touch verilog/arithmetic/float/matrix/model_matrix_float_adder.sv
touch verilog/arithmetic/float/matrix/model_matrix_float_divider.sv
touch verilog/arithmetic/float/matrix/model_matrix_float_multiplier.sv
touch verilog/arithmetic/float/scalar/model_scalar_float_adder.sv
touch verilog/arithmetic/float/scalar/model_scalar_float_divider.sv
touch verilog/arithmetic/float/scalar/model_scalar_float_multiplier.sv
touch verilog/arithmetic/float/tensor/model_tensor_float_adder.sv
touch verilog/arithmetic/float/tensor/model_tensor_float_divider.sv
touch verilog/arithmetic/float/tensor/model_tensor_float_multiplier.sv
touch verilog/arithmetic/float/vector/model_vector_float_adder.sv
touch verilog/arithmetic/float/vector/model_vector_float_divider.sv
touch verilog/arithmetic/float/vector/model_vector_float_multiplier.sv
touch verilog/arithmetic/integer/matrix/model_matrix_integer_adder.sv
touch verilog/arithmetic/integer/matrix/model_matrix_integer_divider.sv
touch verilog/arithmetic/integer/matrix/model_matrix_integer_multiplier.sv
touch verilog/arithmetic/integer/scalar/model_scalar_integer_adder.sv
touch verilog/arithmetic/integer/scalar/model_scalar_integer_divider.sv
touch verilog/arithmetic/integer/scalar/model_scalar_integer_multiplier.sv
touch verilog/arithmetic/integer/tensor/model_tensor_integer_adder.sv
touch verilog/arithmetic/integer/tensor/model_tensor_integer_divider.sv
touch verilog/arithmetic/integer/tensor/model_tensor_integer_multiplier.sv
touch verilog/arithmetic/integer/vector/model_vector_integer_adder.sv
touch verilog/arithmetic/integer/vector/model_vector_integer_divider.sv
touch verilog/arithmetic/integer/vector/model_vector_integer_multiplier.sv
touch verilog/arithmetic/modular/matrix/model_matrix_modular_adder.sv
touch verilog/arithmetic/modular/matrix/model_matrix_modular_inverter.sv
touch verilog/arithmetic/modular/matrix/model_matrix_modular_mod.sv
touch verilog/arithmetic/modular/matrix/model_matrix_modular_multiplier.sv
touch verilog/arithmetic/modular/scalar/model_scalar_modular_adder.sv
touch verilog/arithmetic/modular/scalar/model_scalar_modular_inverter.sv
touch verilog/arithmetic/modular/scalar/model_scalar_modular_mod.sv
touch verilog/arithmetic/modular/scalar/model_scalar_modular_multiplier.sv
touch verilog/arithmetic/modular/tensor/model_tensor_modular_adder.sv
touch verilog/arithmetic/modular/tensor/model_tensor_modular_inverter.sv
touch verilog/arithmetic/modular/tensor/model_tensor_modular_mod.sv
touch verilog/arithmetic/modular/tensor/model_tensor_modular_multiplier.sv
touch verilog/arithmetic/modular/vector/model_vector_modular_adder.sv
touch verilog/arithmetic/modular/vector/model_vector_modular_inverter.sv
touch verilog/arithmetic/modular/vector/model_vector_modular_mod.sv
touch verilog/arithmetic/modular/vector/model_vector_modular_multiplier.sv
touch verilog/controller/FNN/convolutional/model_controller.sv
touch verilog/controller/FNN/standard/model_controller.sv
touch verilog/controller/LSTM/convolutional/model_activation_gate_vector.sv
touch verilog/controller/LSTM/convolutional/model_controller.sv
touch verilog/controller/LSTM/convolutional/model_forget_gate_vector.sv
touch verilog/controller/LSTM/convolutional/model_hidden_gate_vector.sv
touch verilog/controller/LSTM/convolutional/model_input_gate_vector.sv
touch verilog/controller/LSTM/convolutional/model_output_gate_vector.sv
touch verilog/controller/LSTM/convolutional/model_state_gate_vector.sv
touch verilog/controller/LSTM/standard/model_activation_gate_vector.sv
touch verilog/controller/LSTM/standard/model_controller.sv
touch verilog/controller/LSTM/standard/model_forget_gate_vector.sv
touch verilog/controller/LSTM/standard/model_hidden_gate_vector.sv
touch verilog/controller/LSTM/standard/model_input_gate_vector.sv
touch verilog/controller/LSTM/standard/model_output_gate_vector.sv
touch verilog/controller/LSTM/standard/model_state_gate_vector.sv
touch verilog/dnc/memory/model_addressing.sv
touch verilog/dnc/memory/model_allocation_weighting.sv
touch verilog/dnc/memory/model_backward_weighting.sv
touch verilog/dnc/memory/model_content_based_addressing.sv
touch verilog/dnc/memory/model_forward_weighting.sv
touch verilog/dnc/memory/model_memory_matrix.sv
touch verilog/dnc/memory/model_memory_retention_vector.sv
touch verilog/dnc/memory/model_precedence_weighting.sv
touch verilog/dnc/memory/model_read_content_weighting.sv
touch verilog/dnc/memory/model_read_vectors.sv
touch verilog/dnc/memory/model_read_weighting.sv
touch verilog/dnc/memory/model_sort_vector.sv
touch verilog/dnc/memory/model_temporal_link_matrix.sv
touch verilog/dnc/memory/model_usage_vector.sv
touch verilog/dnc/memory/model_write_content_weighting.sv
touch verilog/dnc/memory/model_write_weighting.sv
touch verilog/dnc/read_heads/model_read_heads.sv
touch verilog/dnc/top/model_interface_matrix.sv
touch verilog/dnc/top/model_interface_vector.sv
touch verilog/dnc/top/model_output_vector.sv
touch verilog/dnc/top/model_top.sv
touch verilog/dnc/write_heads/model_write_heads.sv
touch verilog/intro/model_intro_adder_model.sv
touch verilog/math/algebra/matrix/model_matrix_convolution.sv
touch verilog/math/algebra/matrix/model_matrix_inverse.sv
touch verilog/math/algebra/matrix/model_matrix_multiplication.sv
touch verilog/math/algebra/matrix/model_matrix_product.sv
touch verilog/math/algebra/matrix/model_matrix_summation.sv
touch verilog/math/algebra/matrix/model_matrix_transpose.sv
touch verilog/math/algebra/matrix/model_matrix_vector_convolution.sv
touch verilog/math/algebra/matrix/model_matrix_vector_product.sv
touch verilog/math/algebra/matrix/model_transpose_vector_product.sv
touch verilog/math/algebra/tensor/model_tensor_convolution.sv
touch verilog/math/algebra/tensor/model_tensor_inverse.sv
touch verilog/math/algebra/tensor/model_tensor_matrix_convolution.sv
touch verilog/math/algebra/tensor/model_tensor_matrix_product.sv
touch verilog/math/algebra/tensor/model_tensor_multiplication.sv
touch verilog/math/algebra/tensor/model_tensor_product.sv
touch verilog/math/algebra/tensor/model_tensor_summation.sv
touch verilog/math/algebra/tensor/model_tensor_transpose.sv
touch verilog/math/algebra/vector/model_dot_product.sv
touch verilog/math/algebra/vector/model_vector_convolution.sv
touch verilog/math/algebra/vector/model_vector_cosine_similarity.sv
touch verilog/math/algebra/vector/model_vector_module.sv
touch verilog/math/algebra/vector/model_vector_multiplication.sv
touch verilog/math/algebra/vector/model_vector_summation.sv
touch verilog/math/calculus/matrix/model_matrix_differentiation.sv
touch verilog/math/calculus/matrix/model_matrix_integration.sv
touch verilog/math/calculus/matrix/model_matrix_softmax.sv
touch verilog/math/calculus/tensor/model_tensor_differentiation.sv
touch verilog/math/calculus/tensor/model_tensor_integration.sv
touch verilog/math/calculus/tensor/model_tensor_softmax.sv
touch verilog/math/calculus/vector/model_vector_differentiation.sv
touch verilog/math/calculus/vector/model_vector_integration.sv
touch verilog/math/calculus/vector/model_vector_softmax.sv
touch verilog/math/function/matrix/model_matrix_logistic_function.sv
touch verilog/math/function/matrix/model_matrix_oneplus_function.sv
touch verilog/math/function/scalar/model_scalar_logistic_function.sv
touch verilog/math/function/scalar/model_scalar_oneplus_function.sv
touch verilog/math/function/vector/model_vector_logistic_function.sv
touch verilog/math/function/vector/model_vector_oneplus_function.sv
touch verilog/math/series/matrix/model_matrix_cosh_function.sv
touch verilog/math/series/matrix/model_matrix_exponentiator_function.sv
touch verilog/math/series/matrix/model_matrix_logarithm_function.sv
touch verilog/math/series/matrix/model_matrix_power_function.sv
touch verilog/math/series/matrix/model_matrix_sinh_function.sv
touch verilog/math/series/matrix/model_matrix_sqrt_function.sv
touch verilog/math/series/matrix/model_matrix_tanh_function.sv
touch verilog/math/series/scalar/model_scalar_cosh_function.sv
touch verilog/math/series/scalar/model_scalar_exponentiator_function.sv
touch verilog/math/series/scalar/model_scalar_logarithm_function.sv
touch verilog/math/series/scalar/model_scalar_power_function.sv
touch verilog/math/series/scalar/model_scalar_sinh_function.sv
touch verilog/math/series/scalar/model_scalar_sqrt_function.sv
touch verilog/math/series/scalar/model_scalar_tanh_function.sv
touch verilog/math/series/vector/model_vector_cosh_function.sv
touch verilog/math/series/vector/model_vector_exponentiator_function.sv
touch verilog/math/series/vector/model_vector_logarithm_function.sv
touch verilog/math/series/vector/model_vector_power_function.sv
touch verilog/math/series/vector/model_vector_sinh_function.sv
touch verilog/math/series/vector/model_vector_sqrt_function.sv
touch verilog/math/series/vector/model_vector_tanh_function.sv
touch verilog/ntm/memory/model_addressing.sv
touch verilog/ntm/memory/model_content_based_addressing.sv
touch verilog/ntm/read_heads/model_reading.sv
touch verilog/ntm/top/model_interface_matrix.sv
touch verilog/ntm/top/model_interface_vector.sv
touch verilog/ntm/top/model_output_vector.sv
touch verilog/ntm/top/model_top.sv
touch verilog/ntm/write_heads/model_erasing.sv
touch verilog/ntm/write_heads/model_writing.sv
touch verilog/pkg/model_dnc_core_pkg.sv
touch verilog/pkg/model_arithmetic_pkg.sv
touch verilog/pkg/model_ntm_core_pkg.sv
touch verilog/pkg/model_fnn_controller_pkg.sv
touch verilog/pkg/model_intro_pkg.sv
touch verilog/pkg/model_lstm_controller_pkg.sv
touch verilog/pkg/model_math_pkg.sv
touch verilog/pkg/model_state_pkg.sv
touch verilog/state/feedback/model_state_matrix_feedforward.sv
touch verilog/state/feedback/model_state_matrix_input.sv
touch verilog/state/feedback/model_state_matrix_output.sv
touch verilog/state/feedback/model_state_matrix_state.sv
touch verilog/state/outputs/model_state_vector_output.sv
touch verilog/state/outputs/model_state_vector_state.sv
touch verilog/state/top/model_state_top.sv
touch verilog/trainer/FNN/model_trainer.sv
touch verilog/trainer/LSTM/model_activation_trainer.sv
touch verilog/trainer/LSTM/model_forget_trainer.sv
touch verilog/trainer/LSTM/model_input_trainer.sv
touch verilog/trainer/LSTM/model_output_trainer.sv
