emacs -batch vhdl/controller/FNNal/ntm_controller.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/FNNal/ntm_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/FNN/standard/ntm_controller.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/FNN/standard/ntm_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_activation_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_activation_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_controller.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_forget_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_forget_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_hidden_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_input_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_input_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_output_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_output_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTMal/ntm_state_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_activation_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_activation_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_controller.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_forget_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_forget_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_hidden_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_input_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_input_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_output_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_output_trainer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/controller/LSTM/standard/ntm_state_gate_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_addressing.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_allocation_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_backward_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_content_based_addressing.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_forward_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_memory_matrix.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_memory_retention_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_precedence_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_read_content_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_read_vectors.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_read_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_sort_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_temporal_link_matrix.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_usage_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_write_content_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/memory/dnc_write_weighting.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/read_heads/dnc_free_gates.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/read_heads/dnc_read_keys.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/read_heads/dnc_read_modes.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/read_heads/dnc_read_strengths.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/top/dnc_controller_output_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/top/dnc_output_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/top/dnc_read_interface_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/top/dnc_top.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/top/dnc_write_interface_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/write_heads/dnc_allocation_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/write_heads/dnc_erase_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/write_heads/dnc_write_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/write_heads/dnc_write_key.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/write_heads/dnc_write_strength.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/dnc/write_heads/dnc_write_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_matrix_determinant.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_matrix_inversion.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_matrix_product.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_matrix_rank.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_matrix_transpose.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_scalar_product.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/algebra/ntm_vector_product.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_adder.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_divider.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_exponentiator.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_inverter.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_logarithm.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_mod.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_multiplier.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/matrix/ntm_matrix_root.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_adder.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_divider.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_exponentiator.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_inverter.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_logarithm.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_mod.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_multiplier.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/scalar/ntm_scalar_root.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_adder.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_divider.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_exponentiator.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_inverter.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_logarithm.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_mod.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_multiplier.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/arithmetic/vector/ntm_vector_root.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_convolution_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_convolution_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_convolution_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_cosine_similarity_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_cosine_similarity_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_cosine_similarity_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_differentiation_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_differentiation_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_differentiation_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_multiplication_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_multiplication_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_multiplication_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_cosh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_sinh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_tanh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_logistic_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_softmax_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_oneplus_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_cosh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_sinh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_tanh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_logistic_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_softmax_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_oneplus_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_cosh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_sinh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_tanh_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_logistic_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_softmax_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_oneplus_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/matrix/ntm_matrix_summation_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/scalar/ntm_scalar_summation_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/math/function/vector/ntm_vector_summation_function.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/memory/ntm_addressing.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/memory/ntm_content_based_addressing.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/read_heads/ntm_reading.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/top/ntm_controller_output_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/top/ntm_interface_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/top/ntm_output_vector.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/top/ntm_top.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/write_heads/ntm_erasing.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/ntm/write_heads/ntm_writing.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/pkg/dnc_core_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/pkg/ntm_core_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/pkg/ntm_fnn_controller_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/pkg/ntm_lstm_controller_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/pkg/ntm_math_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
