touch verilog/arithmetic/float/matrix/ntm_matrix_adder.sv
touch verilog/arithmetic/float/matrix/ntm_matrix_divider.sv
touch verilog/arithmetic/float/matrix/ntm_matrix_multiplier.sv
touch verilog/arithmetic/float/scalar/ntm_scalar_adder.sv
touch verilog/arithmetic/float/scalar/ntm_scalar_divider.sv
touch verilog/arithmetic/float/scalar/ntm_scalar_float_adder.sv
touch verilog/arithmetic/float/scalar/ntm_scalar_float_divider.sv
touch verilog/arithmetic/float/scalar/ntm_scalar_float_multiplier.sv
touch verilog/arithmetic/float/scalar/ntm_scalar_multiplier.sv
touch verilog/arithmetic/float/tensor/ntm_tensor_adder.sv
touch verilog/arithmetic/float/tensor/ntm_tensor_divider.sv
touch verilog/arithmetic/float/tensor/ntm_tensor_multiplier.sv
touch verilog/arithmetic/float/vector/ntm_vector_adder.sv
touch verilog/arithmetic/float/vector/ntm_vector_divider.sv
touch verilog/arithmetic/float/vector/ntm_vector_multiplier.sv
touch verilog/arithmetic/integer/matrix/ntm_matrix_integer_adder.sv
touch verilog/arithmetic/integer/matrix/ntm_matrix_integer_divider.sv
touch verilog/arithmetic/integer/matrix/ntm_matrix_integer_multiplier.sv
touch verilog/arithmetic/integer/scalar/ntm_scalar_integer_adder.sv
touch verilog/arithmetic/integer/scalar/ntm_scalar_integer_divider.sv
touch verilog/arithmetic/integer/scalar/ntm_scalar_integer_multiplier.sv
touch verilog/arithmetic/integer/tensor/ntm_tensor_integer_adder.sv
touch verilog/arithmetic/integer/tensor/ntm_tensor_integer_divider.sv
touch verilog/arithmetic/integer/tensor/ntm_tensor_integer_multiplier.sv
touch verilog/arithmetic/integer/vector/ntm_vector_integer_adder.sv
touch verilog/arithmetic/integer/vector/ntm_vector_integer_divider.sv
touch verilog/arithmetic/integer/vector/ntm_vector_integer_multiplier.sv
touch verilog/arithmetic/modular/matrix/ntm_matrix_modular_adder.sv
touch verilog/arithmetic/modular/matrix/ntm_matrix_modular_inverter.sv
touch verilog/arithmetic/modular/matrix/ntm_matrix_modular_mod.sv
touch verilog/arithmetic/modular/matrix/ntm_matrix_modular_multiplier.sv
touch verilog/arithmetic/modular/scalar/ntm_scalar_modular_adder.sv
touch verilog/arithmetic/modular/scalar/ntm_scalar_modular_inverter.sv
touch verilog/arithmetic/modular/scalar/ntm_scalar_modular_mod.sv
touch verilog/arithmetic/modular/scalar/ntm_scalar_modular_multiplier.sv
touch verilog/arithmetic/modular/tensor/ntm_tensor_modular_adder.sv
touch verilog/arithmetic/modular/tensor/ntm_tensor_modular_inverter.sv
touch verilog/arithmetic/modular/tensor/ntm_tensor_modular_mod.sv
touch verilog/arithmetic/modular/tensor/ntm_tensor_modular_multiplier.sv
touch verilog/arithmetic/modular/vector/ntm_vector_modular_adder.sv
touch verilog/arithmetic/modular/vector/ntm_vector_modular_inverter.sv
touch verilog/arithmetic/modular/vector/ntm_vector_modular_mod.sv
touch verilog/arithmetic/modular/vector/ntm_vector_modular_multiplier.sv
touch verilog/controller/FNN/convolutional/ntm_controller.sv
touch verilog/controller/FNN/convolutional/ntm_trainer.sv
touch verilog/controller/FNN/standard/ntm_controller.sv
touch verilog/controller/FNN/standard/ntm_trainer.sv
touch verilog/controller/LSTM/convolutional/ntm_activation_gate_vector.sv
touch verilog/controller/LSTM/convolutional/ntm_activation_trainer.sv
touch verilog/controller/LSTM/convolutional/ntm_controller.sv
touch verilog/controller/LSTM/convolutional/ntm_forget_gate_vector.sv
touch verilog/controller/LSTM/convolutional/ntm_forget_trainer.sv
touch verilog/controller/LSTM/convolutional/ntm_hidden_gate_vector.sv
touch verilog/controller/LSTM/convolutional/ntm_input_gate_vector.sv
touch verilog/controller/LSTM/convolutional/ntm_input_trainer.sv
touch verilog/controller/LSTM/convolutional/ntm_output_gate_vector.sv
touch verilog/controller/LSTM/convolutional/ntm_output_trainer.sv
touch verilog/controller/LSTM/convolutional/ntm_state_gate_vector.sv
touch verilog/controller/LSTM/standard/ntm_activation_gate_vector.sv
touch verilog/controller/LSTM/standard/ntm_activation_trainer.sv
touch verilog/controller/LSTM/standard/ntm_controller.sv
touch verilog/controller/LSTM/standard/ntm_forget_gate_vector.sv
touch verilog/controller/LSTM/standard/ntm_forget_trainer.sv
touch verilog/controller/LSTM/standard/ntm_hidden_gate_vector.sv
touch verilog/controller/LSTM/standard/ntm_input_gate_vector.sv
touch verilog/controller/LSTM/standard/ntm_input_trainer.sv
touch verilog/controller/LSTM/standard/ntm_output_gate_vector.sv
touch verilog/controller/LSTM/standard/ntm_output_trainer.sv
touch verilog/controller/LSTM/standard/ntm_state_gate_vector.sv
touch verilog/dnc/memory/dnc_addressing.sv
touch verilog/dnc/memory/dnc_allocation_weighting.sv
touch verilog/dnc/memory/dnc_backward_weighting.sv
touch verilog/dnc/memory/dnc_content_based_addressing.sv
touch verilog/dnc/memory/dnc_forward_weighting.sv
touch verilog/dnc/memory/dnc_memory_matrix.sv
touch verilog/dnc/memory/dnc_memory_retention_vector.sv
touch verilog/dnc/memory/dnc_precedence_weighting.sv
touch verilog/dnc/memory/dnc_read_content_weighting.sv
touch verilog/dnc/memory/dnc_read_vectors.sv
touch verilog/dnc/memory/dnc_read_weighting.sv
touch verilog/dnc/memory/dnc_sort_vector.sv
touch verilog/dnc/memory/dnc_temporal_link_matrix.sv
touch verilog/dnc/memory/dnc_usage_vector.sv
touch verilog/dnc/memory/dnc_write_content_weighting.sv
touch verilog/dnc/memory/dnc_write_weighting.sv
touch verilog/dnc/read_heads/dnc_free_gates.sv
touch verilog/dnc/read_heads/dnc_read_keys.sv
touch verilog/dnc/read_heads/dnc_read_modes.sv
touch verilog/dnc/read_heads/dnc_read_strengths.sv
touch verilog/dnc/top/dnc_output_vector.sv
touch verilog/dnc/top/dnc_read_interface_vector.sv
touch verilog/dnc/top/dnc_top.sv
touch verilog/dnc/top/dnc_write_interface_vector.sv
touch verilog/dnc/write_heads/dnc_allocation_gate.sv
touch verilog/dnc/write_heads/dnc_erase_vector.sv
touch verilog/dnc/write_heads/dnc_write_gate.sv
touch verilog/dnc/write_heads/dnc_write_key.sv
touch verilog/dnc/write_heads/dnc_write_strength.sv
touch verilog/dnc/write_heads/dnc_write_vector.sv
touch verilog/math/algebra/matrix/ntm_matrix_convolution.sv
touch verilog/math/algebra/matrix/ntm_matrix_product.sv
touch verilog/math/algebra/matrix/ntm_matrix_transpose.sv
touch verilog/math/algebra/scalar/ntm_scalar_product.sv
touch verilog/math/algebra/scalar/ntm_scalar_transpose.sv
touch verilog/math/algebra/tensor/ntm_tensor_convolution.sv
touch verilog/math/algebra/tensor/ntm_tensor_product.sv
touch verilog/math/algebra/tensor/ntm_tensor_transpose.sv
touch verilog/math/algebra/vector/ntm_vector_convolution.sv
touch verilog/math/calculus/matrix/ntm_matrix_differentiation.sv
touch verilog/math/calculus/tensor/ntm_tensor_differentiation.sv
touch verilog/math/calculus/vector/ntm_vector_differentiation.sv
touch verilog/math/function/matrix/ntm_matrix_cosh_function.sv
touch verilog/math/function/matrix/ntm_matrix_cosine_similarity_function.sv
touch verilog/math/function/matrix/ntm_matrix_exponentiator_function.sv
touch verilog/math/function/matrix/ntm_matrix_logarithm_function.sv
touch verilog/math/function/matrix/ntm_matrix_logistic_function.sv
touch verilog/math/function/matrix/ntm_matrix_multiplication_function.sv
touch verilog/math/function/matrix/ntm_matrix_oneplus_function.sv
touch verilog/math/function/matrix/ntm_matrix_sinh_function.sv
touch verilog/math/function/matrix/ntm_matrix_softmax_function.sv
touch verilog/math/function/matrix/ntm_matrix_summation_function.sv
touch verilog/math/function/matrix/ntm_matrix_tanh_function.sv
touch verilog/math/function/scalar/ntm_scalar_cosh_function.sv
touch verilog/math/function/scalar/ntm_scalar_cosine_similarity_function.sv
touch verilog/math/function/scalar/ntm_scalar_exponentiator_function.sv
touch verilog/math/function/scalar/ntm_scalar_logarithm_function.sv
touch verilog/math/function/scalar/ntm_scalar_logistic_function.sv
touch verilog/math/function/scalar/ntm_scalar_multiplication_function.sv
touch verilog/math/function/scalar/ntm_scalar_oneplus_function.sv
touch verilog/math/function/scalar/ntm_scalar_sinh_function.sv
touch verilog/math/function/scalar/ntm_scalar_softmax_function.sv
touch verilog/math/function/scalar/ntm_scalar_summation_function.sv
touch verilog/math/function/scalar/ntm_scalar_tanh_function.sv
touch verilog/math/function/vector/ntm_vector_cosh_function.sv
touch verilog/math/function/vector/ntm_vector_cosine_similarity_function.sv
touch verilog/math/function/vector/ntm_vector_exponentiator_function.sv
touch verilog/math/function/vector/ntm_vector_logarithm_function.sv
touch verilog/math/function/vector/ntm_vector_logistic_function.sv
touch verilog/math/function/vector/ntm_vector_multiplication_function.sv
touch verilog/math/function/vector/ntm_vector_oneplus_function.sv
touch verilog/math/function/vector/ntm_vector_sinh_function.sv
touch verilog/math/function/vector/ntm_vector_softmax_function.sv
touch verilog/math/function/vector/ntm_vector_summation_function.sv
touch verilog/math/function/vector/ntm_vector_tanh_function.sv
touch verilog/ntm/memory/ntm_addressing.sv
touch verilog/ntm/memory/ntm_content_based_addressing.sv
touch verilog/ntm/read_heads/ntm_reading.sv
touch verilog/ntm/top/ntm_interface_vector.sv
touch verilog/ntm/top/ntm_output_vector.sv
touch verilog/ntm/top/ntm_top.sv
touch verilog/ntm/write_heads/ntm_erasing.sv
touch verilog/ntm/write_heads/ntm_writing.sv
touch verilog/pkg/dnc_core_pkg.sv
touch verilog/pkg/ntm_arithmetic_pkg.sv
touch verilog/pkg/ntm_core_pkg.sv
touch verilog/pkg/ntm_fnn_controller_pkg.sv
touch verilog/pkg/ntm_lstm_controller_pkg.sv
touch verilog/pkg/ntm_math_pkg.sv
touch verilog/pkg/ntm_state_pkg.sv
touch verilog/state/feedback/ntm_state_matrix_feedforward.sv
touch verilog/state/feedback/ntm_state_matrix_input.sv
touch verilog/state/feedback/ntm_state_matrix_output.sv
touch verilog/state/feedback/ntm_state_matrix_state.sv
touch verilog/state/outputs/ntm_state_vector_output.sv
touch verilog/state/outputs/ntm_state_vector_state.sv
touch verilog/state/top/ntm_state_top.sv
