vhd2vl vhdl/controller/LSTM/convolutional/ntm_controller.vhd verilog/controller/LSTM/convolutional/ntm_controller.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_controller.vhd verilog/controller/LSTM/standard/ntm_controller.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_input_trainer.vhd verilog/controller/LSTM/convolutional/ntm_input_trainer.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_input_trainer.vhd verilog/controller/LSTM/standard/ntm_input_trainer.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_forget_trainer.vhd verilog/controller/LSTM/convolutional/ntm_forget_trainer.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_output_trainer.vhd verilog/controller/LSTM/convolutional/ntm_output_trainer.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_forget_trainer.vhd verilog/controller/LSTM/standard/ntm_forget_trainer.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_output_trainer.vhd verilog/controller/LSTM/standard/ntm_output_trainer.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_input_gate_vector.vhd verilog/controller/LSTM/convolutional/ntm_input_gate_vector.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_state_gate_vector.vhd verilog/controller/LSTM/convolutional/ntm_state_gate_vector.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_input_gate_vector.vhd verilog/controller/LSTM/standard/ntm_input_gate_vector.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_state_gate_vector.vhd verilog/controller/LSTM/standard/ntm_state_gate_vector.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_activation_trainer.vhd verilog/controller/LSTM/convolutional/ntm_activation_trainer.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_forget_gate_vector.vhd verilog/controller/LSTM/convolutional/ntm_forget_gate_vector.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_hidden_gate_vector.vhd verilog/controller/LSTM/convolutional/ntm_hidden_gate_vector.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_output_gate_vector.vhd verilog/controller/LSTM/convolutional/ntm_output_gate_vector.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_activation_trainer.vhd verilog/controller/LSTM/standard/ntm_activation_trainer.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_forget_gate_vector.vhd verilog/controller/LSTM/standard/ntm_forget_gate_vector.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_hidden_gate_vector.vhd verilog/controller/LSTM/standard/ntm_hidden_gate_vector.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_output_gate_vector.vhd verilog/controller/LSTM/standard/ntm_output_gate_vector.sv
vhd2vl vhdl/controller/LSTM/convolutional/ntm_activation_gate_vector.vhd verilog/controller/LSTM/convolutional/ntm_activation_gate_vector.sv
vhd2vl vhdl/controller/LSTM/standard/ntm_activation_gate_vector.vhd verilog/controller/LSTM/standard/ntm_activation_gate_vector.sv

