###################################################################################
##                                            __ _      _     _                  ##
##                                           / _(_)    | |   | |                 ##
##                __ _ _   _  ___  ___ _ __ | |_ _  ___| | __| |                 ##
##               / _` | | | |/ _ \/ _ \ '_ \|  _| |/ _ \ |/ _` |                 ##
##              | (_| | |_| |  __/  __/ | | | | | |  __/ | (_| |                 ##
##               \__, |\__,_|\___|\___|_| |_|_| |_|\___|_|\__,_|                 ##
##                  | |                                                          ##
##                  |_|                                                          ##
##                                                                               ##
##                                                                               ##
##              QueenField                                                       ##
##              Multi-Processor System on Chip                                   ##
##                                                                               ##
###################################################################################

###################################################################################
##                                                                               ##
## Copyright (c) 2022-2025 by the author(s)                                      ##
##                                                                               ##
## Permission is hereby granted, free of charge, to any person obtaining a copy  ##
## of this software and associated documentation files (the "Software"), to deal ##
## in the Software without restriction, including without limitation the rights  ##
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     ##
## copies of the Software, and to permit persons to whom the Software is         ##
## furnished to do so, subject to the following conditions:                      ##
##                                                                               ##
## The above copyright notice and this permission notice shall be included in    ##
## all copies or substantial portions of the Software.                           ##
##                                                                               ##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    ##
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      ##
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   ##
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        ##
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, ##
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN     ##
## THE SOFTWARE.                                                                 ##
##                                                                               ##
## ============================================================================= ##
## Author(s):                                                                    ##
##   Paco Reina Campo <pacoreinacampo@queenfield.tech>                           ##
##                                                                               ##
###################################################################################

touch code/classes/philosophers/ntm_philosophers/application/design_if.sv
touch code/classes/philosophers/ntm_philosophers/application/fsm.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_agent.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_driver.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_environment.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_monitor.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_sample.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_scoreboard.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_sequence_item.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_sequence.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_testbench.sv
touch code/classes/philosophers/ntm_philosophers/library/peripheral_test.sv
touch code/classes/soldiers/ntm_soldiers/application/design_if.sv
touch code/classes/soldiers/ntm_soldiers/application/fsm.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_agent.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_driver.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_environment.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_monitor.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_sample.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_scoreboard.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_sequence_item.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_sequence.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_testbench.sv
touch code/classes/soldiers/ntm_soldiers/library/peripheral_test.sv
touch code/classes/workers/ntm_workers/application/design_if.sv
touch code/classes/workers/ntm_workers/application/fsm.sv
touch code/classes/workers/ntm_workers/library/peripheral_agent.sv
touch code/classes/workers/ntm_workers/library/peripheral_driver.sv
touch code/classes/workers/ntm_workers/library/peripheral_environment.sv
touch code/classes/workers/ntm_workers/library/peripheral_monitor.sv
touch code/classes/workers/ntm_workers/library/peripheral_sample.sv
touch code/classes/workers/ntm_workers/library/peripheral_scoreboard.sv
touch code/classes/workers/ntm_workers/library/peripheral_sequence_item.sv
touch code/classes/workers/ntm_workers/library/peripheral_sequence.sv
touch code/classes/workers/ntm_workers/library/peripheral_testbench.sv
touch code/classes/workers/ntm_workers/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/application/design_if.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/application/fsm.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/application/design_if.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/application/fsm.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/processing_unit/mimd/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/application/design_if.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/application/fsm.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/processing_unit/misd/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/application/design_if.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/application/fsm.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/processing_unit/simd/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/application/design_if.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/application/fsm.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/processing_unit/sisd/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/application/design_if.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/application/fsm.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip/library/peripheral_test.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/application/design_if.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/application/fsm.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_agent.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_driver.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_environment.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_monitor.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_sample.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_scoreboard.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_sequence_item.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_sequence.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_testbench.sv
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip/library/peripheral_test.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/application/design_if.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/application/fsm.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_agent.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_driver.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_environment.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_monitor.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_sample.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_scoreboard.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_sequence_item.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_sequence.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_testbench.sv
touch code/computing/computer_architecture/harvard_architecture/pu_or1k/library/peripheral_test.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/application/design_if.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/application/fsm.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_agent.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_driver.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_environment.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_monitor.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_sample.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_scoreboard.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_sequence_item.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_sequence.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_testbench.sv
touch code/computing/computer_architecture/harvard_architecture/pu_riscv/library/peripheral_test.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/application/design_if.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/application/fsm.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_agent.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_driver.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_environment.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_monitor.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_sample.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_scoreboard.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_sequence_item.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_sequence.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_testbench.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_or1k/library/peripheral_test.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/application/design_if.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/application/fsm.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_agent.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_driver.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_environment.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_monitor.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_sample.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_scoreboard.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_sequence_item.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_sequence.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_testbench.sv
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv/library/peripheral_test.sv
touch code/computing/information/bit/bit/application/design_if.sv
touch code/computing/information/bit/bit/application/fsm.sv
touch code/computing/information/bit/bit/library/peripheral_agent.sv
touch code/computing/information/bit/bit/library/peripheral_driver.sv
touch code/computing/information/bit/bit/library/peripheral_environment.sv
touch code/computing/information/bit/bit/library/peripheral_monitor.sv
touch code/computing/information/bit/bit/library/peripheral_sample.sv
touch code/computing/information/bit/bit/library/peripheral_scoreboard.sv
touch code/computing/information/bit/bit/library/peripheral_sequence_item.sv
touch code/computing/information/bit/bit/library/peripheral_sequence.sv
touch code/computing/information/bit/bit/library/peripheral_testbench.sv
touch code/computing/information/bit/bit/library/peripheral_test.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/application/design_if.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/application/fsm.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_agent.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_driver.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_environment.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_monitor.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_sample.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_scoreboard.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_sequence_item.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_sequence.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_testbench.sv
touch code/computing/information/combinational_logic/arithmetic_circuits/library/peripheral_test.sv
touch code/computing/information/combinational_logic/logic_circuits/application/design_if.sv
touch code/computing/information/combinational_logic/logic_circuits/application/fsm.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_agent.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_driver.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_environment.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_monitor.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_sample.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_scoreboard.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_sequence_item.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_sequence.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_testbench.sv
touch code/computing/information/combinational_logic/logic_circuits/library/peripheral_test.sv
touch code/computing/information/finite_state_machine/finite_state_machine/application/design_if.sv
touch code/computing/information/finite_state_machine/finite_state_machine/application/fsm.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_agent.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_driver.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_environment.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_monitor.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_sample.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_scoreboard.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_sequence_item.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_sequence.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_testbench.sv
touch code/computing/information/finite_state_machine/finite_state_machine/library/peripheral_test.sv
touch code/computing/information/logic_gate/and_gate/application/design_if.sv
touch code/computing/information/logic_gate/and_gate/application/fsm.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/and_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/nand_gate/application/design_if.sv
touch code/computing/information/logic_gate/nand_gate/application/fsm.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/nand_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/nor_gate/application/design_if.sv
touch code/computing/information/logic_gate/nor_gate/application/fsm.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/nor_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/not_gate/application/design_if.sv
touch code/computing/information/logic_gate/not_gate/application/fsm.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/not_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/or_gate/application/design_if.sv
touch code/computing/information/logic_gate/or_gate/application/fsm.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/or_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/xnor_gate/application/design_if.sv
touch code/computing/information/logic_gate/xnor_gate/application/fsm.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/xnor_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/xor_gate/application/design_if.sv
touch code/computing/information/logic_gate/xor_gate/application/fsm.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/xor_gate/library/peripheral_test.sv
touch code/computing/information/logic_gate/yes_gate/application/design_if.sv
touch code/computing/information/logic_gate/yes_gate/application/fsm.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_agent.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_driver.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_environment.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_monitor.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_sample.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_scoreboard.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_sequence_item.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_sequence.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_testbench.sv
touch code/computing/information/logic_gate/yes_gate/library/peripheral_test.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/application/design_if.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/application/fsm.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_agent.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_driver.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_environment.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_monitor.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_sample.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_scoreboard.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_sequence_item.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_sequence.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_testbench.sv
touch code/computing/information/pushdown_automaton/pushdown_automaton/library/peripheral_test.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/application/design_if.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/application/fsm.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_agent.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_driver.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_environment.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_monitor.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_sample.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_scoreboard.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_sequence_item.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_sequence.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_testbench.sv
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network/library/peripheral_test.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/application/design_if.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/application/fsm.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_agent.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_driver.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_environment.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_monitor.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_sample.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_scoreboard.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_sequence_item.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_sequence.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_testbench.sv
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network/library/peripheral_test.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/application/design_if.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/application/fsm.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_agent.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_driver.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_environment.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_monitor.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_sample.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_scoreboard.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_sequence_item.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_sequence.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_testbench.sv
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network/library/peripheral_test.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/application/design_if.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/application/fsm.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_agent.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_driver.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_environment.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_monitor.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_sample.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_scoreboard.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_sequence_item.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_sequence.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_testbench.sv
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer/library/peripheral_test.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/application/design_if.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/application/fsm.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_agent.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_driver.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_environment.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_monitor.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_sample.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_scoreboard.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_sequence_item.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_sequence.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_testbench.sv
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer/library/peripheral_test.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/application/design_if.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/application/fsm.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_agent.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_driver.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_environment.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_monitor.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_sample.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_scoreboard.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_sequence_item.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_sequence.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_testbench.sv
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer/library/peripheral_test.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/application/design_if.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/application/fsm.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_agent.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_driver.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_environment.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_monitor.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_sample.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_scoreboard.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_sequence_item.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_sequence.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_testbench.sv
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine/library/peripheral_test.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/application/design_if.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/application/fsm.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_agent.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_driver.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_environment.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_monitor.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_sample.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_scoreboard.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_sequence_item.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_sequence.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_testbench.sv
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine/library/peripheral_test.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/application/design_if.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/application/fsm.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_agent.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_driver.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_environment.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_monitor.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_sample.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_scoreboard.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_sequence_item.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_sequence.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_testbench.sv
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine/library/peripheral_test.sv
