set model_path         "../../../../../../../model/vhdl/code"
set model_pkg_path     "../../../../../../../model/vhdl/code/pkg"
set design_path        "../../../../../../../rtl/vhdl/code"
set design_pkg_path    "../../../../../../../rtl/vhdl/code/pkg"
set verification_path  "../../../../../../../bench/vhdl/code/procedures/design"
set simulation_path    "../../../../../../../sim/vhdl/verification/procedures"
