touch code/algebra/matrix/accelerator_matrix_convolution.vhd
touch code/algebra/matrix/accelerator_matrix_differentiation.vhd
touch code/algebra/matrix/accelerator_matrix_integration.vhd
touch code/algebra/matrix/accelerator_matrix_inverse.vhd
touch code/algebra/matrix/accelerator_matrix_multiplication.vhd
touch code/algebra/matrix/accelerator_matrix_product.vhd
touch code/algebra/matrix/accelerator_matrix_softmax.vhd
touch code/algebra/matrix/accelerator_matrix_summation.vhd
touch code/algebra/matrix/accelerator_matrix_transpose.vhd
touch code/algebra/matrix/accelerator_matrix_vector_convolution.vhd
touch code/algebra/matrix/accelerator_matrix_vector_product.vhd
touch code/algebra/matrix/accelerator_transpose_vector_product.vhd
touch code/algebra/tensor/accelerator_tensor_convolution.vhd
touch code/algebra/tensor/accelerator_tensor_differentiation.vhd
touch code/algebra/tensor/accelerator_tensor_integration.vhd
touch code/algebra/tensor/accelerator_tensor_inverse.vhd
touch code/algebra/tensor/accelerator_tensor_matrix_convolution.vhd
touch code/algebra/tensor/accelerator_tensor_matrix_product.vhd
touch code/algebra/tensor/accelerator_tensor_product.vhd
touch code/algebra/tensor/accelerator_tensor_softmax.vhd
touch code/algebra/tensor/accelerator_tensor_transpose.vhd
touch code/algebra/vector/accelerator_dot_product.vhd
touch code/algebra/vector/accelerator_vector_convolution.vhd
touch code/algebra/vector/accelerator_vector_cosine_similarity.vhd
touch code/algebra/vector/accelerator_vector_differentiation.vhd
touch code/algebra/vector/accelerator_vector_integration.vhd
touch code/algebra/vector/accelerator_vector_module.vhd
touch code/algebra/vector/accelerator_vector_multiplication.vhd
touch code/algebra/vector/accelerator_vector_softmax.vhd
touch code/algebra/vector/accelerator_vector_summation.vhd
touch code/architecture/mpsoc/ahb3/accelerator_mpsoc_ahb3.vhd
touch code/architecture/mpsoc/apb4/accelerator_mpsoc_apb4.vhd
touch code/architecture/mpsoc/axi4/accelerator_mpsoc_axi4.vhd
touch code/architecture/mpsoc/bb/accelerator_mpsoc_bb.vhd
touch code/architecture/mpsoc/biu/accelerator_mpsoc_biu.vhd
touch code/architecture/mpsoc/wb/accelerator_mpsoc_wb.vhd
touch code/architecture/pu/ahb3/accelerator_pu_ahb3.vhd
touch code/architecture/pu/apb4/accelerator_pu_apb4.vhd
touch code/architecture/pu/axi4/accelerator_pu_axi4.vhd
touch code/architecture/pu/bb/accelerator_pu_bb.vhd
touch code/architecture/pu/biu/accelerator_pu_biu.vhd
touch code/architecture/pu/wb/accelerator_pu_wb.vhd
touch code/architecture/soc/ahb3/accelerator_soc_ahb3.vhd
touch code/architecture/soc/apb4/accelerator_soc_apb4.vhd
touch code/architecture/soc/axi4/accelerator_soc_axi4.vhd
touch code/architecture/soc/bb/accelerator_soc_bb.vhd
touch code/architecture/soc/biu/accelerator_soc_biu.vhd
touch code/architecture/soc/wb/accelerator_soc_wb.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_adder.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_divider.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_multiplier.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_subtractor.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_adder.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_divider.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_multiplier.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_subtractor.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_adder.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_divider.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_multiplier.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_subtractor.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_adder.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_divider.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_multiplier.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_subtractor.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_adder.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_divider.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_multiplier.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_subtractor.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_adder.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_divider.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_multiplier.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_subtractor.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_adder.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_divider.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_multiplier.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_subtractor.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_adder.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_divider.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_multiplier.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_subtractor.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_adder.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_divider.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_multiplier.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_subtractor.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_adder.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_divider.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_multiplier.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_subtractor.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_adder.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_divider.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_multiplier.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_subtractor.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_adder.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_divider.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_multiplier.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_subtractor.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_adder.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_divider.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_multiplier.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_subtractor.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_adder.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_divider.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_multiplier.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_subtractor.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_adder.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_divider.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_multiplier.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_subtractor.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_adder.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_divider.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_multiplier.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_subtractor.vhd
touch code/math/matrix/accelerator_matrix_cosh_function.vhd
touch code/math/matrix/accelerator_matrix_exponentiator_function.vhd
touch code/math/matrix/accelerator_matrix_logarithm_function.vhd
touch code/math/matrix/accelerator_matrix_logistic_function.vhd
touch code/math/matrix/accelerator_matrix_oneplus_function.vhd
touch code/math/matrix/accelerator_matrix_sinh_function.vhd
touch code/math/matrix/accelerator_matrix_tanh_function.vhd
touch code/math/scalar/accelerator_scalar_cosh_function.vhd
touch code/math/scalar/accelerator_scalar_exponentiator_function.vhd
touch code/math/scalar/accelerator_scalar_logarithm_function.vhd
touch code/math/scalar/accelerator_scalar_logistic_function.vhd
touch code/math/scalar/accelerator_scalar_oneplus_function.vhd
touch code/math/scalar/accelerator_scalar_sinh_function.vhd
touch code/math/scalar/accelerator_scalar_tanh_function.vhd
touch code/math/vector/accelerator_vector_cosh_function.vhd
touch code/math/vector/accelerator_vector_exponentiator_function.vhd
touch code/math/vector/accelerator_vector_logarithm_function.vhd
touch code/math/vector/accelerator_vector_logistic_function.vhd
touch code/math/vector/accelerator_vector_oneplus_function.vhd
touch code/math/vector/accelerator_vector_sinh_function.vhd
touch code/math/vector/accelerator_vector_tanh_function.vhd
touch code/nn/fnn/convolutional/accelerator_controller.vhd
touch code/nn/fnn/standard/accelerator_controller.vhd
touch code/nn/lstm/convolutional/accelerator_activation_gate_vector.vhd
touch code/nn/lstm/convolutional/accelerator_controller.vhd
touch code/nn/lstm/convolutional/accelerator_forget_gate_vector.vhd
touch code/nn/lstm/convolutional/accelerator_hidden_gate_vector.vhd
touch code/nn/lstm/convolutional/accelerator_input_gate_vector.vhd
touch code/nn/lstm/convolutional/accelerator_output_gate_vector.vhd
touch code/nn/lstm/convolutional/accelerator_state_gate_vector.vhd
touch code/nn/lstm/standard/accelerator_activation_gate_vector.vhd
touch code/nn/lstm/standard/accelerator_controller.vhd
touch code/nn/lstm/standard/accelerator_forget_gate_vector.vhd
touch code/nn/lstm/standard/accelerator_hidden_gate_vector.vhd
touch code/nn/lstm/standard/accelerator_input_gate_vector.vhd
touch code/nn/lstm/standard/accelerator_output_gate_vector.vhd
touch code/nn/lstm/standard/accelerator_state_gate_vector.vhd
touch code/nn/ntm/memory/accelerator_addressing.vhd
touch code/nn/ntm/memory/accelerator_content_based_addressing.vhd
touch code/nn/ntm/read_heads/accelerator_reading.vhd
touch code/nn/ntm/top/accelerator_interface_matrix.vhd
touch code/nn/ntm/top/accelerator_interface_vector.vhd
touch code/nn/ntm/top/accelerator_output_vector.vhd
touch code/nn/ntm/top/accelerator_top.vhd
touch code/nn/ntm/write_heads/accelerator_erasing.vhd
touch code/nn/ntm/write_heads/accelerator_writing.vhd
touch code/pkg/accelerator_ann_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_arithmetic_vhdl_pkg.vhd
touch code/pkg/accelerator_core_vhdl_pkg.vhd
touch code/pkg/accelerator_fnn_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_lstm_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_math_vhdl_pkg.vhd
touch code/pkg/accelerator_pnn_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_state_vhdl_pkg.vhd
touch code/state/feedback/accelerator_state_matrix_feedforward.vhd
touch code/state/feedback/accelerator_state_matrix_input.vhd
touch code/state/feedback/accelerator_state_matrix_output.vhd
touch code/state/feedback/accelerator_state_matrix_state.vhd
touch code/state/outputs/accelerator_state_vector_output.vhd
touch code/state/outputs/accelerator_state_vector_state.vhd
touch code/state/pnn/convolutional/accelerator_controller.vhd
touch code/state/pnn/standard/accelerator_controller.vhd
touch code/state/top/accelerator_state_top.vhd
touch code/trainer/differentiation/accelerator_trainer_matrix_differentiation.vhd
touch code/trainer/differentiation/accelerator_trainer_vector_differentiation.vhd
touch code/trainer/fnn/accelerator_trainer.vhd
touch code/trainer/lstm/accelerator_activation_trainer.vhd
touch code/trainer/lstm/accelerator_forget_trainer.vhd
touch code/trainer/lstm/accelerator_input_trainer.vhd
touch code/trainer/lstm/accelerator_output_trainer.vhd
touch code/trainer/pnn/accelerator_trainer.vhd
