touch code/architecture/mpsoc/accelerator_mpsoc.vhd
touch code/architecture/pu/accelerator_pu.vhd
touch code/architecture/soc/accelerator_soc.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_adder.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_divider.vhd
touch code/arithmetic/definition/matrix/accelerator_matrix_float_multiplier.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_adder.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_divider.vhd
touch code/arithmetic/definition/scalar/accelerator_scalar_float_multiplier.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_adder.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_divider.vhd
touch code/arithmetic/definition/tensor/accelerator_tensor_float_multiplier.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_adder.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_divider.vhd
touch code/arithmetic/definition/vector/accelerator_vector_float_multiplier.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_adder.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_divider.vhd
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_multiplier.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_adder.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_divider.vhd
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_multiplier.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_adder.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_divider.vhd
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_multiplier.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_adder.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_divider.vhd
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_multiplier.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_adder.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_divider.vhd
touch code/arithmetic/float/matrix/accelerator_matrix_float_multiplier.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_adder.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_divider.vhd
touch code/arithmetic/float/scalar/accelerator_scalar_float_multiplier.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_adder.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_divider.vhd
touch code/arithmetic/float/tensor/accelerator_tensor_float_multiplier.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_adder.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_divider.vhd
touch code/arithmetic/float/vector/accelerator_vector_float_multiplier.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_adder.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_divider.vhd
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_multiplier.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_adder.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_divider.vhd
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_multiplier.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_adder.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_divider.vhd
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_multiplier.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_adder.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_divider.vhd
touch code/arithmetic/integer/vector/accelerator_vector_integer_multiplier.vhd
touch code/math/algebra/matrix/accelerator_matrix_convolution.vhd
touch code/math/algebra/matrix/accelerator_matrix_inverse.vhd
touch code/math/algebra/matrix/accelerator_matrix_multiplication.vhd
touch code/math/algebra/matrix/accelerator_matrix_product.vhd
touch code/math/algebra/matrix/accelerator_matrix_summation.vhd
touch code/math/algebra/matrix/accelerator_matrix_transpose.vhd
touch code/math/algebra/matrix/accelerator_matrix_vector_convolution.vhd
touch code/math/algebra/matrix/accelerator_matrix_vector_product.vhd
touch code/math/algebra/matrix/accelerator_transpose_vector_product.vhd
touch code/math/algebra/tensor/accelerator_tensor_convolution.vhd
touch code/math/algebra/tensor/accelerator_tensor_inverse.vhd
touch code/math/algebra/tensor/accelerator_tensor_matrix_convolution.vhd
touch code/math/algebra/tensor/accelerator_tensor_matrix_product.vhd
touch code/math/algebra/tensor/accelerator_tensor_product.vhd
touch code/math/algebra/tensor/accelerator_tensor_transpose.vhd
touch code/math/algebra/vector/accelerator_dot_product.vhd
touch code/math/algebra/vector/accelerator_vector_convolution.vhd
touch code/math/algebra/vector/accelerator_vector_cosine_similarity.vhd
touch code/math/algebra/vector/accelerator_vector_module.vhd
touch code/math/algebra/vector/accelerator_vector_multiplication.vhd
touch code/math/algebra/vector/accelerator_vector_summation.vhd
touch code/math/calculus/matrix/accelerator_matrix_differentiation.vhd
touch code/math/calculus/matrix/accelerator_matrix_integration.vhd
touch code/math/calculus/matrix/accelerator_matrix_softmax.vhd
touch code/math/calculus/tensor/accelerator_tensor_differentiation.vhd
touch code/math/calculus/tensor/accelerator_tensor_integration.vhd
touch code/math/calculus/tensor/accelerator_tensor_softmax.vhd
touch code/math/calculus/vector/accelerator_vector_differentiation.vhd
touch code/math/calculus/vector/accelerator_vector_integration.vhd
touch code/math/calculus/vector/accelerator_vector_softmax.vhd
touch code/math/function/matrix/accelerator_matrix_logistic_function.vhd
touch code/math/function/matrix/accelerator_matrix_oneplus_function.vhd
touch code/math/function/scalar/accelerator_scalar_logistic_function.vhd
touch code/math/function/scalar/accelerator_scalar_oneplus_function.vhd
touch code/math/function/vector/accelerator_vector_logistic_function.vhd
touch code/math/function/vector/accelerator_vector_oneplus_function.vhd
touch code/math/series/matrix/accelerator_matrix_cosh_function.vhd
touch code/math/series/matrix/accelerator_matrix_exponentiator_function.vhd
touch code/math/series/matrix/accelerator_matrix_logarithm_function.vhd
touch code/math/series/matrix/accelerator_matrix_sinh_function.vhd
touch code/math/series/matrix/accelerator_matrix_tanh_function.vhd
touch code/math/series/scalar/accelerator_scalar_cosh_function.vhd
touch code/math/series/scalar/accelerator_scalar_exponentiator_function.vhd
touch code/math/series/scalar/accelerator_scalar_logarithm_function.vhd
touch code/math/series/scalar/accelerator_scalar_sinh_function.vhd
touch code/math/series/scalar/accelerator_scalar_tanh_function.vhd
touch code/math/series/vector/accelerator_vector_cosh_function.vhd
touch code/math/series/vector/accelerator_vector_exponentiator_function.vhd
touch code/math/series/vector/accelerator_vector_logarithm_function.vhd
touch code/math/series/vector/accelerator_vector_sinh_function.vhd
touch code/math/series/vector/accelerator_vector_tanh_function.vhd
touch code/nn/ANN/components/accelerator_masked_multi_head_attention.vhd
touch code/nn/ANN/components/accelerator_masked_scaled_dot_product_attention.vhd
touch code/nn/ANN/components/accelerator_multi_head_attention.vhd
touch code/nn/ANN/components/accelerator_scaled_dot_product_attention.vhd
touch code/nn/ANN/controller/fnn/convolutional/accelerator_fnn.vhd
touch code/nn/ANN/controller/fnn/standard/accelerator_fnn.vhd
touch code/nn/ANN/controller/lstm/convolutional/accelerator_lstm.vhd
touch code/nn/ANN/controller/lstm/standard/accelerator_lstm.vhd
touch code/nn/ANN/functions/accelerator_layer_norm.vhd
touch code/nn/ANN/functions/accelerator_positional_encoding.vhd
touch code/nn/ANN/inputs/accelerator_inputs_vector.vhd
touch code/nn/ANN/inputs/accelerator_keys_vector.vhd
touch code/nn/ANN/inputs/accelerator_queries_vector.vhd
touch code/nn/ANN/inputs/accelerator_values_vector.vhd
touch code/nn/ANN/top/accelerator_controller.vhd
touch code/nn/ANN/top/accelerator_decoder.vhd
touch code/nn/ANN/top/accelerator_encoder.vhd
touch code/nn/FNN/convolutional/accelerator_controller.vhd
touch code/nn/FNN/standard/accelerator_controller.vhd
touch code/nn/LSTM/convolutional/accelerator_activation_gate_vector.vhd
touch code/nn/LSTM/convolutional/accelerator_controller.vhd
touch code/nn/LSTM/convolutional/accelerator_forget_gate_vector.vhd
touch code/nn/LSTM/convolutional/accelerator_hidden_gate_vector.vhd
touch code/nn/LSTM/convolutional/accelerator_input_gate_vector.vhd
touch code/nn/LSTM/convolutional/accelerator_output_gate_vector.vhd
touch code/nn/LSTM/convolutional/accelerator_state_gate_vector.vhd
touch code/nn/LSTM/standard/accelerator_activation_gate_vector.vhd
touch code/nn/LSTM/standard/accelerator_controller.vhd
touch code/nn/LSTM/standard/accelerator_forget_gate_vector.vhd
touch code/nn/LSTM/standard/accelerator_hidden_gate_vector.vhd
touch code/nn/LSTM/standard/accelerator_input_gate_vector.vhd
touch code/nn/LSTM/standard/accelerator_output_gate_vector.vhd
touch code/nn/LSTM/standard/accelerator_state_gate_vector.vhd
touch code/nn/NTM/memory/accelerator_addressing.vhd
touch code/nn/NTM/memory/accelerator_content_based_addressing.vhd
touch code/nn/NTM/read_heads/accelerator_reading.vhd
touch code/nn/NTM/top/accelerator_interface_matrix.vhd
touch code/nn/NTM/top/accelerator_interface_vector.vhd
touch code/nn/NTM/top/accelerator_output_vector.vhd
touch code/nn/NTM/top/accelerator_top.vhd
touch code/nn/NTM/write_heads/accelerator_erasing.vhd
touch code/nn/NTM/write_heads/accelerator_writing.vhd
touch code/pkg/accelerator_arithmetic_vhdl_pkg.vhd
touch code/pkg/accelerator_core_vhdl_pkg.vhd
touch code/pkg/accelerator_fnn_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_linear_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_lstm_controller_vhdl_pkg.vhd
touch code/pkg/accelerator_math_vhdl_pkg.vhd
touch code/pkg/accelerator_state_vhdl_pkg.vhd
touch code/pkg/accelerator_transformer_controller_vhdl_pkg.vhd
touch code/state/feedback/accelerator_state_matrix_feedforward.vhd
touch code/state/feedback/accelerator_state_matrix_input.vhd
touch code/state/feedback/accelerator_state_matrix_output.vhd
touch code/state/feedback/accelerator_state_matrix_state.vhd
touch code/state/linear/convolutional/accelerator_controller.vhd
touch code/state/linear/standard/accelerator_controller.vhd
touch code/state/outputs/accelerator_state_vector_output.vhd
touch code/state/outputs/accelerator_state_vector_state.vhd
touch code/state/top/accelerator_state_top.vhd
touch code/trainer/differentiation/accelerator_trainer_matrix_differentiation.vhd
touch code/trainer/differentiation/accelerator_trainer_vector_differentiation.vhd
touch code/trainer/FNN/accelerator_trainer.vhd
touch code/trainer/linear/accelerator_trainer.vhd
touch code/trainer/LSTM/accelerator_activation_trainer.vhd
touch code/trainer/LSTM/accelerator_forget_trainer.vhd
touch code/trainer/LSTM/accelerator_input_trainer.vhd
touch code/trainer/LSTM/accelerator_output_trainer.vhd
