touch library/algebra/matrix/ntm_matrix_convolution.py
touch library/algebra/matrix/ntm_matrix_differentiation.py
touch library/algebra/matrix/ntm_matrix_integration.py
touch library/algebra/matrix/ntm_matrix_inverse.py
touch library/algebra/matrix/ntm_matrix_multiplication.py
touch library/algebra/matrix/ntm_matrix_product.py
touch library/algebra/matrix/ntm_matrix_softmax.py
touch library/algebra/matrix/ntm_matrix_summation.py
touch library/algebra/matrix/ntm_matrix_transpose.py
touch library/algebra/matrix/ntm_matrix_vector_convolution.py
touch library/algebra/matrix/ntm_matrix_vector_product.py
touch library/algebra/matrix/ntm_transpose_vector_product.py
touch library/algebra/scalar/ntm_scalar_multiplication.py
touch library/algebra/scalar/ntm_scalar_summation.py
touch library/algebra/tensor/ntm_tensor_convolution.py
touch library/algebra/tensor/ntm_tensor_differentiation.py
touch library/algebra/tensor/ntm_tensor_integration.py
touch library/algebra/tensor/ntm_tensor_inverse.py
touch library/algebra/tensor/ntm_tensor_matrix_convolution.py
touch library/algebra/tensor/ntm_tensor_matrix_product.py
touch library/algebra/tensor/ntm_tensor_multiplication.py
touch library/algebra/tensor/ntm_tensor_product.py
touch library/algebra/tensor/ntm_tensor_softmax.py
touch library/algebra/tensor/ntm_tensor_summation.py
touch library/algebra/tensor/ntm_tensor_transpose.py
touch library/algebra/test_matrix_algebra.py
touch library/algebra/test_scalar_algebra.py
touch library/algebra/test_tensor_algebra.py
touch library/algebra/test_vector_algebra.py
touch library/algebra/vector/ntm_dot_product.py
touch library/algebra/vector/ntm_vector_convolution.py
touch library/algebra/vector/ntm_vector_cosine_similarity.py
touch library/algebra/vector/ntm_vector_differentiation.py
touch library/algebra/vector/ntm_vector_integration.py
touch library/algebra/vector/ntm_vector_module.py
touch library/algebra/vector/ntm_vector_multiplication.py
touch library/algebra/vector/ntm_vector_softmax.py
touch library/algebra/vector/ntm_vector_summation.py
touch library/arithmetic/matrix/adder/ntm_matrix_adder.py
touch library/arithmetic/matrix/divider/ntm_matrix_divider.py
touch library/arithmetic/matrix/multiplier/ntm_matrix_multiplier.py
touch library/arithmetic/matrix/subtractor/ntm_matrix_subtractor.py
touch library/arithmetic/scalar/adder/ntm_scalar_adder.py
touch library/arithmetic/scalar/divider/ntm_scalar_divider.py
touch library/arithmetic/scalar/multiplier/ntm_scalar_multiplier.py
touch library/arithmetic/scalar/subtractor/ntm_scalar_subtractor.py
touch library/arithmetic/tensor/adder/ntm_tensor_adder.py
touch library/arithmetic/tensor/divider/ntm_tensor_divider.py
touch library/arithmetic/tensor/multiplier/ntm_tensor_multiplier.py
touch library/arithmetic/tensor/subtractor/ntm_tensor_subtractor.py
touch library/arithmetic/test_matrix_arithmetic.py
touch library/arithmetic/test_scalar_arithmetic.py
touch library/arithmetic/test_tensor_arithmetic.py
touch library/arithmetic/test_vector_arithmetic.py
touch library/arithmetic/vector/adder/ntm_vector_adder.py
touch library/arithmetic/vector/divider/ntm_vector_divider.py
touch library/arithmetic/vector/multiplier/ntm_vector_multiplier.py
touch library/arithmetic/vector/subtractor/ntm_vector_subtractor.py
touch library/math/matrix/ntm_matrix_deviation_function.py
touch library/math/matrix/ntm_matrix_logistic_function.py
touch library/math/matrix/ntm_matrix_mean_function.py
touch library/math/matrix/ntm_matrix_oneplus_function.py
touch library/math/scalar/ntm_scalar_deviation_function.py
touch library/math/scalar/ntm_scalar_logistic_function.py
touch library/math/scalar/ntm_scalar_mean_function.py
touch library/math/scalar/ntm_scalar_oneplus_function.py
touch library/math/test_matrix_math.py
touch library/math/test_scalar_math.py
touch library/math/test_vector_math.py
touch library/math/vector/ntm_vector_deviation_function.py
touch library/math/vector/ntm_vector_logistic_function.py
touch library/math/vector/ntm_vector_mean_function.py
touch library/math/vector/ntm_vector_oneplus_function.py
touch library/nn/ann/components/ntm_masked_multi_head_attention.py
touch library/nn/ann/components/ntm_masked_scaled_dot_product_attention.py
touch library/nn/ann/components/ntm_multi_head_attention.py
touch library/nn/ann/components/ntm_scaled_dot_product_attention.py
touch library/nn/ann/controller/fnn/ntm_fnn.py
touch library/nn/ann/controller/lstm/ntm_lstm.py
touch library/nn/ann/functions/ntm_layer_norm.py
touch library/nn/ann/functions/ntm_positional_encoding.py
touch library/nn/ann/inputs/ntm_inputs_vector.py
touch library/nn/ann/inputs/ntm_keys_vector.py
touch library/nn/ann/inputs/ntm_queries_vector.py
touch library/nn/ann/inputs/ntm_values_vector.py
touch library/nn/ann/test_ann_components.py
touch library/nn/ann/test_ann_controller.py
touch library/nn/ann/test_ann_functions.py
touch library/nn/ann/test_ann_inputs.py
touch library/nn/ann/test_ann_top.py
touch library/nn/ann/top/ntm_controller.py
touch library/nn/ann/top/ntm_decoder.py
touch library/nn/ann/top/ntm_encoder.py
touch library/nn/dnc/memory/dnc_addressing.py
touch library/nn/dnc/memory/dnc_allocation_weighting.py
touch library/nn/dnc/memory/dnc_backward_weighting.py
touch library/nn/dnc/memory/dnc_forward_weighting.py
touch library/nn/dnc/memory/dnc_matrix_content_based_addressing.py
touch library/nn/dnc/memory/dnc_memory_matrix.py
touch library/nn/dnc/memory/dnc_memory_retention_vector.py
touch library/nn/dnc/memory/dnc_precedence_weighting.py
touch library/nn/dnc/memory/dnc_sort_vector.py
touch library/nn/dnc/memory/dnc_temporal_link_matrix.py
touch library/nn/dnc/memory/dnc_usage_vector.py
touch library/nn/dnc/memory/dnc_vector_content_based_addressing.py
touch library/nn/dnc/read_heads/dnc_read_content_weighting.py
touch library/nn/dnc/read_heads/dnc_read_vectors.py
touch library/nn/dnc/read_heads/dnc_read_weighting.py
touch library/nn/dnc/test_dnc_memory.py
touch library/nn/dnc/test_dnc_read_heads.py
touch library/nn/dnc/test_dnc_top.py
touch library/nn/dnc/test_dnc_trained.py
touch library/nn/dnc/test_dnc_write_heads.py
touch library/nn/dnc/top/dnc_interface_matrix.py
touch library/nn/dnc/top/dnc_interface_top.py
touch library/nn/dnc/top/dnc_interface_vector.py
touch library/nn/dnc/top/dnc_output_vector.py
touch library/nn/dnc/top/dnc_top.py
touch library/nn/dnc/trained/dnc_trained_top.py
touch library/nn/dnc/write_heads/dnc_write_content_weighting.py
touch library/nn/dnc/write_heads/dnc_write_weighting.py
touch library/nn/fnn/convolutional/ntm_controller.py
touch library/nn/fnn/standard/ntm_controller.py
touch library/nn/fnn/test_convolutional_fnn_controller.py
touch library/nn/fnn/test_standard_fnn_controller.py
touch library/nn/lstm/convolutional/ntm_activation_gate_vector.py
touch library/nn/lstm/convolutional/ntm_controller.py
touch library/nn/lstm/convolutional/ntm_forget_gate_vector.py
touch library/nn/lstm/convolutional/ntm_hidden_gate_vector.py
touch library/nn/lstm/convolutional/ntm_input_gate_vector.py
touch library/nn/lstm/convolutional/ntm_output_gate_vector.py
touch library/nn/lstm/convolutional/ntm_state_gate_vector.py
touch library/nn/lstm/standard/ntm_activation_gate_vector.py
touch library/nn/lstm/standard/ntm_controller.py
touch library/nn/lstm/standard/ntm_forget_gate_vector.py
touch library/nn/lstm/standard/ntm_hidden_gate_vector.py
touch library/nn/lstm/standard/ntm_input_gate_vector.py
touch library/nn/lstm/standard/ntm_output_gate_vector.py
touch library/nn/lstm/standard/ntm_state_gate_vector.py
touch library/nn/lstm/test_convolutional_lstm_controller.py
touch library/nn/lstm/test_standard_lstm_controller.py
touch library/nn/ntm/memory/ntm_addressing.py
touch library/nn/ntm/memory/ntm_matrix_content_based_addressing.py
touch library/nn/ntm/memory/ntm_vector_content_based_addressing.py
touch library/nn/ntm/read_heads/ntm_reading.py
touch library/nn/ntm/test_ntm_memory.py
touch library/nn/ntm/test_ntm_read_heads.py
touch library/nn/ntm/test_ntm_top.py
touch library/nn/ntm/test_ntm_trained.py
touch library/nn/ntm/test_ntm_write_heads.py
touch library/nn/ntm/top/ntm_interface_matrix.py
touch library/nn/ntm/top/ntm_interface_top.py
touch library/nn/ntm/top/ntm_interface_vector.py
touch library/nn/ntm/top/ntm_output_vector.py
touch library/nn/ntm/top/ntm_top.py
touch library/nn/ntm/trained/ntm_trained_top.py
touch library/nn/ntm/write_heads/ntm_erasing.py
touch library/nn/ntm/write_heads/ntm_writing.py
touch library/state/feedback/ntm_state_matrix_feedforward.py
touch library/state/feedback/ntm_state_matrix_input.py
touch library/state/feedback/ntm_state_matrix_output.py
touch library/state/feedback/ntm_state_matrix_state.py
touch library/state/outputs/ntm_state_vector_output.py
touch library/state/outputs/ntm_state_vector_state.py
touch library/state/test_state_feedback.py
touch library/state/test_state_outputs.py
touch library/state/test_state_top.py
touch library/state/top/ntm_state_top.py
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.py
touch library/trainer/differentiation/ntm_vector_controller_differentiation.py
touch library/trainer/fnn/ntm_fnn_b_trainer.py
touch library/trainer/fnn/ntm_fnn_d_trainer.py
touch library/trainer/fnn/ntm_fnn_k_trainer.py
touch library/trainer/fnn/ntm_fnn_trainer.py
touch library/trainer/fnn/ntm_fnn_u_trainer.py
touch library/trainer/fnn/ntm_fnn_v_trainer.py
touch library/trainer/fnn/ntm_fnn_w_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_b_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_d_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_k_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_u_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_v_trainer.py
touch library/trainer/lstm/activation/ntm_lstm_activation_w_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_b_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_d_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_k_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_u_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_v_trainer.py
touch library/trainer/lstm/forget/ntm_lstm_forget_w_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_b_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_d_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_k_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_u_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_v_trainer.py
touch library/trainer/lstm/input/ntm_lstm_input_w_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_b_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_d_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_k_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_u_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_v_trainer.py
touch library/trainer/lstm/output/ntm_lstm_output_w_trainer.py
touch library/trainer/test_trainer_differentiation.py
touch library/trainer/test_trainer_fnn.py
touch library/trainer/test_trainer_lstm.py
