touch library/algebra/matrix/accelerator_matrix_convolution.py
touch library/algebra/matrix/accelerator_matrix_differentiation.py
touch library/algebra/matrix/accelerator_matrix_integration.py
touch library/algebra/matrix/accelerator_matrix_inverse.py
touch library/algebra/matrix/accelerator_matrix_multiplication.py
touch library/algebra/matrix/accelerator_matrix_product.py
touch library/algebra/matrix/accelerator_matrix_softmax.py
touch library/algebra/matrix/accelerator_matrix_summation.py
touch library/algebra/matrix/accelerator_matrix_transpose.py
touch library/algebra/matrix/accelerator_matrix_vector_convolution.py
touch library/algebra/matrix/accelerator_matrix_vector_product.py
touch library/algebra/matrix/accelerator_transpose_vector_product.py
touch library/algebra/scalar/accelerator_scalar_multiplication.py
touch library/algebra/scalar/accelerator_scalar_summation.py
touch library/algebra/tensor/accelerator_tensor_convolution.py
touch library/algebra/tensor/accelerator_tensor_differentiation.py
touch library/algebra/tensor/accelerator_tensor_integration.py
touch library/algebra/tensor/accelerator_tensor_inverse.py
touch library/algebra/tensor/accelerator_tensor_matrix_convolution.py
touch library/algebra/tensor/accelerator_tensor_matrix_product.py
touch library/algebra/tensor/accelerator_tensor_multiplication.py
touch library/algebra/tensor/accelerator_tensor_product.py
touch library/algebra/tensor/accelerator_tensor_softmax.py
touch library/algebra/tensor/accelerator_tensor_summation.py
touch library/algebra/tensor/accelerator_tensor_transpose.py
touch library/algebra/test_matrix_algebra.py
touch library/algebra/test_scalar_algebra.py
touch library/algebra/test_tensor_algebra.py
touch library/algebra/test_vector_algebra.py
touch library/algebra/vector/accelerator_dot_product.py
touch library/algebra/vector/accelerator_vector_convolution.py
touch library/algebra/vector/accelerator_vector_cosine_similarity.py
touch library/algebra/vector/accelerator_vector_differentiation.py
touch library/algebra/vector/accelerator_vector_integration.py
touch library/algebra/vector/accelerator_vector_module.py
touch library/algebra/vector/accelerator_vector_multiplication.py
touch library/algebra/vector/accelerator_vector_softmax.py
touch library/algebra/vector/accelerator_vector_summation.py
touch library/arithmetic/matrix/adder/accelerator_matrix_adder.py
touch library/arithmetic/matrix/divider/accelerator_matrix_divider.py
touch library/arithmetic/matrix/multiplier/accelerator_matrix_multiplier.py
touch library/arithmetic/matrix/subtractor/accelerator_matrix_subtractor.py
touch library/arithmetic/scalar/adder/accelerator_scalar_adder.py
touch library/arithmetic/scalar/divider/accelerator_scalar_divider.py
touch library/arithmetic/scalar/multiplier/accelerator_scalar_multiplier.py
touch library/arithmetic/scalar/subtractor/accelerator_scalar_subtractor.py
touch library/arithmetic/tensor/adder/accelerator_tensor_adder.py
touch library/arithmetic/tensor/divider/accelerator_tensor_divider.py
touch library/arithmetic/tensor/multiplier/accelerator_tensor_multiplier.py
touch library/arithmetic/tensor/subtractor/accelerator_tensor_subtractor.py
touch library/arithmetic/test_matrix_arithmetic.py
touch library/arithmetic/test_scalar_arithmetic.py
touch library/arithmetic/test_tensor_arithmetic.py
touch library/arithmetic/test_vector_arithmetic.py
touch library/arithmetic/vector/adder/accelerator_vector_adder.py
touch library/arithmetic/vector/divider/accelerator_vector_divider.py
touch library/arithmetic/vector/multiplier/accelerator_vector_multiplier.py
touch library/arithmetic/vector/subtractor/accelerator_vector_subtractor.py
touch library/math/matrix/accelerator_matrix_deviation_function.py
touch library/math/matrix/accelerator_matrix_logistic_function.py
touch library/math/matrix/accelerator_matrix_mean_function.py
touch library/math/matrix/accelerator_matrix_oneplus_function.py
touch library/math/scalar/accelerator_scalar_deviation_function.py
touch library/math/scalar/accelerator_scalar_logistic_function.py
touch library/math/scalar/accelerator_scalar_mean_function.py
touch library/math/scalar/accelerator_scalar_oneplus_function.py
touch library/math/test_matrix_math.py
touch library/math/test_scalar_math.py
touch library/math/test_vector_math.py
touch library/math/vector/accelerator_vector_deviation_function.py
touch library/math/vector/accelerator_vector_logistic_function.py
touch library/math/vector/accelerator_vector_mean_function.py
touch library/math/vector/accelerator_vector_oneplus_function.py
touch library/nn/fnn/convolutional/accelerator_controller.py
touch library/nn/fnn/standard/accelerator_controller.py
touch library/nn/fnn/test_convolutional_fnn_controller.py
touch library/nn/fnn/test_standard_fnn_controller.py
touch library/nn/lstm/convolutional/accelerator_activation_gate_vector.py
touch library/nn/lstm/convolutional/accelerator_controller.py
touch library/nn/lstm/convolutional/accelerator_forget_gate_vector.py
touch library/nn/lstm/convolutional/accelerator_hidden_gate_vector.py
touch library/nn/lstm/convolutional/accelerator_input_gate_vector.py
touch library/nn/lstm/convolutional/accelerator_output_gate_vector.py
touch library/nn/lstm/convolutional/accelerator_state_gate_vector.py
touch library/nn/lstm/standard/accelerator_activation_gate_vector.py
touch library/nn/lstm/standard/accelerator_controller.py
touch library/nn/lstm/standard/accelerator_forget_gate_vector.py
touch library/nn/lstm/standard/accelerator_hidden_gate_vector.py
touch library/nn/lstm/standard/accelerator_input_gate_vector.py
touch library/nn/lstm/standard/accelerator_output_gate_vector.py
touch library/nn/lstm/standard/accelerator_state_gate_vector.py
touch library/nn/lstm/test_convolutional_lstm_controller.py
touch library/nn/lstm/test_standard_lstm_controller.py
touch library/nn/ntm/memory/accelerator_addressing.py
touch library/nn/ntm/memory/accelerator_matrix_content_based_addressing.py
touch library/nn/ntm/memory/accelerator_vector_content_based_addressing.py
touch library/nn/ntm/read_heads/accelerator_reading.py
touch library/nn/ntm/test_ntm_memory.py
touch library/nn/ntm/test_ntm_read_heads.py
touch library/nn/ntm/test_ntm_top.py
touch library/nn/ntm/test_ntm_trained.py
touch library/nn/ntm/test_ntm_write_heads.py
touch library/nn/ntm/top/accelerator_interface_matrix.py
touch library/nn/ntm/top/accelerator_interface_top.py
touch library/nn/ntm/top/accelerator_interface_vector.py
touch library/nn/ntm/top/accelerator_output_vector.py
touch library/nn/ntm/top/accelerator_top.py
touch library/nn/ntm/trained/accelerator_trained_top.py
touch library/nn/ntm/write_heads/accelerator_erasing.py
touch library/nn/ntm/write_heads/accelerator_writing.py
touch library/trainer/differentiation/accelerator_matrix_controller_differentiation.py
touch library/trainer/differentiation/accelerator_vector_controller_differentiation.py
touch library/trainer/fnn/accelerator_fnn_b_trainer.py
touch library/trainer/fnn/accelerator_fnn_d_trainer.py
touch library/trainer/fnn/accelerator_fnn_k_trainer.py
touch library/trainer/fnn/accelerator_fnn_trainer.py
touch library/trainer/fnn/accelerator_fnn_u_trainer.py
touch library/trainer/fnn/accelerator_fnn_v_trainer.py
touch library/trainer/fnn/accelerator_fnn_w_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_b_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_d_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_k_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_u_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_v_trainer.py
touch library/trainer/lstm/activation/accelerator_lstm_activation_w_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_b_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_d_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_k_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_u_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_v_trainer.py
touch library/trainer/lstm/forget/accelerator_lstm_forget_w_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_b_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_d_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_k_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_u_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_v_trainer.py
touch library/trainer/lstm/input/accelerator_lstm_input_w_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_b_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_d_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_k_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_u_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_v_trainer.py
touch library/trainer/lstm/output/accelerator_lstm_output_w_trainer.py
touch library/trainer/test_trainer_differentiation.py
touch library/trainer/test_trainer_fnn.py
touch library/trainer/test_trainer_lstm.py
