touch library/arithmetic/matrix/adder/ntm_matrix_adder.py
touch library/arithmetic/matrix/divider/ntm_matrix_divider.py
touch library/arithmetic/matrix/multiplier/ntm_matrix_multiplier.py
touch library/arithmetic/matrix/ntm_matrix_arithmetic.py
touch library/arithmetic/matrix/subtractor/ntm_matrix_subtractor.py
touch library/arithmetic/scalar/adder/ntm_scalar_adder.py
touch library/arithmetic/scalar/divider/ntm_scalar_divider.py
touch library/arithmetic/scalar/multiplier/ntm_scalar_multiplier.py
touch library/arithmetic/scalar/ntm_scalar_arithmetic.py
touch library/arithmetic/scalar/subtractor/ntm_scalar_subtractor.py
touch library/arithmetic/tensor/adder/ntm_tensor_adder.py
touch library/arithmetic/tensor/divider/ntm_tensor_divider.py
touch library/arithmetic/tensor/multiplier/ntm_tensor_multiplier.py
touch library/arithmetic/tensor/ntm_tensor_arithmetic.py
touch library/arithmetic/tensor/subtractor/ntm_tensor_subtractor.py
touch library/arithmetic/test_matrix_arithmetic.py
touch library/arithmetic/test_scalar_arithmetic.py
touch library/arithmetic/test_tensor_arithmetic.py
touch library/arithmetic/test_vector_arithmetic.py
touch library/arithmetic/vector/adder/ntm_vector_adder.py
touch library/arithmetic/vector/divider/ntm_vector_divider.py
touch library/arithmetic/vector/multiplier/ntm_vector_multiplier.py
touch library/arithmetic/vector/ntm_vector_arithmetic.py
touch library/arithmetic/vector/subtractor/ntm_vector_subtractor.py
touch library/controller/FNN/convolutional/ntm_controller.py
touch library/controller/FNN/standard/ntm_controller.py
touch library/controller/FNN/test_convolutional_fnn_controller.py
touch library/controller/FNN/test_standard_fnn_controller.py
touch library/controller/LSTM/convolutional/ntm_activation_gate_vector.py
touch library/controller/LSTM/convolutional/ntm_controller.py
touch library/controller/LSTM/convolutional/ntm_forget_gate_vector.py
touch library/controller/LSTM/convolutional/ntm_hidden_gate_vector.py
touch library/controller/LSTM/convolutional/ntm_input_gate_vector.py
touch library/controller/LSTM/convolutional/ntm_output_gate_vector.py
touch library/controller/LSTM/convolutional/ntm_state_gate_vector.py
touch library/controller/LSTM/standard/ntm_activation_gate_vector.py
touch library/controller/LSTM/standard/ntm_controller.py
touch library/controller/LSTM/standard/ntm_forget_gate_vector.py
touch library/controller/LSTM/standard/ntm_hidden_gate_vector.py
touch library/controller/LSTM/standard/ntm_input_gate_vector.py
touch library/controller/LSTM/standard/ntm_output_gate_vector.py
touch library/controller/LSTM/standard/ntm_state_gate_vector.py
touch library/controller/LSTM/test_convolutional_lstm_controller.py
touch library/controller/LSTM/test_standard_lstm_controller.py
touch library/math/algebra/matrix/ntm_matrix_convolution.py
touch library/math/algebra/matrix/ntm_matrix_inverse.py
touch library/math/algebra/matrix/ntm_matrix_math_algebra.py
touch library/math/algebra/matrix/ntm_matrix_multiplication.py
touch library/math/algebra/matrix/ntm_matrix_product.py
touch library/math/algebra/matrix/ntm_matrix_summation.py
touch library/math/algebra/matrix/ntm_matrix_transpose.py
touch library/math/algebra/matrix/ntm_matrix_vector_convolution.py
touch library/math/algebra/matrix/ntm_matrix_vector_product.py
touch library/math/algebra/matrix/ntm_transpose_vector_product.py
touch library/math/algebra/scalar/ntm_scalar_math_algebra.py
touch library/math/algebra/scalar/ntm_scalar_multiplication.py
touch library/math/algebra/scalar/ntm_scalar_summation.py
touch library/math/algebra/tensor/ntm_tensor_convolution.py
touch library/math/algebra/tensor/ntm_tensor_inverse.py
touch library/math/algebra/tensor/ntm_tensor_math_algebra.py
touch library/math/algebra/tensor/ntm_tensor_matrix_convolution.py
touch library/math/algebra/tensor/ntm_tensor_matrix_product.py
touch library/math/algebra/tensor/ntm_tensor_multiplication.py
touch library/math/algebra/tensor/ntm_tensor_product.py
touch library/math/algebra/tensor/ntm_tensor_summation.py
touch library/math/algebra/tensor/ntm_tensor_transpose.py
touch library/math/algebra/test_matrix_algebra.py
touch library/math/algebra/test_scalar_algebra.py
touch library/math/algebra/test_tensor_algebra.py
touch library/math/algebra/test_vector_algebra.py
touch library/math/algebra/vector/ntm_dot_product.py
touch library/math/algebra/vector/ntm_vector_convolution.py
touch library/math/algebra/vector/ntm_vector_cosine_similarity.py
touch library/math/algebra/vector/ntm_vector_math_algebra.py
touch library/math/algebra/vector/ntm_vector_module.py
touch library/math/algebra/vector/ntm_vector_multiplication.py
touch library/math/algebra/vector/ntm_vector_summation.py
touch library/math/calculus/matrix/ntm_matrix_differentiation.py
touch library/math/calculus/matrix/ntm_matrix_integration.py
touch library/math/calculus/matrix/ntm_matrix_math_calculus.py
touch library/math/calculus/matrix/ntm_matrix_softmax.py
touch library/math/calculus/tensor/ntm_tensor_differentiation.py
touch library/math/calculus/tensor/ntm_tensor_integration.py
touch library/math/calculus/tensor/ntm_tensor_math_calculus.py
touch library/math/calculus/tensor/ntm_tensor_softmax.py
touch library/math/calculus/test_matrix_calculus.py
touch library/math/calculus/test_tensor_calculus.py
touch library/math/calculus/test_vector_calculus.py
touch library/math/calculus/vector/ntm_vector_differentiation.py
touch library/math/calculus/vector/ntm_vector_integration.py
touch library/math/calculus/vector/ntm_vector_math_calculus.py
touch library/math/calculus/vector/ntm_vector_softmax.py
touch library/math/function/matrix/ntm_matrix_logistic_function.py
touch library/math/function/matrix/ntm_matrix_math_function.py
touch library/math/function/matrix/ntm_matrix_oneplus_function.py
touch library/math/function/scalar/ntm_scalar_logistic_function.py
touch library/math/function/scalar/ntm_scalar_math_function.py
touch library/math/function/scalar/ntm_scalar_oneplus_function.py
touch library/math/function/test_matrix_function.py
touch library/math/function/test_scalar_function.py
touch library/math/function/test_vector_function.py
touch library/math/function/vector/ntm_vector_logistic_function.py
touch library/math/function/vector/ntm_vector_math_function.py
touch library/math/function/vector/ntm_vector_oneplus_function.py
touch library/math/statitics/matrix/ntm_matrix_deviation.py
touch library/math/statitics/matrix/ntm_matrix_math_statitics.py
touch library/math/statitics/matrix/ntm_matrix_mean.py
touch library/math/statitics/scalar/ntm_scalar_deviation.py
touch library/math/statitics/scalar/ntm_scalar_math_statitics.py
touch library/math/statitics/scalar/ntm_scalar_mean.py
touch library/math/statitics/test_matrix_statitics.py
touch library/math/statitics/test_scalar_statitics.py
touch library/math/statitics/test_vector_statitics.py
touch library/math/statitics/vector/ntm_vector_deviation.py
touch library/math/statitics/vector/ntm_vector_math_statitics.py
touch library/math/statitics/vector/ntm_vector_mean.py
touch library/ntm/memory/ntm_addressing.py
touch library/ntm/memory/ntm_matrix_content_based_addressing.py
touch library/ntm/memory/ntm_vector_content_based_addressing.py
touch library/ntm/read_heads/ntm_reading.py
touch library/ntm/test_ntm_memory.py
touch library/ntm/test_ntm_read_heads.py
touch library/ntm/test_ntm_top.py
touch library/ntm/test_ntm_trained.py
touch library/ntm/test_ntm_write_heads.py
touch library/ntm/top/ntm_interface_matrix.py
touch library/ntm/top/ntm_interface_top.py
touch library/ntm/top/ntm_interface_vector.py
touch library/ntm/top/ntm_output_vector.py
touch library/ntm/top/ntm_top.py
touch library/ntm/trained/ntm_trained_top.py
touch library/ntm/write_heads/ntm_erasing.py
touch library/ntm/write_heads/ntm_writing.py
touch library/state/feedback/ntm_state_matrix_feedforward.py
touch library/state/feedback/ntm_state_matrix_input.py
touch library/state/feedback/ntm_state_matrix_output.py
touch library/state/feedback/ntm_state_matrix_state.py
touch library/state/outputs/ntm_state_vector_output.py
touch library/state/outputs/ntm_state_vector_state.py
touch library/state/test_state_feedback.py
touch library/state/test_state_outputs.py
touch library/state/test_state_top.py
touch library/state/top/ntm_state_top.py
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.py
touch library/trainer/differentiation/ntm_vector_controller_differentiation.py
touch library/trainer/FNN/ntm_fnn_b_trainer.py
touch library/trainer/FNN/ntm_fnn_d_trainer.py
touch library/trainer/FNN/ntm_fnn_k_trainer.py
touch library/trainer/FNN/ntm_fnn_trainer.py
touch library/trainer/FNN/ntm_fnn_u_trainer.py
touch library/trainer/FNN/ntm_fnn_v_trainer.py
touch library/trainer/FNN/ntm_fnn_w_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.py
touch library/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.py
touch library/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_b_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_d_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_k_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_u_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_v_trainer.py
touch library/trainer/LSTM/input/ntm_lstm_input_w_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_b_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_d_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_k_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_u_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_v_trainer.py
touch library/trainer/LSTM/output/ntm_lstm_output_w_trainer.py
touch library/trainer/test_trainer_differentiation.py
touch library/trainer/test_trainer_fnn.py
touch library/trainer/test_trainer_lstm.py
touch library/transformer/components/ntm_masked_multi_head_attention.py
touch library/transformer/components/ntm_masked_scaled_dot_product_attention.py
touch library/transformer/components/ntm_multi_head_attention.py
touch library/transformer/components/ntm_scaled_dot_product_attention.py
touch library/transformer/controller/fnn/ntm_fnn.py
touch library/transformer/controller/lstm/ntm_lstm.py
touch library/transformer/functions/ntm_layer_norm.py
touch library/transformer/functions/ntm_positional_encoding.py
touch library/transformer/inputs/ntm_inputs_vector.py
touch library/transformer/inputs/ntm_keys_vector.py
touch library/transformer/inputs/ntm_queries_vector.py
touch library/transformer/inputs/ntm_values_vector.py
touch library/transformer/test_transformer_components.py
touch library/transformer/test_transformer_controller.py
touch library/transformer/test_transformer_functions.py
touch library/transformer/test_transformer_inputs.py
touch library/transformer/test_transformer_top.py
touch library/transformer/top/ntm_controller.py
touch library/transformer/top/ntm_decoder.py
touch library/transformer/top/ntm_encoder.py
