touch code/classes/philosophers/ntm_philosophers.tb.m
touch code/classes/soldiers/ntm_soldiers.tb.m
touch code/classes/workers/ntm_workers.tb.m
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip.tb.m
touch code/computing/advanced_computer_architecture/processing_unit/mimd.tb.m
touch code/computing/advanced_computer_architecture/processing_unit/misd.tb.m
touch code/computing/advanced_computer_architecture/processing_unit/simd.tb.m
touch code/computing/advanced_computer_architecture/processing_unit/sisd.tb.m
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip.tb.m
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip.tb.m
touch code/computing/computer_architecture/harvard_architecture/alu.tb.m
touch code/computing/computer_architecture/harvard_architecture/control_unit.tb.m
touch code/computing/computer_architecture/harvard_architecture/io_unit.tb.m
touch code/computing/computer_architecture/harvard_architecture/memory_unit.tb.m
touch code/computing/computer_architecture/von_neumann_architecture/alu.tb.m
touch code/computing/computer_architecture/von_neumann_architecture/control_unit.tb.m
touch code/computing/computer_architecture/von_neumann_architecture/io_unit.tb.m
touch code/computing/computer_architecture/von_neumann_architecture/memory_unit.tb.m
touch code/computing/information/bit/bit.tb.m
touch code/computing/information/combinational_logic/arithmetic_circuits.tb.m
touch code/computing/information/combinational_logic/logic_circuits.tb.m
touch code/computing/information/finite_state_machine/finite_state_machine.tb.m
touch code/computing/information/logic_gate/and_gate.tb.m
touch code/computing/information/logic_gate/nand_gate.tb.m
touch code/computing/information/logic_gate/nor_gate.tb.m
touch code/computing/information/logic_gate/not_gate.tb.m
touch code/computing/information/logic_gate/or_gate.tb.m
touch code/computing/information/logic_gate/xnor_gate.tb.m
touch code/computing/information/logic_gate/xor_gate.tb.m
touch code/computing/information/logic_gate/yes_gate.tb.m
touch code/computing/information/pushdown_automaton/pushdown_automaton.tb.m
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network.tb.m
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network.tb.m
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network.tb.m
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer.tb.m
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer.tb.m
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer.tb.m
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine.tb.m
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine.tb.m
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine.tb.m
touch code/pkg/classes/ntm_philosophers_pkg.tb.m
touch code/pkg/classes/ntm_soldiers_pkg.tb.m
touch code/pkg/classes/ntm_workers_pkg.tb.m
touch code/pkg/ieee/math_complex-body.tb.m
touch code/pkg/ieee/math_complex.tb.m
touch code/pkg/ieee/math_real-body.tb.m
touch code/pkg/ieee/math_real.tb.m
touch code/pkg/computing/state_pkg.tb.m
