touch library/algebra/matrix/ntm_matrix_algebra.java
touch library/algebra/scalar/ntm_scalar_algebra.java
touch library/algebra/tensor/ntm_tensor_algebra.java
touch library/algebra/vector/ntm_vector_algebra.java
touch library/arithmetic/matrix/ntm_matrix_arithmetic.java
touch library/arithmetic/scalar/ntm_scalar_arithmetic.java
touch library/arithmetic/tensor/ntm_tensor_arithmetic.java
touch library/arithmetic/vector/ntm_vector_arithmetic.java
touch library/math/matrix/ntm_matrix_math.java
touch library/math/scalar/ntm_scalar_math.java
touch library/math/vector/ntm_vector_math.java
touch library/nn/fnn/convolutional/ntm_controller.java
touch library/nn/fnn/standard/ntm_controller.java
touch library/nn/lstm/convolutional/ntm_activation_gate_vector.java
touch library/nn/lstm/convolutional/ntm_controller.java
touch library/nn/lstm/convolutional/ntm_forget_gate_vector.java
touch library/nn/lstm/convolutional/ntm_hidden_gate_vector.java
touch library/nn/lstm/convolutional/ntm_input_gate_vector.java
touch library/nn/lstm/convolutional/ntm_output_gate_vector.java
touch library/nn/lstm/convolutional/ntm_state_gate_vector.java
touch library/nn/lstm/standard/ntm_activation_gate_vector.java
touch library/nn/lstm/standard/ntm_controller.java
touch library/nn/lstm/standard/ntm_forget_gate_vector.java
touch library/nn/lstm/standard/ntm_hidden_gate_vector.java
touch library/nn/lstm/standard/ntm_input_gate_vector.java
touch library/nn/lstm/standard/ntm_output_gate_vector.java
touch library/nn/lstm/standard/ntm_state_gate_vector.java
touch library/nn/ntm/memory/ntm_addressing.java
touch library/nn/ntm/memory/ntm_matrix_content_based_addressing.java
touch library/nn/ntm/memory/ntm_vector_content_based_addressing.java
touch library/nn/ntm/read_heads/ntm_reading.java
touch library/nn/ntm/top/ntm_interface_matrix.java
touch library/nn/ntm/top/ntm_interface_top.java
touch library/nn/ntm/top/ntm_interface_vector.java
touch library/nn/ntm/top/ntm_output_vector.java
touch library/nn/ntm/top/ntm_top.java
touch library/nn/ntm/trained/ntm_trained_top.java
touch library/nn/ntm/write_heads/ntm_erasing.java
touch library/nn/ntm/write_heads/ntm_writing.java
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.java
touch library/trainer/differentiation/ntm_vector_controller_differentiation.java
touch library/trainer/fnn/ntm_fnn_b_trainer.java
touch library/trainer/fnn/ntm_fnn_d_trainer.java
touch library/trainer/fnn/ntm_fnn_k_trainer.java
touch library/trainer/fnn/ntm_fnn_trainer.java
touch library/trainer/fnn/ntm_fnn_u_trainer.java
touch library/trainer/fnn/ntm_fnn_v_trainer.java
touch library/trainer/fnn/ntm_fnn_w_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_b_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_d_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_k_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_u_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_v_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_w_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_b_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_d_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_k_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_u_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_v_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_w_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_b_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_d_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_k_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_u_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_v_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_w_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_b_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_d_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_k_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_u_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_v_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_w_trainer.java
