touch library/algebra/matrix/ntm_matrix_algebra.adb
touch library/algebra/scalar/ntm_scalar_algebra.adb
touch library/algebra/tensor/ntm_tensor_algebra.adb
touch library/algebra/vector/ntm_vector_algebra.adb
touch library/arithmetic/matrix/ntm_matrix_arithmetic.adb
touch library/arithmetic/scalar/ntm_scalar_arithmetic.adb
touch library/arithmetic/tensor/ntm_tensor_arithmetic.adb
touch library/arithmetic/vector/ntm_vector_arithmetic.adb
touch library/math/matrix/ntm_matrix_math.adb
touch library/math/scalar/ntm_scalar_math.adb
touch library/math/vector/ntm_vector_math.adb
touch library/nn/ann/components/ntm_masked_multi_head_attention.adb
touch library/nn/ann/components/ntm_masked_scaled_dot_product_attention.adb
touch library/nn/ann/components/ntm_multi_head_attention.adb
touch library/nn/ann/components/ntm_scaled_dot_product_attention.adb
touch library/nn/ann/controller/fnn/ntm_fnn.adb
touch library/nn/ann/controller/lstm/ntm_lstm.adb
touch library/nn/ann/functions/ntm_layer_norm.adb
touch library/nn/ann/functions/ntm_positional_encoding.adb
touch library/nn/ann/inputs/ntm_inputs_vector.adb
touch library/nn/ann/inputs/ntm_keys_vector.adb
touch library/nn/ann/inputs/ntm_queries_vector.adb
touch library/nn/ann/inputs/ntm_values_vector.adb
touch library/nn/ann/top/ntm_controller.adb
touch library/nn/ann/top/ntm_decoder.adb
touch library/nn/ann/top/ntm_encoder.adb
touch library/nn/dnc/memory/dnc_addressing.adb
touch library/nn/dnc/memory/dnc_allocation_weighting.adb
touch library/nn/dnc/memory/dnc_backward_weighting.adb
touch library/nn/dnc/memory/dnc_forward_weighting.adb
touch library/nn/dnc/memory/dnc_matrix_content_based_addressing.adb
touch library/nn/dnc/memory/dnc_memory_matrix.adb
touch library/nn/dnc/memory/dnc_memory_retention_vector.adb
touch library/nn/dnc/memory/dnc_precedence_weighting.adb
touch library/nn/dnc/memory/dnc_sort_vector.adb
touch library/nn/dnc/memory/dnc_temporal_link_matrix.adb
touch library/nn/dnc/memory/dnc_usage_vector.adb
touch library/nn/dnc/memory/dnc_vector_content_based_addressing.adb
touch library/nn/dnc/read_heads/dnc_read_content_weighting.adb
touch library/nn/dnc/read_heads/dnc_read_vectors.adb
touch library/nn/dnc/read_heads/dnc_read_weighting.adb
touch library/nn/dnc/top/dnc_interface_matrix.adb
touch library/nn/dnc/top/dnc_interface_top.adb
touch library/nn/dnc/top/dnc_interface_vector.adb
touch library/nn/dnc/top/dnc_output_vector.adb
touch library/nn/dnc/top/dnc_top.adb
touch library/nn/dnc/trained/dnc_trained_top.adb
touch library/nn/dnc/write_heads/dnc_write_content_weighting.adb
touch library/nn/dnc/write_heads/dnc_write_weighting.adb
touch library/nn/fnn/convolutional/ntm_controller.adb
touch library/nn/fnn/standard/ntm_controller.adb
touch library/nn/lstm/convolutional/ntm_activation_gate_vector.adb
touch library/nn/lstm/convolutional/ntm_controller.adb
touch library/nn/lstm/convolutional/ntm_forget_gate_vector.adb
touch library/nn/lstm/convolutional/ntm_hidden_gate_vector.adb
touch library/nn/lstm/convolutional/ntm_input_gate_vector.adb
touch library/nn/lstm/convolutional/ntm_output_gate_vector.adb
touch library/nn/lstm/convolutional/ntm_state_gate_vector.adb
touch library/nn/lstm/standard/ntm_activation_gate_vector.adb
touch library/nn/lstm/standard/ntm_controller.adb
touch library/nn/lstm/standard/ntm_forget_gate_vector.adb
touch library/nn/lstm/standard/ntm_hidden_gate_vector.adb
touch library/nn/lstm/standard/ntm_input_gate_vector.adb
touch library/nn/lstm/standard/ntm_output_gate_vector.adb
touch library/nn/lstm/standard/ntm_state_gate_vector.adb
touch library/nn/ntm/memory/ntm_addressing.adb
touch library/nn/ntm/memory/ntm_matrix_content_based_addressing.adb
touch library/nn/ntm/memory/ntm_vector_content_based_addressing.adb
touch library/nn/ntm/read_heads/ntm_reading.adb
touch library/nn/ntm/top/ntm_interface_matrix.adb
touch library/nn/ntm/top/ntm_interface_top.adb
touch library/nn/ntm/top/ntm_interface_vector.adb
touch library/nn/ntm/top/ntm_output_vector.adb
touch library/nn/ntm/top/ntm_top.adb
touch library/nn/ntm/trained/ntm_trained_top.adb
touch library/nn/ntm/write_heads/ntm_erasing.adb
touch library/nn/ntm/write_heads/ntm_writing.adb
touch library/state/feedback/ntm_state_feedback.adb
touch library/state/outputs/ntm_state_outputs.adb
touch library/state/top/ntm_state_top.adb
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.adb
touch library/trainer/differentiation/ntm_vector_controller_differentiation.adb
touch library/trainer/fnn/ntm_fnn_b_trainer.adb
touch library/trainer/fnn/ntm_fnn_d_trainer.adb
touch library/trainer/fnn/ntm_fnn_k_trainer.adb
touch library/trainer/fnn/ntm_fnn_trainer.adb
touch library/trainer/fnn/ntm_fnn_u_trainer.adb
touch library/trainer/fnn/ntm_fnn_v_trainer.adb
touch library/trainer/fnn/ntm_fnn_w_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_b_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_d_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_k_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_u_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_v_trainer.adb
touch library/trainer/lstm/activation/ntm_lstm_activation_w_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_b_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_d_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_k_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_u_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_v_trainer.adb
touch library/trainer/lstm/forget/ntm_lstm_forget_w_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_b_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_d_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_k_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_u_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_v_trainer.adb
touch library/trainer/lstm/input/ntm_lstm_input_w_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_b_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_d_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_k_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_u_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_v_trainer.adb
touch library/trainer/lstm/output/ntm_lstm_output_w_trainer.adb
