touch code//classes/philosophers/ntm_philosophers.vhd
touch code//classes/soldiers/ntm_soldiers.vhd
touch code//classes/workers/ntm_workers.vhd
touch code//computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip.vhd
touch code//computing/advanced_computer_architecture/processing_unit/mimd.vhd
touch code//computing/advanced_computer_architecture/processing_unit/misd.vhd
touch code//computing/advanced_computer_architecture/processing_unit/simd.vhd
touch code//computing/advanced_computer_architecture/processing_unit/sisd.vhd
touch code//computing/advanced_computer_architecture/system_on_chip/bus_on_chip.vhd
touch code//computing/advanced_computer_architecture/system_on_chip/network_on_chip.vhd
touch code//computing/computer_architecture/harvard_architecture/alu.vhd
touch code//computing/computer_architecture/harvard_architecture/control_unit.vhd
touch code//computing/computer_architecture/harvard_architecture/io_unit.vhd
touch code//computing/computer_architecture/harvard_architecture/memory_unit.vhd
touch code//computing/computer_architecture/von_neumann_architecture/alu.vhd
touch code//computing/computer_architecture/von_neumann_architecture/control_unit.vhd
touch code//computing/computer_architecture/von_neumann_architecture/io_unit.vhd
touch code//computing/computer_architecture/von_neumann_architecture/memory_unit.vhd
touch code//computing/information/bit/bit.vhd
touch code//computing/information/combinational_logic/arithmetic_circuits.vhd
touch code//computing/information/combinational_logic/logic_circuits.vhd
touch code//computing/information/finite_state_machine/finite_state_machine.vhd
touch code//computing/information/logic_gate/and_gate.vhd
touch code//computing/information/logic_gate/nand_gate.vhd
touch code//computing/information/logic_gate/nor_gate.vhd
touch code//computing/information/logic_gate/not_gate.vhd
touch code//computing/information/logic_gate/or_gate.vhd
touch code//computing/information/logic_gate/xnor_gate.vhd
touch code//computing/information/logic_gate/xor_gate.vhd
touch code//computing/information/logic_gate/yes_gate.vhd
touch code//computing/information/pushdown_automaton/pushdown_automaton.vhd
touch code//computing/neural_network/feedforward_neural_network/feedforward_neural_network.vhd
touch code//computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network.vhd
touch code//computing/neural_network/transformer_neural_network/transformer_neural_network.vhd
touch code//computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer.vhd
touch code//computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer.vhd
touch code//computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer.vhd
touch code//computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine.vhd
touch code//computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine.vhd
touch code//computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine.vhd
touch code//pkg/classes/ntm_philosophers_pkg.vhd
touch code//pkg/classes/ntm_soldiers_pkg.vhd
touch code//pkg/classes/ntm_workers_pkg.vhd
touch code//pkg/ieee/math_complex-body.vhd
touch code//pkg/ieee/math_complex.vhd
touch code//pkg/ieee/math_real-body.vhd
touch code//pkg/ieee/math_real.vhd
touch code//pkg/computing/state_pkg.vhd
touch code/classes/philosophers/ntm_philosophers.vhd
touch code/classes/soldiers/ntm_soldiers.vhd
touch code/classes/workers/ntm_workers.vhd
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip.vhd
touch code/computing/advanced_computer_architecture/processing_unit/mimd.vhd
touch code/computing/advanced_computer_architecture/processing_unit/misd.vhd
touch code/computing/advanced_computer_architecture/processing_unit/simd.vhd
touch code/computing/advanced_computer_architecture/processing_unit/sisd.vhd
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip.vhd
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip.vhd
touch code/computing/computer_architecture/harvard_architecture/alu.vhd
touch code/computing/computer_architecture/harvard_architecture/control_unit.vhd
touch code/computing/computer_architecture/harvard_architecture/io_unit.vhd
touch code/computing/computer_architecture/harvard_architecture/memory_unit.vhd
touch code/computing/computer_architecture/von_neumann_architecture/alu.vhd
touch code/computing/computer_architecture/von_neumann_architecture/control_unit.vhd
touch code/computing/computer_architecture/von_neumann_architecture/io_unit.vhd
touch code/computing/computer_architecture/von_neumann_architecture/memory_unit.vhd
touch code/computing/information/bit/bit.vhd
touch code/computing/information/combinational_logic/arithmetic_circuits.vhd
touch code/computing/information/combinational_logic/logic_circuits.vhd
touch code/computing/information/finite_state_machine/finite_state_machine.vhd
touch code/computing/information/logic_gate/and_gate.vhd
touch code/computing/information/logic_gate/nand_gate.vhd
touch code/computing/information/logic_gate/nor_gate.vhd
touch code/computing/information/logic_gate/not_gate.vhd
touch code/computing/information/logic_gate/or_gate.vhd
touch code/computing/information/logic_gate/xnor_gate.vhd
touch code/computing/information/logic_gate/xor_gate.vhd
touch code/computing/information/logic_gate/yes_gate.vhd
touch code/computing/information/pushdown_automaton/pushdown_automaton.vhd
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network.vhd
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network.vhd
touch code/computing/neural_network/transformer_neural_network/transformer_neural_network.vhd
touch code/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer.vhd
touch code/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer.vhd
touch code/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer.vhd
touch code/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine.vhd
touch code/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine.vhd
touch code/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine.vhd
touch code/pkg/classes/ntm_philosophers_pkg.vhd
touch code/pkg/classes/ntm_soldiers_pkg.vhd
touch code/pkg/classes/ntm_workers_pkg.vhd
touch code/pkg/ieee/math_complex-body.vhd
touch code/pkg/ieee/math_complex.vhd
touch code/pkg/ieee/math_real-body.vhd
touch code/pkg/ieee/math_real.vhd
touch code/pkg/computing/state_pkg.c
