dot -Tsvg graphviz/controller/FNN/convolutional/ntm_controller.dot > graphviz/controller/FNN/convolutional/ntm_controller.svg
dot -Tsvg graphviz/controller/FNN/standard/ntm_controller.dot > graphviz/controller/FNN/standard/ntm_controller.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_activation_gate_vector.dot > graphviz/controller/LSTM/convolutional/ntm_activation_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_controller.dot > graphviz/controller/LSTM/convolutional/ntm_controller.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_forget_gate_vector.dot > graphviz/controller/LSTM/convolutional/ntm_forget_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_hidden_gate_vector.dot > graphviz/controller/LSTM/convolutional/ntm_hidden_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_input_gate_vector.dot > graphviz/controller/LSTM/convolutional/ntm_input_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_output_gate_vector.dot > graphviz/controller/LSTM/convolutional/ntm_output_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/convolutional/ntm_state_gate_vector.dot > graphviz/controller/LSTM/convolutional/ntm_state_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_activation_gate_vector.dot > graphviz/controller/LSTM/standard/ntm_activation_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_controller.dot > graphviz/controller/LSTM/standard/ntm_controller.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_forget_gate_vector.dot > graphviz/controller/LSTM/standard/ntm_forget_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_hidden_gate_vector.dot > graphviz/controller/LSTM/standard/ntm_hidden_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_input_gate_vector.dot > graphviz/controller/LSTM/standard/ntm_input_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_output_gate_vector.dot > graphviz/controller/LSTM/standard/ntm_output_gate_vector.svg
dot -Tsvg graphviz/controller/LSTM/standard/ntm_state_gate_vector.dot > graphviz/controller/LSTM/standard/ntm_state_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/components/ntm_masked_multi_head_attention.dot > graphviz/controller/transformer/components/ntm_masked_multi_head_attention.svg
dot -Tsvg graphviz/controller/transformer/components/ntm_masked_scaled_dot_product_attention.dot > graphviz/controller/transformer/components/ntm_masked_scaled_dot_product_attention.svg
dot -Tsvg graphviz/controller/transformer/components/ntm_multi_head_attention.dot > graphviz/controller/transformer/components/ntm_multi_head_attention.svg
dot -Tsvg graphviz/controller/transformer/components/ntm_scaled_dot_product_attention.dot > graphviz/controller/transformer/components/ntm_scaled_dot_product_attention.svg
dot -Tsvg graphviz/controller/transformer/fnn/ntm_fnn.dot > graphviz/controller/transformer/fnn/ntm_fnn.svg
dot -Tsvg graphviz/controller/transformer/functions/ntm_layer_norm.dot > graphviz/controller/transformer/functions/ntm_layer_norm.svg
dot -Tsvg graphviz/controller/transformer/functions/ntm_positional_encoding.dot > graphviz/controller/transformer/functions/ntm_positional_encoding.svg
dot -Tsvg graphviz/controller/transformer/inputs/ntm_inputs_vector.dot > graphviz/controller/transformer/inputs/ntm_inputs_vector.svg
dot -Tsvg graphviz/controller/transformer/inputs/ntm_keys_vector.dot > graphviz/controller/transformer/inputs/ntm_keys_vector.svg
dot -Tsvg graphviz/controller/transformer/inputs/ntm_queries_vector.dot > graphviz/controller/transformer/inputs/ntm_queries_vector.svg
dot -Tsvg graphviz/controller/transformer/inputs/ntm_values_vector.dot > graphviz/controller/transformer/inputs/ntm_values_vector.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_activation_gate_vector.dot > graphviz/controller/transformer/lstm/ntm_activation_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_forget_gate_vector.dot > graphviz/controller/transformer/lstm/ntm_forget_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_hidden_gate_vector.dot > graphviz/controller/transformer/lstm/ntm_hidden_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_input_gate_vector.dot > graphviz/controller/transformer/lstm/ntm_input_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_lstm.dot > graphviz/controller/transformer/lstm/ntm_lstm.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_output_gate_vector.dot > graphviz/controller/transformer/lstm/ntm_output_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/lstm/ntm_state_gate_vector.dot > graphviz/controller/transformer/lstm/ntm_state_gate_vector.svg
dot -Tsvg graphviz/controller/transformer/top/ntm_controller.dot > graphviz/controller/transformer/top/ntm_controller.svg
dot -Tsvg graphviz/controller/transformer/top/ntm_decoder.dot > graphviz/controller/transformer/top/ntm_decoder.svg
dot -Tsvg graphviz/controller/transformer/top/ntm_encoder.dot > graphviz/controller/transformer/top/ntm_encoder.svg
dot -Tsvg graphviz/dnc/memory/dnc_addressing.dot > graphviz/dnc/memory/dnc_addressing.svg
dot -Tsvg graphviz/dnc/memory/dnc_allocation_weighting.dot > graphviz/dnc/memory/dnc_allocation_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_backward_weighting.dot > graphviz/dnc/memory/dnc_backward_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_forward_weighting.dot > graphviz/dnc/memory/dnc_forward_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_matrix_content_based_addressing.dot > graphviz/dnc/memory/dnc_matrix_content_based_addressing.svg
dot -Tsvg graphviz/dnc/memory/dnc_memory_matrix.dot > graphviz/dnc/memory/dnc_memory_matrix.svg
dot -Tsvg graphviz/dnc/memory/dnc_memory_retention_vector.dot > graphviz/dnc/memory/dnc_memory_retention_vector.svg
dot -Tsvg graphviz/dnc/memory/dnc_precedence_weighting.dot > graphviz/dnc/memory/dnc_precedence_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_read_content_weighting.dot > graphviz/dnc/memory/dnc_read_content_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_read_vectors.dot > graphviz/dnc/memory/dnc_read_vectors.svg
dot -Tsvg graphviz/dnc/memory/dnc_read_weighting.dot > graphviz/dnc/memory/dnc_read_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_sort_vector.dot > graphviz/dnc/memory/dnc_sort_vector.svg
dot -Tsvg graphviz/dnc/memory/dnc_temporal_link_matrix.dot > graphviz/dnc/memory/dnc_temporal_link_matrix.svg
dot -Tsvg graphviz/dnc/memory/dnc_usage_vector.dot > graphviz/dnc/memory/dnc_usage_vector.svg
dot -Tsvg graphviz/dnc/memory/dnc_vector_content_based_addressing.dot > graphviz/dnc/memory/dnc_vector_content_based_addressing.svg
dot -Tsvg graphviz/dnc/memory/dnc_write_content_weighting.dot > graphviz/dnc/memory/dnc_write_content_weighting.svg
dot -Tsvg graphviz/dnc/memory/dnc_write_weighting.dot > graphviz/dnc/memory/dnc_write_weighting.svg
dot -Tsvg graphviz/dnc/top/dnc_interface_matrix.dot > graphviz/dnc/top/dnc_interface_matrix.svg
dot -Tsvg graphviz/dnc/top/dnc_interface_top.dot > graphviz/dnc/top/dnc_interface_top.svg
dot -Tsvg graphviz/dnc/top/dnc_interface_vector.dot > graphviz/dnc/top/dnc_interface_vector.svg
dot -Tsvg graphviz/dnc/top/dnc_output_vector.dot > graphviz/dnc/top/dnc_output_vector.svg
dot -Tsvg graphviz/dnc/top/dnc_top.dot > graphviz/dnc/top/dnc_top.svg
dot -Tsvg graphviz/dnc/trained/dnc_trained_top.dot > graphviz/dnc/trained/dnc_trained_top.svg
dot -Tsvg graphviz/ntm/memory/ntm_addressing.dot > graphviz/ntm/memory/ntm_addressing.svg
dot -Tsvg graphviz/ntm/memory/ntm_matrix_content_based_addressing.dot > graphviz/ntm/memory/ntm_matrix_content_based_addressing.svg
dot -Tsvg graphviz/ntm/memory/ntm_vector_content_based_addressing.dot > graphviz/ntm/memory/ntm_vector_content_based_addressing.svg
dot -Tsvg graphviz/ntm/read_heads/ntm_reading_tesbench.dot > graphviz/ntm/read_heads/ntm_reading_tesbench.svg
dot -Tsvg graphviz/ntm/read_heads/ntm_reading.dot > graphviz/ntm/read_heads/ntm_reading.svg
dot -Tsvg graphviz/ntm/top/ntm_interface_matrix.dot > graphviz/ntm/top/ntm_interface_matrix.svg
dot -Tsvg graphviz/ntm/top/ntm_interface_top.dot > graphviz/ntm/top/ntm_interface_top.svg
dot -Tsvg graphviz/ntm/top/ntm_interface_vector.dot > graphviz/ntm/top/ntm_interface_vector.svg
dot -Tsvg graphviz/ntm/top/ntm_output_vector.dot > graphviz/ntm/top/ntm_output_vector.svg
dot -Tsvg graphviz/ntm/top/ntm_top.dot > graphviz/ntm/top/ntm_top.svg
dot -Tsvg graphviz/ntm/trained/ntm_trained_top.dot > graphviz/ntm/trained/ntm_trained_top.svg
dot -Tsvg graphviz/ntm/write_heads/ntm_erasing_tesbench.dot > graphviz/ntm/write_heads/ntm_erasing_tesbench.svg
dot -Tsvg graphviz/ntm/write_heads/ntm_erasing.dot > graphviz/ntm/write_heads/ntm_erasing.svg
dot -Tsvg graphviz/ntm/write_heads/ntm_writing_tesbench.dot > graphviz/ntm/write_heads/ntm_writing_tesbench.svg
dot -Tsvg graphviz/ntm/write_heads/ntm_writing.dot > graphviz/ntm/write_heads/ntm_writing.svg
dot -Tsvg graphviz/state/feedback/ntm_state_matrix_feedforward.dot > graphviz/state/feedback/ntm_state_matrix_feedforward.svg
dot -Tsvg graphviz/state/feedback/ntm_state_matrix_input.dot > graphviz/state/feedback/ntm_state_matrix_input.svg
dot -Tsvg graphviz/state/feedback/ntm_state_matrix_output.dot > graphviz/state/feedback/ntm_state_matrix_output.svg
dot -Tsvg graphviz/state/feedback/ntm_state_matrix_state.dot > graphviz/state/feedback/ntm_state_matrix_state.svg
dot -Tsvg graphviz/state/outputs/ntm_state_vector_output.dot > graphviz/state/outputs/ntm_state_vector_output.svg
dot -Tsvg graphviz/state/outputs/ntm_state_vector_state.dot > graphviz/state/outputs/ntm_state_vector_state.svg
dot -Tsvg graphviz/state/top/ntm_state_top.dot > graphviz/state/top/ntm_state_top.svg
dot -Tsvg graphviz/trainer/differentiation/ntm_matrix_controller_differentiation.dot > graphviz/trainer/differentiation/ntm_matrix_controller_differentiation.svg
dot -Tsvg graphviz/trainer/differentiation/ntm_vector_controller_differentiation.dot > graphviz/trainer/differentiation/ntm_vector_controller_differentiation.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_b_trainer.dot > graphviz/trainer/FNN/ntm_fnn_b_trainer.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_d_trainer.dot > graphviz/trainer/FNN/ntm_fnn_d_trainer.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_k_trainer.dot > graphviz/trainer/FNN/ntm_fnn_k_trainer.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_trainer.dot > graphviz/trainer/FNN/ntm_fnn_trainer.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_u_trainer.dot > graphviz/trainer/FNN/ntm_fnn_u_trainer.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_v_trainer.dot > graphviz/trainer/FNN/ntm_fnn_v_trainer.svg
dot -Tsvg graphviz/trainer/FNN/ntm_fnn_w_trainer.dot > graphviz/trainer/FNN/ntm_fnn_w_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.dot > graphviz/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.dot > graphviz/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_b_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_b_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_d_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_d_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_k_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_k_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_u_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_u_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_v_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_v_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/input/ntm_lstm_input_w_trainer.dot > graphviz/trainer/LSTM/input/ntm_lstm_input_w_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_b_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_b_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_d_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_d_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_k_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_k_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_u_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_u_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_v_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_v_trainer.svg
dot -Tsvg graphviz/trainer/LSTM/output/ntm_lstm_output_w_trainer.dot > graphviz/trainer/LSTM/output/ntm_lstm_output_w_trainer.svg
