touch code/classes/philosophers/ntm_philosophers.vhd
touch code/classes/soldiers/ntm_soldiers.vhd
touch code/classes/workers/ntm_workers.vhd
touch code/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip.vhd
touch code/computing/advanced_computer_architecture/processing_unit/mimd.vhd
touch code/computing/advanced_computer_architecture/processing_unit/misd.vhd
touch code/computing/advanced_computer_architecture/processing_unit/simd.vhd
touch code/computing/advanced_computer_architecture/processing_unit/sisd.vhd
touch code/computing/advanced_computer_architecture/system_on_chip/bus_on_chip.vhd
touch code/computing/advanced_computer_architecture/system_on_chip/network_on_chip.vhd
touch code/computing/computer_architecture/harvard_architecture/pu_or1k.vhd
touch code/computing/computer_architecture/harvard_architecture/pu_riscv.vhd
touch code/computing/computer_architecture/von_neumann_architecture/pu_msp430.vhd
touch code/computing/computer_architecture/von_neumann_architecture/pu_riscv.vhd
touch code/computing/information/bit/bit.vhd
touch code/computing/information/combinational_logic/arithmetic_circuits.vhd
touch code/computing/information/combinational_logic/logic_circuits.vhd
touch code/computing/information/finite_state_machine/finite_state_machine.vhd
touch code/computing/information/logic_gate/a_and_not_b_gate.vhd
touch code/computing/information/logic_gate/a_gate.vhd
touch code/computing/information/logic_gate/a_implies_b_gate.vhd
touch code/computing/information/logic_gate/and_gate.vhd
touch code/computing/information/logic_gate/b_gate.vhd
touch code/computing/information/logic_gate/b_implies_a_gate.vhd
touch code/computing/information/logic_gate/false_gate.vhd
touch code/computing/information/logic_gate/nand_gate.vhd
touch code/computing/information/logic_gate/nor_gate.vhd
touch code/computing/information/logic_gate/not_a_and_b_gate.vhd
touch code/computing/information/logic_gate/not_a_gate.vhd
touch code/computing/information/logic_gate/not_b_gate.vhd
touch code/computing/information/logic_gate/or_gate.vhd
touch code/computing/information/logic_gate/true_gate.vhd
touch code/computing/information/logic_gate/xnor_gate.vhd
touch code/computing/information/logic_gate/xor_gate.vhd
touch code/computing/information/pushdown_automaton/pushdown_automaton.vhd
touch code/computing/neural_network/attention_neural_network/attention_neural_network.vhd
touch code/computing/neural_network/differentiable_neural_computer_neural_network/differentiable_neural_computer_neural_network.vhd
touch code/computing/neural_network/feedforward_neural_network/feedforward_neural_network.vhd
touch code/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network.vhd
touch code/computing/neural_network/neural_turing_machine_neural_network/neural_turing_machine_neural_network.vhd
touch code/computing/neural_network/perceptron_neural_network/perceptron_neural_network.vhd
touch code/pkg/classes/ntm_philosophers_pkg.vhd
touch code/pkg/classes/ntm_soldiers_pkg.vhd
touch code/pkg/classes/ntm_workers_pkg.vhd
touch code/pkg/computing/state_pkg.vhd
touch code/pkg/ieee/math_complex-body.vhd
touch code/pkg/ieee/math_complex.vhd
touch code/pkg/ieee/math_real-body.vhd
touch code/pkg/ieee/math_real.vhd
