touch code/algebra/matrix/model_matrix_convolution.sv
touch code/algebra/matrix/model_matrix_differentiation.sv
touch code/algebra/matrix/model_matrix_integration.sv
touch code/algebra/matrix/model_matrix_inverse.sv
touch code/algebra/matrix/model_matrix_multiplication.sv
touch code/algebra/matrix/model_matrix_product.sv
touch code/algebra/matrix/model_matrix_softmax.sv
touch code/algebra/matrix/model_matrix_summation.sv
touch code/algebra/matrix/model_matrix_transpose.sv
touch code/algebra/matrix/model_matrix_vector_convolution.sv
touch code/algebra/matrix/model_matrix_vector_product.sv
touch code/algebra/matrix/model_transpose_vector_product.sv
touch code/algebra/tensor/model_tensor_convolution.sv
touch code/algebra/tensor/model_tensor_differentiation.sv
touch code/algebra/tensor/model_tensor_integration.sv
touch code/algebra/tensor/model_tensor_inverse.sv
touch code/algebra/tensor/model_tensor_matrix_convolution.sv
touch code/algebra/tensor/model_tensor_matrix_product.sv
touch code/algebra/tensor/model_tensor_product.sv
touch code/algebra/tensor/model_tensor_softmax.sv
touch code/algebra/tensor/model_tensor_transpose.sv
touch code/algebra/vector/model_dot_product.sv
touch code/algebra/vector/model_vector_convolution.sv
touch code/algebra/vector/model_vector_cosine_similarity.sv
touch code/algebra/vector/model_vector_differentiation.sv
touch code/algebra/vector/model_vector_integration.sv
touch code/algebra/vector/model_vector_module.sv
touch code/algebra/vector/model_vector_multiplication.sv
touch code/algebra/vector/model_vector_softmax.sv
touch code/algebra/vector/model_vector_summation.sv
touch code/architecture/mpsoc/ahb3/model_mpsoc_ahb3.sv
touch code/architecture/mpsoc/apb4/model_mpsoc_apb4.sv
touch code/architecture/mpsoc/axi4/model_mpsoc_axi4.sv
touch code/architecture/mpsoc/bb/model_mpsoc_bb.sv
touch code/architecture/mpsoc/tl/model_mpsoc_tl.sv
touch code/architecture/mpsoc/wb/model_mpsoc_wb.sv
touch code/architecture/pu/ahb3/model_pu_ahb3.sv
touch code/architecture/pu/apb4/model_pu_apb4.sv
touch code/architecture/pu/axi4/model_pu_axi4.sv
touch code/architecture/pu/bb/model_pu_bb.sv
touch code/architecture/pu/tl/model_pu_tl.sv
touch code/architecture/pu/wb/model_pu_wb.sv
touch code/architecture/soc/ahb3/model_soc_ahb3.sv
touch code/architecture/soc/apb4/model_soc_apb4.sv
touch code/architecture/soc/axi4/model_soc_axi4.sv
touch code/architecture/soc/bb/model_soc_bb.sv
touch code/architecture/soc/tl/model_soc_tl.sv
touch code/architecture/soc/wb/model_soc_wb.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_adder.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_divider.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_multiplier.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_subtractor.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_adder.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_divider.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_multiplier.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_subtractor.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_adder.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_divider.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_multiplier.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_subtractor.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_adder.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_divider.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_multiplier.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_subtractor.sv
touch code/arithmetic/float/matrix/model_matrix_float_adder.sv
touch code/arithmetic/float/matrix/model_matrix_float_divider.sv
touch code/arithmetic/float/matrix/model_matrix_float_multiplier.sv
touch code/arithmetic/float/matrix/model_matrix_float_subtractor.sv
touch code/arithmetic/float/scalar/model_scalar_float_adder.sv
touch code/arithmetic/float/scalar/model_scalar_float_divider.sv
touch code/arithmetic/float/scalar/model_scalar_float_multiplier.sv
touch code/arithmetic/float/scalar/model_scalar_float_subtractor.sv
touch code/arithmetic/float/tensor/model_tensor_float_adder.sv
touch code/arithmetic/float/tensor/model_tensor_float_divider.sv
touch code/arithmetic/float/tensor/model_tensor_float_multiplier.sv
touch code/arithmetic/float/tensor/model_tensor_float_subtractor.sv
touch code/arithmetic/float/vector/model_vector_float_adder.sv
touch code/arithmetic/float/vector/model_vector_float_divider.sv
touch code/arithmetic/float/vector/model_vector_float_multiplier.sv
touch code/arithmetic/float/vector/model_vector_float_subtractor.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_adder.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_divider.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_multiplier.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_subtractor.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_adder.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_divider.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_multiplier.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_subtractor.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_adder.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_divider.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_multiplier.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_subtractor.sv
touch code/arithmetic/integer/vector/model_vector_integer_adder.sv
touch code/arithmetic/integer/vector/model_vector_integer_divider.sv
touch code/arithmetic/integer/vector/model_vector_integer_multiplier.sv
touch code/arithmetic/integer/vector/model_vector_integer_subtractor.sv
touch code/math/matrix/model_matrix_cosh_function.sv
touch code/math/matrix/model_matrix_exponentiator_function.sv
touch code/math/matrix/model_matrix_logarithm_function.sv
touch code/math/matrix/model_matrix_logistic_function.sv
touch code/math/matrix/model_matrix_oneplus_function.sv
touch code/math/matrix/model_matrix_sinh_function.sv
touch code/math/matrix/model_matrix_tanh_function.sv
touch code/math/scalar/model_scalar_cosh_function.sv
touch code/math/scalar/model_scalar_exponentiator_function.sv
touch code/math/scalar/model_scalar_logarithm_function.sv
touch code/math/scalar/model_scalar_logistic_function.sv
touch code/math/scalar/model_scalar_oneplus_function.sv
touch code/math/scalar/model_scalar_sinh_function.sv
touch code/math/scalar/model_scalar_tanh_function.sv
touch code/math/vector/model_vector_cosh_function.sv
touch code/math/vector/model_vector_exponentiator_function.sv
touch code/math/vector/model_vector_logarithm_function.sv
touch code/math/vector/model_vector_logistic_function.sv
touch code/math/vector/model_vector_oneplus_function.sv
touch code/math/vector/model_vector_sinh_function.sv
touch code/math/vector/model_vector_tanh_function.sv
touch code/nn/fnn/convolutional/model_controller.sv
touch code/nn/fnn/standard/model_controller.sv
touch code/nn/lstm/convolutional/model_activation_gate_vector.sv
touch code/nn/lstm/convolutional/model_controller.sv
touch code/nn/lstm/convolutional/model_forget_gate_vector.sv
touch code/nn/lstm/convolutional/model_hidden_gate_vector.sv
touch code/nn/lstm/convolutional/model_input_gate_vector.sv
touch code/nn/lstm/convolutional/model_output_gate_vector.sv
touch code/nn/lstm/convolutional/model_state_gate_vector.sv
touch code/nn/lstm/standard/model_activation_gate_vector.sv
touch code/nn/lstm/standard/model_controller.sv
touch code/nn/lstm/standard/model_forget_gate_vector.sv
touch code/nn/lstm/standard/model_hidden_gate_vector.sv
touch code/nn/lstm/standard/model_input_gate_vector.sv
touch code/nn/lstm/standard/model_output_gate_vector.sv
touch code/nn/lstm/standard/model_state_gate_vector.sv
touch code/nn/ntm/memory/model_addressing.sv
touch code/nn/ntm/memory/model_content_based_addressing.sv
touch code/nn/ntm/read_heads/model_reading.sv
touch code/nn/ntm/top/model_interface_matrix.sv
touch code/nn/ntm/top/model_interface_vector.sv
touch code/nn/ntm/top/model_output_vector.sv
touch code/nn/ntm/top/model_top.sv
touch code/nn/ntm/write_heads/model_erasing.sv
touch code/nn/ntm/write_heads/model_writing.sv
touch code/pkg/model_ann_controller_verilog_pkg.sv
touch code/pkg/model_arithmetic_verilog_pkg.sv
touch code/pkg/model_fnn_controller_verilog_pkg.sv
touch code/pkg/model_lstm_controller_verilog_pkg.sv
touch code/pkg/model_math_verilog_pkg.sv
touch code/pkg/model_ntm_core_verilog_pkg.sv
touch code/pkg/model_pnn_controller_verilog_pkg.sv
touch code/pkg/model_state_verilog_pkg.sv
touch code/trainer/differentiation/model_trainer_matrix_differentiation.sv
touch code/trainer/differentiation/model_trainer_vector_differentiation.sv
touch code/trainer/fnn/model_trainer.sv
touch code/trainer/lstm/model_activation_trainer.sv
touch code/trainer/lstm/model_forget_trainer.sv
touch code/trainer/lstm/model_input_trainer.sv
touch code/trainer/lstm/model_output_trainer.sv
touch code/trainer/pnn/model_trainer.sv
