touch code/architecture/mpsoc/model_mpsoc.sv
touch code/architecture/pu/model_pu.sv
touch code/architecture/soc/model_soc.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_adder.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_divider.sv
touch code/arithmetic/fixed/matrix/model_matrix_fixed_multiplier.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_adder.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_divider.sv
touch code/arithmetic/fixed/scalar/model_scalar_fixed_multiplier.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_adder.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_divider.sv
touch code/arithmetic/fixed/tensor/model_tensor_fixed_multiplier.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_adder.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_divider.sv
touch code/arithmetic/fixed/vector/model_vector_fixed_multiplier.sv
touch code/arithmetic/float/matrix/model_matrix_float_adder.sv
touch code/arithmetic/float/matrix/model_matrix_float_divider.sv
touch code/arithmetic/float/matrix/model_matrix_float_multiplier.sv
touch code/arithmetic/float/scalar/model_scalar_float_adder.sv
touch code/arithmetic/float/scalar/model_scalar_float_divider.sv
touch code/arithmetic/float/scalar/model_scalar_float_multiplier.sv
touch code/arithmetic/float/tensor/model_tensor_float_adder.sv
touch code/arithmetic/float/tensor/model_tensor_float_divider.sv
touch code/arithmetic/float/tensor/model_tensor_float_multiplier.sv
touch code/arithmetic/float/vector/model_vector_float_adder.sv
touch code/arithmetic/float/vector/model_vector_float_divider.sv
touch code/arithmetic/float/vector/model_vector_float_multiplier.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_adder.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_divider.sv
touch code/arithmetic/integer/matrix/model_matrix_integer_multiplier.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_adder.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_divider.sv
touch code/arithmetic/integer/scalar/model_scalar_integer_multiplier.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_adder.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_divider.sv
touch code/arithmetic/integer/tensor/model_tensor_integer_multiplier.sv
touch code/arithmetic/integer/vector/model_vector_integer_adder.sv
touch code/arithmetic/integer/vector/model_vector_integer_divider.sv
touch code/arithmetic/integer/vector/model_vector_integer_multiplier.sv
touch code/controller/FNN/convolutional/model_controller.sv
touch code/controller/FNN/standard/model_controller.sv
touch code/controller/LSTM/convolutional/model_activation_gate_vector.sv
touch code/controller/LSTM/convolutional/model_controller.sv
touch code/controller/LSTM/convolutional/model_forget_gate_vector.sv
touch code/controller/LSTM/convolutional/model_hidden_gate_vector.sv
touch code/controller/LSTM/convolutional/model_input_gate_vector.sv
touch code/controller/LSTM/convolutional/model_output_gate_vector.sv
touch code/controller/LSTM/convolutional/model_state_gate_vector.sv
touch code/controller/LSTM/standard/model_activation_gate_vector.sv
touch code/controller/LSTM/standard/model_controller.sv
touch code/controller/LSTM/standard/model_forget_gate_vector.sv
touch code/controller/LSTM/standard/model_hidden_gate_vector.sv
touch code/controller/LSTM/standard/model_input_gate_vector.sv
touch code/controller/LSTM/standard/model_output_gate_vector.sv
touch code/controller/LSTM/standard/model_state_gate_vector.sv
touch code/math/algebra/matrix/model_matrix_convolution.sv
touch code/math/algebra/matrix/model_matrix_inverse.sv
touch code/math/algebra/matrix/model_matrix_multiplication.sv
touch code/math/algebra/matrix/model_matrix_product.sv
touch code/math/algebra/matrix/model_matrix_summation.sv
touch code/math/algebra/matrix/model_matrix_transpose.sv
touch code/math/algebra/matrix/model_matrix_vector_convolution.sv
touch code/math/algebra/matrix/model_matrix_vector_product.sv
touch code/math/algebra/matrix/model_transpose_vector_product.sv
touch code/math/algebra/tensor/model_tensor_convolution.sv
touch code/math/algebra/tensor/model_tensor_inverse.sv
touch code/math/algebra/tensor/model_tensor_matrix_convolution.sv
touch code/math/algebra/tensor/model_tensor_matrix_product.sv
touch code/math/algebra/tensor/model_tensor_product.sv
touch code/math/algebra/tensor/model_tensor_transpose.sv
touch code/math/algebra/vector/model_dot_product.sv
touch code/math/algebra/vector/model_vector_convolution.sv
touch code/math/algebra/vector/model_vector_cosine_similarity.sv
touch code/math/algebra/vector/model_vector_module.sv
touch code/math/algebra/vector/model_vector_multiplication.sv
touch code/math/algebra/vector/model_vector_summation.sv
touch code/math/calculus/matrix/model_matrix_differentiation.sv
touch code/math/calculus/matrix/model_matrix_integration.sv
touch code/math/calculus/matrix/model_matrix_softmax.sv
touch code/math/calculus/tensor/model_tensor_differentiation.sv
touch code/math/calculus/tensor/model_tensor_integration.sv
touch code/math/calculus/tensor/model_tensor_softmax.sv
touch code/math/calculus/vector/model_vector_differentiation.sv
touch code/math/calculus/vector/model_vector_integration.sv
touch code/math/calculus/vector/model_vector_softmax.sv
touch code/math/function/matrix/model_matrix_logistic_function.sv
touch code/math/function/matrix/model_matrix_oneplus_function.sv
touch code/math/function/scalar/model_scalar_logistic_function.sv
touch code/math/function/scalar/model_scalar_oneplus_function.sv
touch code/math/function/vector/model_vector_logistic_function.sv
touch code/math/function/vector/model_vector_oneplus_function.sv
touch code/math/series/matrix/model_matrix_cosh_function.sv
touch code/math/series/matrix/model_matrix_exponentiator_function.sv
touch code/math/series/matrix/model_matrix_logarithm_function.sv
touch code/math/series/matrix/model_matrix_sinh_function.sv
touch code/math/series/matrix/model_matrix_tanh_function.sv
touch code/math/series/scalar/model_scalar_cosh_function.sv
touch code/math/series/scalar/model_scalar_exponentiator_function.sv
touch code/math/series/scalar/model_scalar_logarithm_function.sv
touch code/math/series/scalar/model_scalar_sinh_function.sv
touch code/math/series/scalar/model_scalar_tanh_function.sv
touch code/math/series/vector/model_vector_cosh_function.sv
touch code/math/series/vector/model_vector_exponentiator_function.sv
touch code/math/series/vector/model_vector_logarithm_function.sv
touch code/math/series/vector/model_vector_sinh_function.sv
touch code/math/series/vector/model_vector_tanh_function.sv
touch code/ntm/memory/model_addressing.sv
touch code/ntm/memory/model_content_based_addressing.sv
touch code/ntm/read_heads/model_reading.sv
touch code/ntm/top/model_interface_matrix.sv
touch code/ntm/top/model_interface_vector.sv
touch code/ntm/top/model_output_vector.sv
touch code/ntm/top/model_top.sv
touch code/ntm/write_heads/model_erasing.sv
touch code/ntm/write_heads/model_writing.sv
touch code/pkg/model_arithmetic_verilog_pkg.sv
touch code/pkg/model_fnn_controller_verilog_pkg.sv
touch code/pkg/model_linear_controller_verilog_pkg.sv
touch code/pkg/model_lstm_controller_verilog_pkg.sv
touch code/pkg/model_math_verilog_pkg.sv
touch code/pkg/model_ntm_core_verilog_pkg.sv
touch code/pkg/model_state_verilog_pkg.sv
touch code/pkg/model_transformer_controller_verilog_pkg.sv
touch code/state/feedback/model_state_matrix_feedforward.sv
touch code/state/feedback/model_state_matrix_input.sv
touch code/state/feedback/model_state_matrix_output.sv
touch code/state/feedback/model_state_matrix_state.sv
touch code/state/linear/convolutional/model_controller.sv
touch code/state/linear/standard/model_controller.sv
touch code/state/outputs/model_state_vector_output.sv
touch code/state/outputs/model_state_vector_state.sv
touch code/state/top/model_state_top.sv
touch code/trainer/differentiation/model_trainer_matrix_differentiation.sv
touch code/trainer/differentiation/model_trainer_vector_differentiation.sv
touch code/trainer/FNN/model_trainer.sv
touch code/trainer/linear/model_trainer.sv
touch code/trainer/LSTM/model_activation_trainer.sv
touch code/trainer/LSTM/model_forget_trainer.sv
touch code/trainer/LSTM/model_input_trainer.sv
touch code/trainer/LSTM/model_output_trainer.sv
touch code/transformer/components/model_masked_multi_head_attention.sv
touch code/transformer/components/model_masked_scaled_dot_product_attention.sv
touch code/transformer/components/model_multi_head_attention.sv
touch code/transformer/components/model_scaled_dot_product_attention.sv
touch code/transformer/controller/fnn/convolutional/model_fnn.sv
touch code/transformer/controller/fnn/standard/model_fnn.sv
touch code/transformer/controller/lstm/convolutional/model_lstm.sv
touch code/transformer/controller/lstm/standard/model_lstm.sv
touch code/transformer/functions/model_layer_norm.sv
touch code/transformer/functions/model_positional_encoding.sv
touch code/transformer/inputs/model_inputs_vector.sv
touch code/transformer/inputs/model_keys_vector.sv
touch code/transformer/inputs/model_queries_vector.sv
touch code/transformer/inputs/model_values_vector.sv
touch code/transformer/top/model_controller.sv
touch code/transformer/top/model_decoder.sv
touch code/transformer/top/model_encoder.sv
