emacs -batch vhdl/osvvm/controller/FNN/convolutional/ntm_convolutional_fnn_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/FNN/convolutional/ntm_convolutional_fnn_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/FNN/standard/ntm_standard_fnn_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/FNN/standard/ntm_standard_fnn_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/LSTM/convolutional/ntm_convolutional_lstm_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/LSTM/convolutional/ntm_convolutional_lstm_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/LSTM/standard/ntm_standard_lstm_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/controller/LSTM/standard/ntm_standard_lstm_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/memory/dnc_memory_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/memory/dnc_memory_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/read_heads/dnc_read_heads_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/read_heads/dnc_read_heads_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/top/dnc_top_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/top/dnc_top_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/write_heads/dnc_write_heads_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/dnc/write_heads/dnc_write_heads_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/math/algebra/ntm_algebra_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/math/algebra/ntm_algebra_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/math/arithmetic/ntm_arithmetic_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/math/arithmetic/ntm_arithmetic_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/math/function/ntm_function_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/math/function/ntm_function_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/memory/ntm_memory_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/memory/ntm_memory_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/read_heads/ntm_read_heads_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/read_heads/ntm_read_heads_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/top/ntm_top_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/top/ntm_top_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/write_heads/ntm_write_heads_stimulus.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/osvvm/ntm/write_heads/ntm_write_heads_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
