touch verilog/model/controller/FNN/convolutional/ntm_controller.sv
touch verilog/model/controller/FNN/convolutional/ntm_trainer.sv
touch verilog/model/controller/FNN/standard/ntm_controller.sv
touch verilog/model/controller/FNN/standard/ntm_trainer.sv
touch verilog/model/controller/LSTM/convolutional/ntm_activation_gate_vector.sv
touch verilog/model/controller/LSTM/convolutional/ntm_activation_trainer.sv
touch verilog/model/controller/LSTM/convolutional/ntm_controller.sv
touch verilog/model/controller/LSTM/convolutional/ntm_forget_gate_vector.sv
touch verilog/model/controller/LSTM/convolutional/ntm_forget_trainer.sv
touch verilog/model/controller/LSTM/convolutional/ntm_hidden_gate_vector.sv
touch verilog/model/controller/LSTM/convolutional/ntm_input_gate_vector.sv
touch verilog/model/controller/LSTM/convolutional/ntm_input_trainer.sv
touch verilog/model/controller/LSTM/convolutional/ntm_output_gate_vector.sv
touch verilog/model/controller/LSTM/convolutional/ntm_output_trainer.sv
touch verilog/model/controller/LSTM/convolutional/ntm_state_gate_vector.sv
touch verilog/model/controller/LSTM/standard/ntm_activation_gate_vector.sv
touch verilog/model/controller/LSTM/standard/ntm_activation_trainer.sv
touch verilog/model/controller/LSTM/standard/ntm_controller.sv
touch verilog/model/controller/LSTM/standard/ntm_forget_gate_vector.sv
touch verilog/model/controller/LSTM/standard/ntm_forget_trainer.sv
touch verilog/model/controller/LSTM/standard/ntm_hidden_gate_vector.sv
touch verilog/model/controller/LSTM/standard/ntm_input_gate_vector.sv
touch verilog/model/controller/LSTM/standard/ntm_input_trainer.sv
touch verilog/model/controller/LSTM/standard/ntm_output_gate_vector.sv
touch verilog/model/controller/LSTM/standard/ntm_output_trainer.sv
touch verilog/model/controller/LSTM/standard/ntm_state_gate_vector.sv
touch verilog/model/dnc/memory/dnc_addressing.sv
touch verilog/model/dnc/memory/dnc_allocation_weighting.sv
touch verilog/model/dnc/memory/dnc_backward_weighting.sv
touch verilog/model/dnc/memory/dnc_content_based_addressing.sv
touch verilog/model/dnc/memory/dnc_forward_weighting.sv
touch verilog/model/dnc/memory/dnc_memory_matrix.sv
touch verilog/model/dnc/memory/dnc_memory_retention_vector.sv
touch verilog/model/dnc/memory/dnc_precedence_weighting.sv
touch verilog/model/dnc/memory/dnc_read_content_weighting.sv
touch verilog/model/dnc/memory/dnc_read_vectors.sv
touch verilog/model/dnc/memory/dnc_read_weighting.sv
touch verilog/model/dnc/memory/dnc_sort_vector.sv
touch verilog/model/dnc/memory/dnc_temporal_link_matrix.sv
touch verilog/model/dnc/memory/dnc_usage_vector.sv
touch verilog/model/dnc/memory/dnc_write_content_weighting.sv
touch verilog/model/dnc/memory/dnc_write_weighting.sv
touch verilog/model/dnc/read_heads/dnc_free_gates.sv
touch verilog/model/dnc/read_heads/dnc_read_keys.sv
touch verilog/model/dnc/read_heads/dnc_read_modes.sv
touch verilog/model/dnc/read_heads/dnc_read_strengths.sv
touch verilog/model/dnc/top/dnc_controller_output_vector.sv
touch verilog/model/dnc/top/dnc_output_vector.sv
touch verilog/model/dnc/top/dnc_read_interface_vector.sv
touch verilog/model/dnc/top/dnc_top.sv
touch verilog/model/dnc/top/dnc_write_interface_vector.sv
touch verilog/model/dnc/write_heads/dnc_allocation_gate.sv
touch verilog/model/dnc/write_heads/dnc_erase_vector.sv
touch verilog/model/dnc/write_heads/dnc_write_gate.sv
touch verilog/model/dnc/write_heads/dnc_write_key.sv
touch verilog/model/dnc/write_heads/dnc_write_strength.sv
touch verilog/model/dnc/write_heads/dnc_write_vector.sv
touch verilog/model/math/algebra/ntm_matrix_determinant.sv
touch verilog/model/math/algebra/ntm_matrix_inversion.sv
touch verilog/model/math/algebra/ntm_matrix_product.sv
touch verilog/model/math/algebra/ntm_matrix_rank.sv
touch verilog/model/math/algebra/ntm_matrix_transpose.sv
touch verilog/model/math/algebra/ntm_scalar_product.sv
touch verilog/model/math/algebra/ntm_vector_product.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_adder.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_divider.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_exponentiator.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_inverter.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_logarithm.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_mod.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_multiplier.sv
touch verilog/model/math/arithmetic/matrix/ntm_matrix_root.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_adder.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_divider.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_exponentiator.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_inverter.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_logarithm.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_mod.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_multiplier.sv
touch verilog/model/math/arithmetic/scalar/ntm_scalar_root.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_adder.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_divider.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_exponentiator.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_inverter.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_logarithm.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_mod.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_multiplier.sv
touch verilog/model/math/arithmetic/vector/ntm_vector_root.sv
touch verilog/model/math/function/matrix/ntm_matrix_convolution_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_convolution_function.sv
touch verilog/model/math/function/vector/ntm_vector_convolution_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_cosine_similarity_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_cosine_similarity_function.sv
touch verilog/model/math/function/vector/ntm_vector_cosine_similarity_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_differentiation_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_differentiation_function.sv
touch verilog/model/math/function/vector/ntm_vector_differentiation_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_multiplication_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_multiplication_function.sv
touch verilog/model/math/function/vector/ntm_vector_multiplication_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_cosh_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_sinh_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_tanh_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_logistic_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_softmax_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_oneplus_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_cosh_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_sinh_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_tanh_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_logistic_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_softmax_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_oneplus_function.sv
touch verilog/model/math/function/vector/ntm_vector_cosh_function.sv
touch verilog/model/math/function/vector/ntm_vector_sinh_function.sv
touch verilog/model/math/function/vector/ntm_vector_tanh_function.sv
touch verilog/model/math/function/vector/ntm_vector_logistic_function.sv
touch verilog/model/math/function/vector/ntm_vector_softmax_function.sv
touch verilog/model/math/function/vector/ntm_vector_oneplus_function.sv
touch verilog/model/math/function/matrix/ntm_matrix_summation_function.sv
touch verilog/model/math/function/scalar/ntm_scalar_summation_function.sv
touch verilog/model/math/function/vector/ntm_vector_summation_function.sv
touch verilog/model/ntm/memory/ntm_addressing.sv
touch verilog/model/ntm/memory/ntm_content_based_addressing.sv
touch verilog/model/ntm/read_heads/ntm_reading.sv
touch verilog/model/ntm/top/ntm_controller_output_vector.sv
touch verilog/model/ntm/top/ntm_interface_vector.sv
touch verilog/model/ntm/top/ntm_output_vector.sv
touch verilog/model/ntm/top/ntm_top.sv
touch verilog/model/ntm/write_heads/ntm_erasing.sv
touch verilog/model/ntm/write_heads/ntm_writing.sv
touch verilog/model/pkg/dnc_core_pkg.sv
touch verilog/model/pkg/ntm_core_pkg.sv
touch verilog/model/pkg/ntm_fnn_controller_pkg.sv
touch verilog/model/pkg/ntm_lstm_controller_pkg.sv
touch verilog/model/pkg/ntm_math_pkg.sv
touch verilog/uvm/controller/FNN/convolutional/ntm_convolutional_fnn_stimulus.sv
touch verilog/uvm/controller/FNN/convolutional/ntm_convolutional_fnn_testbench.sv
touch verilog/uvm/controller/FNN/standard/ntm_standard_fnn_stimulus.sv
touch verilog/uvm/controller/FNN/standard/ntm_standard_fnn_testbench.sv
touch verilog/uvm/controller/LSTM/convolutional/ntm_convolutional_lstm_stimulus.sv
touch verilog/uvm/controller/LSTM/convolutional/ntm_convolutional_lstm_testbench.sv
touch verilog/uvm/controller/LSTM/standard/ntm_standard_lstm_stimulus.sv
touch verilog/uvm/controller/LSTM/standard/ntm_standard_lstm_testbench.sv
touch verilog/uvm/dnc/memory/dnc_memory_stimulus.sv
touch verilog/uvm/dnc/memory/dnc_memory_testbench.sv
touch verilog/uvm/dnc/read_heads/dnc_read_heads_stimulus.sv
touch verilog/uvm/dnc/read_heads/dnc_read_heads_testbench.sv
touch verilog/uvm/dnc/top/dnc_top_pkg.sv
touch verilog/uvm/dnc/top/dnc_top_stimulus.sv
touch verilog/uvm/dnc/top/dnc_top_testbench.sv
touch verilog/uvm/dnc/write_heads/dnc_write_heads_stimulus.sv
touch verilog/uvm/dnc/write_heads/dnc_write_heads_testbench.sv
touch verilog/uvm/math/algebra/ntm_algebra_pkg.sv
touch verilog/uvm/math/algebra/ntm_algebra_stimulus.sv
touch verilog/uvm/math/algebra/ntm_algebra_testbench.sv
touch verilog/uvm/math/arithmetic/ntm_arithmetic_pkg.sv
touch verilog/uvm/math/arithmetic/ntm_arithmetic_stimulus.sv
touch verilog/uvm/math/arithmetic/ntm_arithmetic_testbench.sv
touch verilog/uvm/math/function/ntm_function_pkg.sv
touch verilog/uvm/math/function/ntm_function_stimulus.sv
touch verilog/uvm/math/function/ntm_function_testbench.sv
touch verilog/uvm/ntm/memory/ntm_memory_stimulus.sv
touch verilog/uvm/ntm/memory/ntm_memory_testbench.sv
touch verilog/uvm/ntm/read_heads/ntm_read_heads_stimulus.sv
touch verilog/uvm/ntm/read_heads/ntm_read_heads_testbench.sv
touch verilog/uvm/ntm/top/ntm_top_pkg.sv
touch verilog/uvm/ntm/top/ntm_top_stimulus.sv
touch verilog/uvm/ntm/top/ntm_top_testbench.sv
touch verilog/uvm/ntm/write_heads/ntm_write_heads_stimulus.sv
touch verilog/uvm/ntm/write_heads/ntm_write_heads_testbench.sv
