touch code/arithmetic/float/matrix/ntm_matrix_float_adder.sv
touch code/arithmetic/float/matrix/ntm_matrix_float_divider.sv
touch code/arithmetic/float/matrix/ntm_matrix_float_multiplier.sv
touch code/arithmetic/float/scalar/ntm_scalar_float_adder.sv
touch code/arithmetic/float/scalar/ntm_scalar_float_divider.sv
touch code/arithmetic/float/scalar/ntm_scalar_float_multiplier.sv
touch code/arithmetic/float/tensor/ntm_tensor_float_adder.sv
touch code/arithmetic/float/tensor/ntm_tensor_float_divider.sv
touch code/arithmetic/float/tensor/ntm_tensor_float_multiplier.sv
touch code/arithmetic/float/vector/ntm_vector_float_adder.sv
touch code/arithmetic/float/vector/ntm_vector_float_divider.sv
touch code/arithmetic/float/vector/ntm_vector_float_multiplier.sv
touch code/arithmetic/integer/matrix/ntm_matrix_integer_adder.sv
touch code/arithmetic/integer/matrix/ntm_matrix_integer_divider.sv
touch code/arithmetic/integer/matrix/ntm_matrix_integer_multiplier.sv
touch code/arithmetic/integer/scalar/ntm_scalar_integer_adder.sv
touch code/arithmetic/integer/scalar/ntm_scalar_integer_divider.sv
touch code/arithmetic/integer/scalar/ntm_scalar_integer_multiplier.sv
touch code/arithmetic/integer/tensor/ntm_tensor_integer_adder.sv
touch code/arithmetic/integer/tensor/ntm_tensor_integer_divider.sv
touch code/arithmetic/integer/tensor/ntm_tensor_integer_multiplier.sv
touch code/arithmetic/integer/vector/ntm_vector_integer_adder.sv
touch code/arithmetic/integer/vector/ntm_vector_integer_divider.sv
touch code/arithmetic/integer/vector/ntm_vector_integer_multiplier.sv
touch code/arithmetic/modular/matrix/ntm_matrix_modular_adder.sv
touch code/arithmetic/modular/matrix/ntm_matrix_modular_inverter.sv
touch code/arithmetic/modular/matrix/ntm_matrix_modular_mod.sv
touch code/arithmetic/modular/matrix/ntm_matrix_modular_multiplier.sv
touch code/arithmetic/modular/scalar/ntm_scalar_modular_adder.sv
touch code/arithmetic/modular/scalar/ntm_scalar_modular_inverter.sv
touch code/arithmetic/modular/scalar/ntm_scalar_modular_mod.sv
touch code/arithmetic/modular/scalar/ntm_scalar_modular_multiplier.sv
touch code/arithmetic/modular/tensor/ntm_tensor_modular_adder.sv
touch code/arithmetic/modular/tensor/ntm_tensor_modular_inverter.sv
touch code/arithmetic/modular/tensor/ntm_tensor_modular_mod.sv
touch code/arithmetic/modular/tensor/ntm_tensor_modular_multiplier.sv
touch code/arithmetic/modular/vector/ntm_vector_modular_adder.sv
touch code/arithmetic/modular/vector/ntm_vector_modular_inverter.sv
touch code/arithmetic/modular/vector/ntm_vector_modular_mod.sv
touch code/arithmetic/modular/vector/ntm_vector_modular_multiplier.sv
touch code/controller/FNN/convolutional/ntm_controller.sv
touch code/controller/FNN/standard/ntm_controller.sv
touch code/controller/LSTM/convolutional/ntm_activation_gate_vector.sv
touch code/controller/LSTM/convolutional/ntm_controller.sv
touch code/controller/LSTM/convolutional/ntm_forget_gate_vector.sv
touch code/controller/LSTM/convolutional/ntm_hidden_gate_vector.sv
touch code/controller/LSTM/convolutional/ntm_input_gate_vector.sv
touch code/controller/LSTM/convolutional/ntm_output_gate_vector.sv
touch code/controller/LSTM/convolutional/ntm_state_gate_vector.sv
touch code/controller/LSTM/standard/ntm_activation_gate_vector.sv
touch code/controller/LSTM/standard/ntm_controller.sv
touch code/controller/LSTM/standard/ntm_forget_gate_vector.sv
touch code/controller/LSTM/standard/ntm_hidden_gate_vector.sv
touch code/controller/LSTM/standard/ntm_input_gate_vector.sv
touch code/controller/LSTM/standard/ntm_output_gate_vector.sv
touch code/controller/LSTM/standard/ntm_state_gate_vector.sv
touch code/transformer/components/ntm_masked_multi_head_attention.sv
touch code/transformer/components/ntm_masked_scaled_dot_product_attention.sv
touch code/transformer/components/ntm_multi_head_attention.sv
touch code/transformer/components/ntm_scaled_dot_product_attention.sv
touch code/transformer/fnn/ntm_fnn.sv
touch code/transformer/functions/ntm_layer_norm.sv
touch code/transformer/functions/ntm_positional_encoding.sv
touch code/transformer/inputs/ntm_inputs_vector.sv
touch code/transformer/inputs/ntm_keys_vector.sv
touch code/transformer/inputs/ntm_queries_vector.sv
touch code/transformer/inputs/ntm_values_vector.sv
touch code/transformer/lstm/ntm_activation_gate_vector.sv
touch code/transformer/lstm/ntm_forget_gate_vector.sv
touch code/transformer/lstm/ntm_hidden_gate_vector.sv
touch code/transformer/lstm/ntm_input_gate_vector.sv
touch code/transformer/lstm/ntm_lstm.sv
touch code/transformer/lstm/ntm_output_gate_vector.sv
touch code/transformer/lstm/ntm_state_gate_vector.sv
touch code/transformer/top/ntm_controller.sv
touch code/transformer/top/ntm_decoder.sv
touch code/transformer/top/ntm_encoder.sv
touch code/dnc/memory/dnc_addressing.sv
touch code/dnc/memory/dnc_allocation_weighting.sv
touch code/dnc/memory/dnc_backward_weighting.sv
touch code/dnc/memory/dnc_content_based_addressing.sv
touch code/dnc/memory/dnc_forward_weighting.sv
touch code/dnc/memory/dnc_memory_matrix.sv
touch code/dnc/memory/dnc_memory_retention_vector.sv
touch code/dnc/memory/dnc_precedence_weighting.sv
touch code/dnc/memory/dnc_read_content_weighting.sv
touch code/dnc/memory/dnc_read_vectors.sv
touch code/dnc/memory/dnc_read_weighting.sv
touch code/dnc/memory/dnc_sort_vector.sv
touch code/dnc/memory/dnc_temporal_link_matrix.sv
touch code/dnc/memory/dnc_usage_vector.sv
touch code/dnc/memory/dnc_write_content_weighting.sv
touch code/dnc/memory/dnc_write_weighting.sv
touch code/dnc/read_heads/dnc_read_heads.sv
touch code/dnc/top/dnc_interface_matrix.sv
touch code/dnc/top/dnc_interface_vector.sv
touch code/dnc/top/dnc_output_vector.sv
touch code/dnc/top/dnc_top.sv
touch code/dnc/write_heads/dnc_write_heads.sv
touch code/intro/ntm_intro_adder.sv
touch code/math/algebra/matrix/ntm_matrix_convolution.sv
touch code/math/algebra/matrix/ntm_matrix_inverse.sv
touch code/math/algebra/matrix/ntm_matrix_multiplication.sv
touch code/math/algebra/matrix/ntm_matrix_product.sv
touch code/math/algebra/matrix/ntm_matrix_summation.sv
touch code/math/algebra/matrix/ntm_matrix_transpose.sv
touch code/math/algebra/matrix/ntm_matrix_vector_convolution.sv
touch code/math/algebra/matrix/ntm_matrix_vector_product.sv
touch code/math/algebra/matrix/ntm_transpose_vector_product.sv
touch code/math/algebra/tensor/ntm_tensor_convolution.sv
touch code/math/algebra/tensor/ntm_tensor_inverse.sv
touch code/math/algebra/tensor/ntm_tensor_matrix_convolution.sv
touch code/math/algebra/tensor/ntm_tensor_matrix_product.sv
touch code/math/algebra/tensor/ntm_tensor_multiplication.sv
touch code/math/algebra/tensor/ntm_tensor_product.sv
touch code/math/algebra/tensor/ntm_tensor_summation.sv
touch code/math/algebra/tensor/ntm_tensor_transpose.sv
touch code/math/algebra/vector/ntm_dot_product.sv
touch code/math/algebra/vector/ntm_vector_convolution.sv
touch code/math/algebra/vector/ntm_vector_cosine_similarity.sv
touch code/math/algebra/vector/ntm_vector_module.sv
touch code/math/algebra/vector/ntm_vector_multiplication.sv
touch code/math/algebra/vector/ntm_vector_summation.sv
touch code/math/calculus/matrix/ntm_matrix_differentiation.sv
touch code/math/calculus/matrix/ntm_matrix_integration.sv
touch code/math/calculus/matrix/ntm_matrix_softmax.sv
touch code/math/calculus/tensor/ntm_tensor_differentiation.sv
touch code/math/calculus/tensor/ntm_tensor_integration.sv
touch code/math/calculus/tensor/ntm_tensor_softmax.sv
touch code/math/calculus/vector/ntm_vector_differentiation.sv
touch code/math/calculus/vector/ntm_vector_integration.sv
touch code/math/calculus/vector/ntm_vector_softmax.sv
touch code/math/function/matrix/ntm_matrix_logistic_function.sv
touch code/math/function/matrix/ntm_matrix_oneplus_function.sv
touch code/math/function/scalar/ntm_scalar_logistic_function.sv
touch code/math/function/scalar/ntm_scalar_oneplus_function.sv
touch code/math/function/vector/ntm_vector_logistic_function.sv
touch code/math/function/vector/ntm_vector_oneplus_function.sv
touch code/math/series/matrix/ntm_matrix_cosh_function.sv
touch code/math/series/matrix/ntm_matrix_exponentiator_function.sv
touch code/math/series/matrix/ntm_matrix_logarithm_function.sv
touch code/math/series/matrix/ntm_matrix_power_function.sv
touch code/math/series/matrix/ntm_matrix_sinh_function.sv
touch code/math/series/matrix/ntm_matrix_sqrt_function.sv
touch code/math/series/matrix/ntm_matrix_tanh_function.sv
touch code/math/series/scalar/ntm_scalar_cosh_function.sv
touch code/math/series/scalar/ntm_scalar_exponentiator_function.sv
touch code/math/series/scalar/ntm_scalar_logarithm_function.sv
touch code/math/series/scalar/ntm_scalar_power_function.sv
touch code/math/series/scalar/ntm_scalar_sinh_function.sv
touch code/math/series/scalar/ntm_scalar_sqrt_function.sv
touch code/math/series/scalar/ntm_scalar_tanh_function.sv
touch code/math/series/vector/ntm_vector_cosh_function.sv
touch code/math/series/vector/ntm_vector_exponentiator_function.sv
touch code/math/series/vector/ntm_vector_logarithm_function.sv
touch code/math/series/vector/ntm_vector_power_function.sv
touch code/math/series/vector/ntm_vector_sinh_function.sv
touch code/math/series/vector/ntm_vector_sqrt_function.sv
touch code/math/series/vector/ntm_vector_tanh_function.sv
touch code/ntm/memory/ntm_addressing.sv
touch code/ntm/memory/ntm_content_based_addressing.sv
touch code/ntm/read_heads/ntm_reading.sv
touch code/ntm/top/ntm_interface_matrix.sv
touch code/ntm/top/ntm_interface_vector.sv
touch code/ntm/top/ntm_output_vector.sv
touch code/ntm/top/ntm_top.sv
touch code/ntm/write_heads/ntm_erasing.sv
touch code/ntm/write_heads/ntm_writing.sv
touch code/pkg/dnc_core_pkg.sv
touch code/pkg/ntm_arithmetic_pkg.sv
touch code/pkg/ntm_core_pkg.sv
touch code/pkg/ntm_fnn_controller_pkg.sv
touch code/pkg/ntm_intro_pkg.sv
touch code/pkg/ntm_lstm_controller_pkg.sv
touch code/pkg/ntm_math_pkg.sv
touch code/pkg/ntm_state_pkg.sv
touch code/state/feedback/ntm_state_matrix_feedforward.sv
touch code/state/feedback/ntm_state_matrix_input.sv
touch code/state/feedback/ntm_state_matrix_output.sv
touch code/state/feedback/ntm_state_matrix_state.sv
touch code/state/outputs/ntm_state_vector_output.sv
touch code/state/outputs/ntm_state_vector_state.sv
touch code/state/top/ntm_state_top.sv
touch code/trainer/differentiation/ntm_matrix_controller_differentiation.sv
touch code/trainer/differentiation/ntm_vector_controller_differentiation.sv
touch code/trainer/FNN/ntm_trainer.sv
touch code/trainer/LSTM/ntm_activation_trainer.sv
touch code/trainer/LSTM/ntm_forget_trainer.sv
touch code/trainer/LSTM/ntm_input_trainer.sv
touch code/trainer/LSTM/ntm_output_trainer.sv
