touch code/architecture/mpsoc/accelerator_mpsoc.sv
touch code/architecture/pu/accelerator_pu.sv
touch code/architecture/soc/accelerator_soc.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_adder.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_divider.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_multiplier.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_adder.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_divider.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_multiplier.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_adder.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_divider.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_multiplier.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_adder.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_divider.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_multiplier.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_adder.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_divider.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_multiplier.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_adder.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_divider.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_multiplier.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_adder.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_divider.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_multiplier.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_adder.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_divider.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_multiplier.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_adder.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_divider.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_multiplier.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_adder.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_divider.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_multiplier.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_adder.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_divider.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_multiplier.sv
touch code/arithmetic/float/vector/accelerator_vector_float_adder.sv
touch code/arithmetic/float/vector/accelerator_vector_float_divider.sv
touch code/arithmetic/float/vector/accelerator_vector_float_multiplier.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_adder.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_divider.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_multiplier.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_adder.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_divider.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_multiplier.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_adder.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_divider.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_multiplier.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_adder.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_divider.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_multiplier.sv
touch code/controller/FNN/convolutional/accelerator_controller.sv
touch code/controller/FNN/standard/accelerator_controller.sv
touch code/controller/LSTM/convolutional/accelerator_activation_gate_vector.sv
touch code/controller/LSTM/convolutional/accelerator_controller.sv
touch code/controller/LSTM/convolutional/accelerator_forget_gate_vector.sv
touch code/controller/LSTM/convolutional/accelerator_hidden_gate_vector.sv
touch code/controller/LSTM/convolutional/accelerator_input_gate_vector.sv
touch code/controller/LSTM/convolutional/accelerator_output_gate_vector.sv
touch code/controller/LSTM/convolutional/accelerator_state_gate_vector.sv
touch code/controller/LSTM/standard/accelerator_activation_gate_vector.sv
touch code/controller/LSTM/standard/accelerator_controller.sv
touch code/controller/LSTM/standard/accelerator_forget_gate_vector.sv
touch code/controller/LSTM/standard/accelerator_hidden_gate_vector.sv
touch code/controller/LSTM/standard/accelerator_input_gate_vector.sv
touch code/controller/LSTM/standard/accelerator_output_gate_vector.sv
touch code/controller/LSTM/standard/accelerator_state_gate_vector.sv
touch code/math/algebra/matrix/accelerator_matrix_convolution.sv
touch code/math/algebra/matrix/accelerator_matrix_inverse.sv
touch code/math/algebra/matrix/accelerator_matrix_multiplication.sv
touch code/math/algebra/matrix/accelerator_matrix_product.sv
touch code/math/algebra/matrix/accelerator_matrix_summation.sv
touch code/math/algebra/matrix/accelerator_matrix_transpose.sv
touch code/math/algebra/matrix/accelerator_matrix_vector_convolution.sv
touch code/math/algebra/matrix/accelerator_matrix_vector_product.sv
touch code/math/algebra/tensor/accelerator_tensor_convolution.sv
touch code/math/algebra/tensor/accelerator_tensor_inverse.sv
touch code/math/algebra/tensor/accelerator_tensor_matrix_convolution.sv
touch code/math/algebra/tensor/accelerator_tensor_matrix_product.sv
touch code/math/algebra/tensor/accelerator_tensor_product.sv
touch code/math/algebra/tensor/accelerator_tensor_transpose.sv
touch code/math/algebra/vector/accelerator_dot_product.sv
touch code/math/algebra/vector/accelerator_vector_convolution.sv
touch code/math/algebra/vector/accelerator_vector_cosine_similarity.sv
touch code/math/algebra/vector/accelerator_vector_module.sv
touch code/math/algebra/vector/accelerator_vector_multiplication.sv
touch code/math/algebra/vector/accelerator_vector_summation.sv
touch code/math/algebra/vector/accelerator_vector_transpose.sv
touch code/math/calculus/matrix/accelerator_matrix_differentiation.sv
touch code/math/calculus/matrix/accelerator_matrix_integration.sv
touch code/math/calculus/matrix/accelerator_matrix_softmax.sv
touch code/math/calculus/tensor/accelerator_tensor_differentiation.sv
touch code/math/calculus/tensor/accelerator_tensor_integration.sv
touch code/math/calculus/tensor/accelerator_tensor_softmax.sv
touch code/math/calculus/vector/accelerator_vector_differentiation.sv
touch code/math/calculus/vector/accelerator_vector_integration.sv
touch code/math/calculus/vector/accelerator_vector_softmax.sv
touch code/math/function/matrix/accelerator_matrix_logistic_function.sv
touch code/math/function/matrix/accelerator_matrix_oneplus_function.sv
touch code/math/function/scalar/accelerator_scalar_logistic_function.sv
touch code/math/function/scalar/accelerator_scalar_oneplus_function.sv
touch code/math/function/vector/accelerator_vector_logistic_function.sv
touch code/math/function/vector/accelerator_vector_oneplus_function.sv
touch code/math/series/matrix/accelerator_matrix_cosh_function.sv
touch code/math/series/matrix/accelerator_matrix_exponentiator_function.sv
touch code/math/series/matrix/accelerator_matrix_logarithm_function.sv
touch code/math/series/matrix/accelerator_matrix_sinh_function.sv
touch code/math/series/matrix/accelerator_matrix_tanh_function.sv
touch code/math/series/scalar/accelerator_scalar_cosh_function.sv
touch code/math/series/scalar/accelerator_scalar_exponentiator_function.sv
touch code/math/series/scalar/accelerator_scalar_logarithm_function.sv
touch code/math/series/scalar/accelerator_scalar_sinh_function.sv
touch code/math/series/scalar/accelerator_scalar_tanh_function.sv
touch code/math/series/vector/accelerator_vector_cosh_function.sv
touch code/math/series/vector/accelerator_vector_exponentiator_function.sv
touch code/math/series/vector/accelerator_vector_logarithm_function.sv
touch code/math/series/vector/accelerator_vector_sinh_function.sv
touch code/math/series/vector/accelerator_vector_tanh_function.sv
touch code/ntm/memory/accelerator_addressing.sv
touch code/ntm/memory/accelerator_content_based_addressing.sv
touch code/ntm/read_heads/accelerator_reading.sv
touch code/ntm/top/accelerator_interface_vector.sv
touch code/ntm/top/accelerator_output_vector.sv
touch code/ntm/top/accelerator_top.sv
touch code/ntm/write_heads/accelerator_erasing.sv
touch code/ntm/write_heads/accelerator_writing.sv
touch code/pkg/accelerator_arithmetic_verilog_pkg.sv
touch code/pkg/accelerator_core_verilog_pkg.sv
touch code/pkg/accelerator_fnn_controller_verilog_pkg.sv
touch code/pkg/accelerator_linear_controller_verilog_pkg.sv
touch code/pkg/accelerator_lstm_controller_verilog_pkg.sv
touch code/pkg/accelerator_math_verilog_pkg.sv
touch code/pkg/accelerator_state_verilog_pkg.sv
touch code/pkg/accelerator_transformer_controller_verilog_pkg.sv
touch code/state/feedback/accelerator_state_matrix_feedforward.sv
touch code/state/feedback/accelerator_state_matrix_input.sv
touch code/state/feedback/accelerator_state_matrix_output.sv
touch code/state/feedback/accelerator_state_matrix_state.sv
touch code/state/linear/convolutional/accelerator_controller.sv
touch code/state/linear/standard/accelerator_controller.sv
touch code/state/outputs/accelerator_state_vector_output.sv
touch code/state/outputs/accelerator_state_vector_state.sv
touch code/state/top/accelerator_state_top.sv
touch code/trainer/differentiation/accelerator_trainer_matrix_differentiation.sv
touch code/trainer/differentiation/accelerator_trainer_vector_differentiation.sv
touch code/trainer/FNN/accelerator_trainer.sv
touch code/trainer/linear/accelerator_trainer.sv
touch code/trainer/LSTM/accelerator_activation_trainer.sv
touch code/trainer/LSTM/accelerator_forget_trainer.sv
touch code/trainer/LSTM/accelerator_input_trainer.sv
touch code/trainer/LSTM/accelerator_output_trainer.sv
touch code/transformer/components/accelerator_masked_multi_head_attention.sv
touch code/transformer/components/accelerator_masked_scaled_dot_product_attention.sv
touch code/transformer/components/accelerator_multi_head_attention.sv
touch code/transformer/components/accelerator_scaled_dot_product_attention.sv
touch code/transformer/controller/fnn/convolutional/accelerator_fnn.sv
touch code/transformer/controller/fnn/standard/accelerator_fnn.sv
touch code/transformer/controller/lstm/convolutional/accelerator_lstm.sv
touch code/transformer/controller/lstm/standard/accelerator_lstm.sv
touch code/transformer/functions/accelerator_layer_norm.sv
touch code/transformer/functions/accelerator_positional_encoding.sv
touch code/transformer/inputs/accelerator_inputs_vector.sv
touch code/transformer/inputs/accelerator_keys_vector.sv
touch code/transformer/inputs/accelerator_queries_vector.sv
touch code/transformer/inputs/accelerator_values_vector.sv
touch code/transformer/top/accelerator_controller.sv
touch code/transformer/top/accelerator_decoder.sv
touch code/transformer/top/accelerator_encoder.sv
