touch code/algebra/matrix/accelerator_matrix_convolution.sv
touch code/algebra/matrix/accelerator_matrix_differentiation.sv
touch code/algebra/matrix/accelerator_matrix_integration.sv
touch code/algebra/matrix/accelerator_matrix_inverse.sv
touch code/algebra/matrix/accelerator_matrix_multiplication.sv
touch code/algebra/matrix/accelerator_matrix_product.sv
touch code/algebra/matrix/accelerator_matrix_softmax.sv
touch code/algebra/matrix/accelerator_matrix_summation.sv
touch code/algebra/matrix/accelerator_matrix_transpose.sv
touch code/algebra/matrix/accelerator_matrix_vector_convolution.sv
touch code/algebra/matrix/accelerator_matrix_vector_product.sv
touch code/algebra/tensor/accelerator_tensor_convolution.sv
touch code/algebra/tensor/accelerator_tensor_differentiation.sv
touch code/algebra/tensor/accelerator_tensor_integration.sv
touch code/algebra/tensor/accelerator_tensor_inverse.sv
touch code/algebra/tensor/accelerator_tensor_matrix_convolution.sv
touch code/algebra/tensor/accelerator_tensor_matrix_product.sv
touch code/algebra/tensor/accelerator_tensor_product.sv
touch code/algebra/tensor/accelerator_tensor_softmax.sv
touch code/algebra/tensor/accelerator_tensor_transpose.sv
touch code/algebra/vector/accelerator_dot_product.sv
touch code/algebra/vector/accelerator_vector_convolution.sv
touch code/algebra/vector/accelerator_vector_cosine_similarity.sv
touch code/algebra/vector/accelerator_vector_differentiation.sv
touch code/algebra/vector/accelerator_vector_integration.sv
touch code/algebra/vector/accelerator_vector_module.sv
touch code/algebra/vector/accelerator_vector_multiplication.sv
touch code/algebra/vector/accelerator_vector_softmax.sv
touch code/algebra/vector/accelerator_vector_summation.sv
touch code/algebra/vector/accelerator_vector_transpose.sv
touch code/architecture/mpsoc/ahb4/model_mpsoc_ahb4.sv
touch code/architecture/mpsoc/apb4/model_mpsoc_apb4.sv
touch code/architecture/mpsoc/axi4/model_mpsoc_axi4.sv
touch code/architecture/mpsoc/bb/model_mpsoc_bb.sv
touch code/architecture/mpsoc/biu/model_mpsoc_biu.sv
touch code/architecture/mpsoc/wb/model_mpsoc_wb.sv
touch code/architecture/pu/ahb4/model_pu_ahb4.sv
touch code/architecture/pu/apb4/model_pu_apb4.sv
touch code/architecture/pu/axi4/model_pu_axi4.sv
touch code/architecture/pu/bb/model_pu_bb.sv
touch code/architecture/pu/biu/model_pu_biu.sv
touch code/architecture/pu/wb/model_pu_wb.sv
touch code/architecture/soc/ahb4/model_soc_ahb4.sv
touch code/architecture/soc/apb4/model_soc_apb4.sv
touch code/architecture/soc/axi4/model_soc_axi4.sv
touch code/architecture/soc/bb/model_soc_bb.sv
touch code/architecture/soc/biu/model_soc_biu.sv
touch code/architecture/soc/wb/model_soc_wb.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_adder.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_divider.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_multiplier.sv
touch code/arithmetic/definition/matrix/accelerator_matrix_float_subtractor.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_adder.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_divider.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_multiplier.sv
touch code/arithmetic/definition/scalar/accelerator_scalar_float_subtractor.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_adder.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_divider.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_multiplier.sv
touch code/arithmetic/definition/tensor/accelerator_tensor_float_subtractor.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_adder.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_divider.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_multiplier.sv
touch code/arithmetic/definition/vector/accelerator_vector_float_subtractor.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_adder.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_divider.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_multiplier.sv
touch code/arithmetic/fixed/matrix/accelerator_matrix_fixed_subtractor.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_adder.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_divider.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_multiplier.sv
touch code/arithmetic/fixed/scalar/accelerator_scalar_fixed_subtractor.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_adder.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_divider.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_multiplier.sv
touch code/arithmetic/fixed/tensor/accelerator_tensor_fixed_subtractor.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_adder.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_divider.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_multiplier.sv
touch code/arithmetic/fixed/vector/accelerator_vector_fixed_subtractor.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_adder.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_divider.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_multiplier.sv
touch code/arithmetic/float/matrix/accelerator_matrix_float_subtractor.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_adder.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_divider.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_multiplier.sv
touch code/arithmetic/float/scalar/accelerator_scalar_float_subtractor.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_adder.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_divider.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_multiplier.sv
touch code/arithmetic/float/tensor/accelerator_tensor_float_subtractor.sv
touch code/arithmetic/float/vector/accelerator_vector_float_adder.sv
touch code/arithmetic/float/vector/accelerator_vector_float_divider.sv
touch code/arithmetic/float/vector/accelerator_vector_float_multiplier.sv
touch code/arithmetic/float/vector/accelerator_vector_float_subtractor.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_adder.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_divider.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_multiplier.sv
touch code/arithmetic/integer/matrix/accelerator_matrix_integer_subtractor.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_adder.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_divider.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_multiplier.sv
touch code/arithmetic/integer/scalar/accelerator_scalar_integer_subtractor.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_adder.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_divider.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_multiplier.sv
touch code/arithmetic/integer/tensor/accelerator_tensor_integer_subtractor.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_adder.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_divider.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_multiplier.sv
touch code/arithmetic/integer/vector/accelerator_vector_integer_subtractor.sv
touch code/math/matrix/accelerator_matrix_cosh_function.sv
touch code/math/matrix/accelerator_matrix_exponentiator_function.sv
touch code/math/matrix/accelerator_matrix_logarithm_function.sv
touch code/math/matrix/accelerator_matrix_logistic_function.sv
touch code/math/matrix/accelerator_matrix_oneplus_function.sv
touch code/math/matrix/accelerator_matrix_sinh_function.sv
touch code/math/matrix/accelerator_matrix_tanh_function.sv
touch code/math/scalar/accelerator_scalar_cosh_function.sv
touch code/math/scalar/accelerator_scalar_exponentiator_function.sv
touch code/math/scalar/accelerator_scalar_logarithm_function.sv
touch code/math/scalar/accelerator_scalar_logistic_function.sv
touch code/math/scalar/accelerator_scalar_oneplus_function.sv
touch code/math/scalar/accelerator_scalar_sinh_function.sv
touch code/math/scalar/accelerator_scalar_tanh_function.sv
touch code/math/vector/accelerator_vector_cosh_function.sv
touch code/math/vector/accelerator_vector_exponentiator_function.sv
touch code/math/vector/accelerator_vector_logarithm_function.sv
touch code/math/vector/accelerator_vector_logistic_function.sv
touch code/math/vector/accelerator_vector_oneplus_function.sv
touch code/math/vector/accelerator_vector_sinh_function.sv
touch code/math/vector/accelerator_vector_tanh_function.sv
touch code/nn/fnn/convolutional/accelerator_controller.sv
touch code/nn/fnn/standard/accelerator_controller.sv
touch code/nn/lstm/convolutional/accelerator_activation_gate_vector.sv
touch code/nn/lstm/convolutional/accelerator_controller.sv
touch code/nn/lstm/convolutional/accelerator_forget_gate_vector.sv
touch code/nn/lstm/convolutional/accelerator_hidden_gate_vector.sv
touch code/nn/lstm/convolutional/accelerator_input_gate_vector.sv
touch code/nn/lstm/convolutional/accelerator_output_gate_vector.sv
touch code/nn/lstm/convolutional/accelerator_state_gate_vector.sv
touch code/nn/lstm/standard/accelerator_activation_gate_vector.sv
touch code/nn/lstm/standard/accelerator_controller.sv
touch code/nn/lstm/standard/accelerator_forget_gate_vector.sv
touch code/nn/lstm/standard/accelerator_hidden_gate_vector.sv
touch code/nn/lstm/standard/accelerator_input_gate_vector.sv
touch code/nn/lstm/standard/accelerator_output_gate_vector.sv
touch code/nn/lstm/standard/accelerator_state_gate_vector.sv
touch code/nn/ntm/memory/accelerator_addressing.sv
touch code/nn/ntm/memory/accelerator_content_based_addressing.sv
touch code/nn/ntm/read_heads/accelerator_reading.sv
touch code/nn/ntm/top/accelerator_interface_vector.sv
touch code/nn/ntm/top/accelerator_output_vector.sv
touch code/nn/ntm/top/accelerator_top.sv
touch code/nn/ntm/write_heads/accelerator_erasing.sv
touch code/nn/ntm/write_heads/accelerator_writing.sv
touch code/pkg/accelerator_ann_controller_verilog_pkg.sv
touch code/pkg/accelerator_arithmetic_verilog_pkg.sv
touch code/pkg/accelerator_core_verilog_pkg.sv
touch code/pkg/accelerator_fnn_controller_verilog_pkg.sv
touch code/pkg/accelerator_lstm_controller_verilog_pkg.sv
touch code/pkg/accelerator_math_verilog_pkg.sv
touch code/pkg/accelerator_pnn_controller_verilog_pkg.sv
touch code/pkg/accelerator_state_verilog_pkg.sv
touch code/trainer/differentiation/accelerator_trainer_matrix_differentiation.sv
touch code/trainer/differentiation/accelerator_trainer_vector_differentiation.sv
touch code/trainer/fnn/accelerator_trainer.sv
touch code/trainer/lstm/accelerator_activation_trainer.sv
touch code/trainer/lstm/accelerator_forget_trainer.sv
touch code/trainer/lstm/accelerator_input_trainer.sv
touch code/trainer/lstm/accelerator_output_trainer.sv
touch code/trainer/pnn/accelerator_trainer.sv
