touch code/baremetal/design/arithmetic/float/ntm_float_pkg.sv
touch code/baremetal/design/arithmetic/float/ntm_float_stimulus.sv
touch code/baremetal/design/arithmetic/float/ntm_float_testbench.sv
touch code/baremetal/design/arithmetic/integer/ntm_integer_pkg.sv
touch code/baremetal/design/arithmetic/integer/ntm_integer_stimulus.sv
touch code/baremetal/design/arithmetic/integer/ntm_integer_testbench.sv
touch code/baremetal/design/arithmetic/modular/ntm_modular_pkg.sv
touch code/baremetal/design/arithmetic/modular/ntm_modular_stimulus.sv
touch code/baremetal/design/arithmetic/modular/ntm_modular_testbench.sv
touch code/baremetal/design/controller/FNN/convolutional/ntm_convolutional_fnn_pkg.sv
touch code/baremetal/design/controller/FNN/convolutional/ntm_convolutional_fnn_stimulus.sv
touch code/baremetal/design/controller/FNN/convolutional/ntm_convolutional_fnn_testbench.sv
touch code/baremetal/design/controller/FNN/standard/ntm_standard_fnn_pkg.sv
touch code/baremetal/design/controller/FNN/standard/ntm_standard_fnn_stimulus.sv
touch code/baremetal/design/controller/FNN/standard/ntm_standard_fnn_testbench.sv
touch code/baremetal/design/controller/LSTM/convolutional/ntm_convolutional_lstm_pkg.sv
touch code/baremetal/design/controller/LSTM/convolutional/ntm_convolutional_lstm_stimulus.sv
touch code/baremetal/design/controller/LSTM/convolutional/ntm_convolutional_lstm_testbench.sv
touch code/baremetal/design/controller/LSTM/standard/ntm_standard_lstm_pkg.sv
touch code/baremetal/design/controller/LSTM/standard/ntm_standard_lstm_stimulus.sv
touch code/baremetal/design/controller/LSTM/standard/ntm_standard_lstm_testbench.sv
touch code/baremetal/design/controller/transformer/convolutional/ntm_convolutional_transformer_pkg.sv
touch code/baremetal/design/controller/transformer/convolutional/ntm_convolutional_transformer_stimulus.sv
touch code/baremetal/design/controller/transformer/convolutional/ntm_convolutional_transformer_testbench.sv
touch code/baremetal/design/controller/transformer/standard/ntm_standard_transformer_pkg.sv
touch code/baremetal/design/controller/transformer/standard/ntm_standard_transformer_stimulus.sv
touch code/baremetal/design/controller/transformer/standard/ntm_standard_transformer_testbench.sv
touch code/baremetal/design/dnc/memory/dnc_memory_pkg.sv
touch code/baremetal/design/dnc/memory/dnc_memory_stimulus.sv
touch code/baremetal/design/dnc/memory/dnc_memory_testbench.sv
touch code/baremetal/design/dnc/read_heads/dnc_read_heads_pkg.sv
touch code/baremetal/design/dnc/read_heads/dnc_read_heads_stimulus.sv
touch code/baremetal/design/dnc/read_heads/dnc_read_heads_testbench.sv
touch code/baremetal/design/dnc/top/dnc_top_pkg.sv
touch code/baremetal/design/dnc/top/dnc_top_stimulus.sv
touch code/baremetal/design/dnc/top/dnc_top_testbench.sv
touch code/baremetal/design/dnc/write_heads/dnc_write_heads_pkg.sv
touch code/baremetal/design/dnc/write_heads/dnc_write_heads_stimulus.sv
touch code/baremetal/design/dnc/write_heads/dnc_write_heads_testbench.sv
touch code/baremetal/design/math/algebra/ntm_algebra_pkg.sv
touch code/baremetal/design/math/algebra/ntm_algebra_stimulus.sv
touch code/baremetal/design/math/algebra/ntm_algebra_testbench.sv
touch code/baremetal/design/math/calculus/ntm_calculus_pkg.sv
touch code/baremetal/design/math/calculus/ntm_calculus_stimulus.sv
touch code/baremetal/design/math/calculus/ntm_calculus_testbench.sv
touch code/baremetal/design/math/function/ntm_function_pkg.sv
touch code/baremetal/design/math/function/ntm_function_stimulus.sv
touch code/baremetal/design/math/function/ntm_function_testbench.sv
touch code/baremetal/design/math/series/ntm_series_pkg.sv
touch code/baremetal/design/math/series/ntm_series_stimulus.sv
touch code/baremetal/design/math/series/ntm_series_testbench.sv
touch code/baremetal/design/ntm/memory/ntm_memory_pkg.sv
touch code/baremetal/design/ntm/memory/ntm_memory_stimulus.sv
touch code/baremetal/design/ntm/memory/ntm_memory_testbench.sv
touch code/baremetal/design/ntm/read_heads/ntm_read_heads_pkg.sv
touch code/baremetal/design/ntm/read_heads/ntm_read_heads_stimulus.sv
touch code/baremetal/design/ntm/read_heads/ntm_read_heads_testbench.sv
touch code/baremetal/design/ntm/top/ntm_top_pkg.sv
touch code/baremetal/design/ntm/top/ntm_top_stimulus.sv
touch code/baremetal/design/ntm/top/ntm_top_testbench.sv
touch code/baremetal/design/ntm/write_heads/ntm_write_heads_pkg.sv
touch code/baremetal/design/ntm/write_heads/ntm_write_heads_stimulus.sv
touch code/baremetal/design/ntm/write_heads/ntm_write_heads_testbench.sv
touch code/baremetal/design/state/feedback/ntm_state_feedback_pkg.sv
touch code/baremetal/design/state/feedback/ntm_state_feedback_stimulus.sv
touch code/baremetal/design/state/feedback/ntm_state_feedback_testbench.sv
touch code/baremetal/design/state/outputs/ntm_state_outputs_pkg.sv
touch code/baremetal/design/state/outputs/ntm_state_outputs_stimulus.sv
touch code/baremetal/design/state/outputs/ntm_state_outputs_testbench.sv
touch code/baremetal/design/state/top/ntm_state_top_pkg.sv
touch code/baremetal/design/state/top/ntm_state_top_stimulus.sv
touch code/baremetal/design/state/top/ntm_state_top_testbench.sv
touch code/baremetal/design/trainer/FNN/ntm_trainer_fnn_pkg.sv
touch code/baremetal/design/trainer/FNN/ntm_trainer_fnn_stimulus.sv
touch code/baremetal/design/trainer/FNN/ntm_trainer_fnn_testbench.sv
touch code/baremetal/design/trainer/LSTM/ntm_trainer_lstm_pkg.sv
touch code/baremetal/design/trainer/LSTM/ntm_trainer_lstm_stimulus.sv
touch code/baremetal/design/trainer/LSTM/ntm_trainer_lstm_testbench.sv
touch code/baremetal/model/arithmetic/float/model_float_pkg.sv
touch code/baremetal/model/arithmetic/float/model_float_stimulus.sv
touch code/baremetal/model/arithmetic/float/model_float_testbench.sv
touch code/baremetal/model/arithmetic/integer/model_integer_pkg.sv
touch code/baremetal/model/arithmetic/integer/model_integer_stimulus.sv
touch code/baremetal/model/arithmetic/integer/model_integer_testbench.sv
touch code/baremetal/model/arithmetic/modular/model_modular_pkg.sv
touch code/baremetal/model/arithmetic/modular/model_modular_stimulus.sv
touch code/baremetal/model/arithmetic/modular/model_modular_testbench.sv
touch code/baremetal/model/controller/FNN/convolutional/model_convolutional_fnn_pkg.sv
touch code/baremetal/model/controller/FNN/convolutional/model_convolutional_fnn_stimulus.sv
touch code/baremetal/model/controller/FNN/convolutional/model_convolutional_fnn_testbench.sv
touch code/baremetal/model/controller/FNN/standard/model_standard_fnn_pkg.sv
touch code/baremetal/model/controller/FNN/standard/model_standard_fnn_stimulus.sv
touch code/baremetal/model/controller/FNN/standard/model_standard_fnn_testbench.sv
touch code/baremetal/model/controller/LSTM/convolutional/model_convolutional_lstm_pkg.sv
touch code/baremetal/model/controller/LSTM/convolutional/model_convolutional_lstm_stimulus.sv
touch code/baremetal/model/controller/LSTM/convolutional/model_convolutional_lstm_testbench.sv
touch code/baremetal/model/controller/LSTM/standard/model_standard_lstm_pkg.sv
touch code/baremetal/model/controller/LSTM/standard/model_standard_lstm_stimulus.sv
touch code/baremetal/model/controller/LSTM/standard/model_standard_lstm_testbench.sv
touch code/baremetal/model/controller/transformer/convolutional/model_convolutional_transformer_pkg.sv
touch code/baremetal/model/controller/transformer/convolutional/model_convolutional_transformer_stimulus.sv
touch code/baremetal/model/controller/transformer/convolutional/model_convolutional_transformer_testbench.sv
touch code/baremetal/model/controller/transformer/standard/model_standard_transformer_pkg.sv
touch code/baremetal/model/controller/transformer/standard/model_standard_transformer_stimulus.sv
touch code/baremetal/model/controller/transformer/standard/model_standard_transformer_testbench.sv
touch code/baremetal/model/dnc/memory/model_memory_pkg.sv
touch code/baremetal/model/dnc/memory/model_memory_stimulus.sv
touch code/baremetal/model/dnc/memory/model_memory_testbench.sv
touch code/baremetal/model/dnc/read_heads/model_read_heads_pkg.sv
touch code/baremetal/model/dnc/read_heads/model_read_heads_stimulus.sv
touch code/baremetal/model/dnc/read_heads/model_read_heads_testbench.sv
touch code/baremetal/model/dnc/top/model_top_pkg.sv
touch code/baremetal/model/dnc/top/model_top_stimulus.sv
touch code/baremetal/model/dnc/top/model_top_testbench.sv
touch code/baremetal/model/dnc/write_heads/model_write_heads_pkg.sv
touch code/baremetal/model/dnc/write_heads/model_write_heads_stimulus.sv
touch code/baremetal/model/dnc/write_heads/model_write_heads_testbench.sv
touch code/baremetal/model/math/algebra/model_algebra_pkg.sv
touch code/baremetal/model/math/algebra/model_algebra_stimulus.sv
touch code/baremetal/model/math/algebra/model_algebra_testbench.sv
touch code/baremetal/model/math/calculus/model_calculus_pkg.sv
touch code/baremetal/model/math/calculus/model_calculus_stimulus.sv
touch code/baremetal/model/math/calculus/model_calculus_testbench.sv
touch code/baremetal/model/math/function/model_function_pkg.sv
touch code/baremetal/model/math/function/model_function_stimulus.sv
touch code/baremetal/model/math/function/model_function_testbench.sv
touch code/baremetal/model/math/series/model_series_pkg.sv
touch code/baremetal/model/math/series/model_series_stimulus.sv
touch code/baremetal/model/math/series/model_series_testbench.sv
touch code/baremetal/model/ntm/memory/model_memory_pkg.sv
touch code/baremetal/model/ntm/memory/model_memory_stimulus.sv
touch code/baremetal/model/ntm/memory/model_memory_testbench.sv
touch code/baremetal/model/ntm/read_heads/model_read_heads_pkg.sv
touch code/baremetal/model/ntm/read_heads/model_read_heads_stimulus.sv
touch code/baremetal/model/ntm/read_heads/model_read_heads_testbench.sv
touch code/baremetal/model/ntm/top/model_top_pkg.sv
touch code/baremetal/model/ntm/top/model_top_stimulus.sv
touch code/baremetal/model/ntm/top/model_top_testbench.sv
touch code/baremetal/model/ntm/write_heads/model_write_heads_pkg.sv
touch code/baremetal/model/ntm/write_heads/model_write_heads_stimulus.sv
touch code/baremetal/model/ntm/write_heads/model_write_heads_testbench.sv
touch code/baremetal/model/state/feedback/model_state_feedback_pkg.sv
touch code/baremetal/model/state/feedback/model_state_feedback_stimulus.sv
touch code/baremetal/model/state/feedback/model_state_feedback_testbench.sv
touch code/baremetal/model/state/outputs/model_state_outputs_pkg.sv
touch code/baremetal/model/state/outputs/model_state_outputs_stimulus.sv
touch code/baremetal/model/state/outputs/model_state_outputs_testbench.sv
touch code/baremetal/model/state/top/model_state_top_pkg.sv
touch code/baremetal/model/state/top/model_state_top_stimulus.sv
touch code/baremetal/model/state/top/model_state_top_testbench.sv
touch code/baremetal/model/trainer/FNN/model_trainer_fnn_pkg.sv
touch code/baremetal/model/trainer/FNN/model_trainer_fnn_stimulus.sv
touch code/baremetal/model/trainer/FNN/model_trainer_fnn_testbench.sv
touch code/baremetal/model/trainer/LSTM/model_trainer_lstm_pkg.sv
touch code/baremetal/model/trainer/LSTM/model_trainer_lstm_stimulus.sv
touch code/baremetal/model/trainer/LSTM/model_trainer_lstm_testbench.sv
