touch library/algebra/matrix/accelerator_matrix_algebra.scala
touch library/algebra/scalar/accelerator_scalar_algebra.scala
touch library/algebra/tensor/accelerator_tensor_algebra.scala
touch library/algebra/vector/accelerator_vector_algebra.scala
touch library/arithmetic/matrix/accelerator_matrix_arithmetic.scala
touch library/arithmetic/scalar/accelerator_scalar_arithmetic.scala
touch library/arithmetic/tensor/accelerator_tensor_arithmetic.scala
touch library/arithmetic/vector/accelerator_vector_arithmetic.scala
touch library/math/matrix/accelerator_matrix_math.scala
touch library/math/scalar/accelerator_scalar_math.scala
touch library/math/vector/accelerator_vector_math.scala
touch library/nn/ann/components/accelerator_masked_multi_head_attention.scala
touch library/nn/ann/components/accelerator_masked_scaled_dot_product_attention.scala
touch library/nn/ann/components/accelerator_multi_head_attention.scala
touch library/nn/ann/components/accelerator_scaled_dot_product_attention.scala
touch library/nn/ann/controller/fnn/accelerator_fnn.scala
touch library/nn/ann/controller/lstm/accelerator_lstm.scala
touch library/nn/ann/functions/accelerator_layer_norm.scala
touch library/nn/ann/functions/accelerator_positional_encoding.scala
touch library/nn/ann/inputs/accelerator_inputs_vector.scala
touch library/nn/ann/inputs/accelerator_keys_vector.scala
touch library/nn/ann/inputs/accelerator_queries_vector.scala
touch library/nn/ann/inputs/accelerator_values_vector.scala
touch library/nn/ann/top/accelerator_controller.scala
touch library/nn/ann/top/accelerator_decoder.scala
touch library/nn/ann/top/accelerator_encoder.scala
touch library/nn/dnc/memory/accelerator_addressing.scala
touch library/nn/dnc/memory/accelerator_allocation_weighting.scala
touch library/nn/dnc/memory/accelerator_backward_weighting.scala
touch library/nn/dnc/memory/accelerator_forward_weighting.scala
touch library/nn/dnc/memory/accelerator_matrix_content_based_addressing.scala
touch library/nn/dnc/memory/accelerator_memory_matrix.scala
touch library/nn/dnc/memory/accelerator_memory_retention_vector.scala
touch library/nn/dnc/memory/accelerator_precedence_weighting.scala
touch library/nn/dnc/memory/accelerator_sort_vector.scala
touch library/nn/dnc/memory/accelerator_temporal_link_matrix.scala
touch library/nn/dnc/memory/accelerator_usage_vector.scala
touch library/nn/dnc/memory/accelerator_vector_content_based_addressing.scala
touch library/nn/dnc/read_heads/accelerator_read_content_weighting.scala
touch library/nn/dnc/read_heads/accelerator_read_vectors.scala
touch library/nn/dnc/read_heads/accelerator_read_weighting.scala
touch library/nn/dnc/top/accelerator_interface_matrix.scala
touch library/nn/dnc/top/accelerator_interface_top.scala
touch library/nn/dnc/top/accelerator_interface_vector.scala
touch library/nn/dnc/top/accelerator_output_vector.scala
touch library/nn/dnc/top/accelerator_top.scala
touch library/nn/dnc/trained/accelerator_trained_top.scala
touch library/nn/dnc/write_heads/accelerator_write_content_weighting.scala
touch library/nn/dnc/write_heads/accelerator_write_weighting.scala
touch library/nn/fnn/convolutional/accelerator_controller.scala
touch library/nn/fnn/standard/accelerator_controller.scala
touch library/nn/lstm/convolutional/accelerator_activation_gate_vector.scala
touch library/nn/lstm/convolutional/accelerator_controller.scala
touch library/nn/lstm/convolutional/accelerator_forget_gate_vector.scala
touch library/nn/lstm/convolutional/accelerator_hidden_gate_vector.scala
touch library/nn/lstm/convolutional/accelerator_input_gate_vector.scala
touch library/nn/lstm/convolutional/accelerator_output_gate_vector.scala
touch library/nn/lstm/convolutional/accelerator_state_gate_vector.scala
touch library/nn/lstm/standard/accelerator_activation_gate_vector.scala
touch library/nn/lstm/standard/accelerator_controller.scala
touch library/nn/lstm/standard/accelerator_forget_gate_vector.scala
touch library/nn/lstm/standard/accelerator_hidden_gate_vector.scala
touch library/nn/lstm/standard/accelerator_input_gate_vector.scala
touch library/nn/lstm/standard/accelerator_output_gate_vector.scala
touch library/nn/lstm/standard/accelerator_state_gate_vector.scala
touch library/nn/ntm/memory/accelerator_addressing.scala
touch library/nn/ntm/memory/accelerator_matrix_content_based_addressing.scala
touch library/nn/ntm/memory/accelerator_vector_content_based_addressing.scala
touch library/nn/ntm/read_heads/accelerator_reading.scala
touch library/nn/ntm/top/accelerator_interface_matrix.scala
touch library/nn/ntm/top/accelerator_interface_top.scala
touch library/nn/ntm/top/accelerator_interface_vector.scala
touch library/nn/ntm/top/accelerator_output_vector.scala
touch library/nn/ntm/top/accelerator_top.scala
touch library/nn/ntm/trained/accelerator_trained_top.scala
touch library/nn/ntm/write_heads/accelerator_erasing.scala
touch library/nn/ntm/write_heads/accelerator_writing.scala
touch library/trainer/differentiation/accelerator_matrix_controller_differentiation.scala
touch library/trainer/differentiation/accelerator_vector_controller_differentiation.scala
touch library/trainer/fnn/accelerator_fnn_b_trainer.scala
touch library/trainer/fnn/accelerator_fnn_d_trainer.scala
touch library/trainer/fnn/accelerator_fnn_k_trainer.scala
touch library/trainer/fnn/accelerator_fnn_trainer.scala
touch library/trainer/fnn/accelerator_fnn_u_trainer.scala
touch library/trainer/fnn/accelerator_fnn_v_trainer.scala
touch library/trainer/fnn/accelerator_fnn_w_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_b_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_d_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_k_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_u_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_v_trainer.scala
touch library/trainer/lstm/activation/accelerator_lstm_activation_w_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_b_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_d_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_k_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_u_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_v_trainer.scala
touch library/trainer/lstm/forget/accelerator_lstm_forget_w_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_b_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_d_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_k_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_u_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_v_trainer.scala
touch library/trainer/lstm/input/accelerator_lstm_input_w_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_b_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_d_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_k_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_u_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_v_trainer.scala
touch library/trainer/lstm/output/accelerator_lstm_output_w_trainer.scala
