emacs -batch vhdl/quantum/classes/philosophers/ntm_philosophers.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/classes/soldiers/ntm_soldiers.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/classes/workers/ntm_workers.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/processing_unit/mimd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/processing_unit/misd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/processing_unit/simd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/processing_unit/sisd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/system_on_chip/bus_on_chip.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/advanced_computer_architecture/system_on_chip/network_on_chip.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/harvard_architecture/alu.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/harvard_architecture/control_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/harvard_architecture/io_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/harvard_architecture/memory_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/von_neumann_architecture/alu.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/von_neumann_architecture/control_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/von_neumann_architecture/io_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/computer_architecture/von_neumann_architecture/memory_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/bit/bit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/combinational_logic/arithmetic_circuits.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/combinational_logic/logic_circuits.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/finite_state_machine/finite_state_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/and_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/nand_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/nor_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/not_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/or_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/xnor_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/xor_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/logic_gate/yes_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/information/pushdown_automaton/pushdown_automaton.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/neural_network/feedforward_neural_network/feedforward_neural_network.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/neural_network/transformer_neural_network/transformer_neural_network.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/classes/ntm_philosophers_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/classes/ntm_soldiers_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/classes/ntm_workers_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/computing/state_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/ieee/math_complex-body.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/ieee/math_complex.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/ieee/math_real-body.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/quantum/pkg/ieee/math_real.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/classes/philosophers/ntm_philosophers.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/classes/soldiers/ntm_soldiers.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/classes/workers/ntm_workers.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_multi_processor_system_on_chip/traditional_multi_processor_system_on_chip.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_processing_unit/traditional_mimd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_processing_unit/traditional_misd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_processing_unit/traditional_simd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_processing_unit/traditional_sisd.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_system_on_chip/traditional_bus_on_chip.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_advanced_computer_architecture/traditional_system_on_chip/traditional_network_on_chip.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_harvard_architecture/traditional_alu.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_harvard_architecture/traditional_control_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_harvard_architecture/traditional_io_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_harvard_architecture/traditional_memory_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_von_neumann_architecture/traditional_alu.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_von_neumann_architecture/traditional_control_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_von_neumann_architecture/traditional_io_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_computer_architecture/traditional_von_neumann_architecture/traditional_memory_unit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_bit/traditional_bit.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_combinational_logic/traditional_arithmetic_circuits.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_combinational_logic/traditional_logic_circuits.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_finite_state_machine/traditional_finite_state_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_and_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_nand_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_nor_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_not_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_or_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_xnor_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_xor_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_logic_gate/traditional_yes_gate.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_information/traditional_pushdown_automaton/traditional_pushdown_automaton.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_neural_network/traditional_feedforward_neural_network/traditional_feedforward_neural_network.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_neural_network/traditional_long_short_term_memory_neural_network/traditional_long_short_term_memory_neural_network.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_neural_network/traditional_transformer_neural_network/traditional_transformer_neural_network.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_turing_machine/traditional_differentiable_neural_computer/traditional_feedforward_differentiable_neural_computer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_turing_machine/traditional_differentiable_neural_computer/traditional_lstm_differentiable_neural_computer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_turing_machine/traditional_differentiable_neural_computer/traditional_transformer_differentiable_neural_computer.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_turing_machine/traditional_neural_turing_machine/traditional_feedforward_neural_turing_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_turing_machine/traditional_neural_turing_machine/traditional_lstm_neural_turing_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/computing/traditional_turing_machine/traditional_neural_turing_machine/traditional_transformer_neural_turing_machine.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/classes/ntm_philosophers_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/classes/ntm_soldiers_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/classes/ntm_workers_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/computing/traditional_state_pkg.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/ieee/math_complex-body.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/ieee/math_complex.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/ieee/math_real-body.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/traditional/pkg/ieee/math_real.vhd -f vhdl-beautify-buffer -f save-buffer

