touch code/arithmetic/float/matrix/ntm_matrix_float_adder.vhd
touch code/arithmetic/float/matrix/ntm_matrix_float_divider.vhd
touch code/arithmetic/float/matrix/ntm_matrix_float_multiplier.vhd
touch code/arithmetic/float/scalar/ntm_scalar_float_adder.vhd
touch code/arithmetic/float/scalar/ntm_scalar_float_divider.vhd
touch code/arithmetic/float/scalar/ntm_scalar_float_multiplier.vhd
touch code/arithmetic/float/tensor/ntm_tensor_float_adder.vhd
touch code/arithmetic/float/tensor/ntm_tensor_float_divider.vhd
touch code/arithmetic/float/tensor/ntm_tensor_float_multiplier.vhd
touch code/arithmetic/float/vector/ntm_vector_float_adder.vhd
touch code/arithmetic/float/vector/ntm_vector_float_divider.vhd
touch code/arithmetic/float/vector/ntm_vector_float_multiplier.vhd
touch code/arithmetic/integer/matrix/ntm_matrix_integer_adder.vhd
touch code/arithmetic/integer/matrix/ntm_matrix_integer_divider.vhd
touch code/arithmetic/integer/matrix/ntm_matrix_integer_multiplier.vhd
touch code/arithmetic/integer/scalar/ntm_scalar_integer_adder.vhd
touch code/arithmetic/integer/scalar/ntm_scalar_integer_divider.vhd
touch code/arithmetic/integer/scalar/ntm_scalar_integer_multiplier.vhd
touch code/arithmetic/integer/tensor/ntm_tensor_integer_adder.vhd
touch code/arithmetic/integer/tensor/ntm_tensor_integer_divider.vhd
touch code/arithmetic/integer/tensor/ntm_tensor_integer_multiplier.vhd
touch code/arithmetic/integer/vector/ntm_vector_integer_adder.vhd
touch code/arithmetic/integer/vector/ntm_vector_integer_divider.vhd
touch code/arithmetic/integer/vector/ntm_vector_integer_multiplier.vhd
touch code/arithmetic/modular/matrix/ntm_matrix_modular_adder.vhd
touch code/arithmetic/modular/matrix/ntm_matrix_modular_inverter.vhd
touch code/arithmetic/modular/matrix/ntm_matrix_modular_mod.vhd
touch code/arithmetic/modular/matrix/ntm_matrix_modular_multiplier.vhd
touch code/arithmetic/modular/scalar/ntm_scalar_modular_adder.vhd
touch code/arithmetic/modular/scalar/ntm_scalar_modular_inverter.vhd
touch code/arithmetic/modular/scalar/ntm_scalar_modular_mod.vhd
touch code/arithmetic/modular/scalar/ntm_scalar_modular_multiplier.vhd
touch code/arithmetic/modular/tensor/ntm_tensor_modular_adder.vhd
touch code/arithmetic/modular/tensor/ntm_tensor_modular_inverter.vhd
touch code/arithmetic/modular/tensor/ntm_tensor_modular_mod.vhd
touch code/arithmetic/modular/tensor/ntm_tensor_modular_multiplier.vhd
touch code/arithmetic/modular/vector/ntm_vector_modular_adder.vhd
touch code/arithmetic/modular/vector/ntm_vector_modular_inverter.vhd
touch code/arithmetic/modular/vector/ntm_vector_modular_mod.vhd
touch code/arithmetic/modular/vector/ntm_vector_modular_multiplier.vhd
touch code/controller/FNN/convolutional/ntm_controller.vhd
touch code/controller/FNN/standard/ntm_controller.vhd
touch code/controller/LSTM/convolutional/ntm_activation_gate_vector.vhd
touch code/controller/LSTM/convolutional/ntm_controller.vhd
touch code/controller/LSTM/convolutional/ntm_forget_gate_vector.vhd
touch code/controller/LSTM/convolutional/ntm_hidden_gate_vector.vhd
touch code/controller/LSTM/convolutional/ntm_input_gate_vector.vhd
touch code/controller/LSTM/convolutional/ntm_output_gate_vector.vhd
touch code/controller/LSTM/convolutional/ntm_state_gate_vector.vhd
touch code/controller/LSTM/standard/ntm_activation_gate_vector.vhd
touch code/controller/LSTM/standard/ntm_controller.vhd
touch code/controller/LSTM/standard/ntm_forget_gate_vector.vhd
touch code/controller/LSTM/standard/ntm_hidden_gate_vector.vhd
touch code/controller/LSTM/standard/ntm_input_gate_vector.vhd
touch code/controller/LSTM/standard/ntm_output_gate_vector.vhd
touch code/controller/LSTM/standard/ntm_state_gate_vector.vhd
touch code/controller/transformer/components/ntm_masked_multi_head_attention.vhd
touch code/controller/transformer/components/ntm_masked_scaled_dot_product_attention.vhd
touch code/controller/transformer/components/ntm_multi_head_attention.vhd
touch code/controller/transformer/components/ntm_scaled_dot_product_attention.vhd
touch code/controller/transformer/fnn/ntm_fnn.vhd
touch code/controller/transformer/functions/ntm_layer_norm.vhd
touch code/controller/transformer/functions/ntm_positional_encoding.vhd
touch code/controller/transformer/inputs/ntm_inputs_vector.vhd
touch code/controller/transformer/inputs/ntm_keys_vector.vhd
touch code/controller/transformer/inputs/ntm_queries_vector.vhd
touch code/controller/transformer/inputs/ntm_values_vector.vhd
touch code/controller/transformer/lstm/ntm_activation_gate_vector.vhd
touch code/controller/transformer/lstm/ntm_forget_gate_vector.vhd
touch code/controller/transformer/lstm/ntm_hidden_gate_vector.vhd
touch code/controller/transformer/lstm/ntm_input_gate_vector.vhd
touch code/controller/transformer/lstm/ntm_lstm.vhd
touch code/controller/transformer/lstm/ntm_output_gate_vector.vhd
touch code/controller/transformer/lstm/ntm_state_gate_vector.vhd
touch code/controller/transformer/top/ntm_controller.vhd
touch code/controller/transformer/top/ntm_decoder.vhd
touch code/controller/transformer/top/ntm_encoder.vhd
touch code/dnc/memory/dnc_addressing.vhd
touch code/dnc/memory/dnc_allocation_weighting.vhd
touch code/dnc/memory/dnc_backward_weighting.vhd
touch code/dnc/memory/dnc_content_based_addressing.vhd
touch code/dnc/memory/dnc_forward_weighting.vhd
touch code/dnc/memory/dnc_memory_matrix.vhd
touch code/dnc/memory/dnc_memory_retention_vector.vhd
touch code/dnc/memory/dnc_precedence_weighting.vhd
touch code/dnc/memory/dnc_read_content_weighting.vhd
touch code/dnc/memory/dnc_read_vectors.vhd
touch code/dnc/memory/dnc_read_weighting.vhd
touch code/dnc/memory/dnc_sort_vector.vhd
touch code/dnc/memory/dnc_temporal_link_matrix.vhd
touch code/dnc/memory/dnc_usage_vector.vhd
touch code/dnc/memory/dnc_write_content_weighting.vhd
touch code/dnc/memory/dnc_write_weighting.vhd
touch code/dnc/read_heads/dnc_read_heads.vhd
touch code/dnc/top/dnc_interface_matrix.vhd
touch code/dnc/top/dnc_interface_vector.vhd
touch code/dnc/top/dnc_output_vector.vhd
touch code/dnc/top/dnc_top.vhd
touch code/dnc/write_heads/dnc_write_heads.vhd
touch code/intro/ntm_intro_adder.vhd
touch code/math/algebra/matrix/ntm_matrix_convolution.vhd
touch code/math/algebra/matrix/ntm_matrix_inverse.vhd
touch code/math/algebra/matrix/ntm_matrix_multiplication.vhd
touch code/math/algebra/matrix/ntm_matrix_product.vhd
touch code/math/algebra/matrix/ntm_matrix_summation.vhd
touch code/math/algebra/matrix/ntm_matrix_transpose.vhd
touch code/math/algebra/matrix/ntm_matrix_vector_convolution.vhd
touch code/math/algebra/matrix/ntm_matrix_vector_product.vhd
touch code/math/algebra/matrix/ntm_transpose_vector_product.vhd
touch code/math/algebra/tensor/ntm_tensor_convolution.vhd
touch code/math/algebra/tensor/ntm_tensor_inverse.vhd
touch code/math/algebra/tensor/ntm_tensor_matrix_convolution.vhd
touch code/math/algebra/tensor/ntm_tensor_matrix_product.vhd
touch code/math/algebra/tensor/ntm_tensor_multiplication.vhd
touch code/math/algebra/tensor/ntm_tensor_product.vhd
touch code/math/algebra/tensor/ntm_tensor_summation.vhd
touch code/math/algebra/tensor/ntm_tensor_transpose.vhd
touch code/math/algebra/vector/ntm_dot_product.vhd
touch code/math/algebra/vector/ntm_vector_convolution.vhd
touch code/math/algebra/vector/ntm_vector_cosine_similarity.vhd
touch code/math/algebra/vector/ntm_vector_module.vhd
touch code/math/algebra/vector/ntm_vector_multiplication.vhd
touch code/math/algebra/vector/ntm_vector_summation.vhd
touch code/math/calculus/matrix/ntm_matrix_differentiation.vhd
touch code/math/calculus/matrix/ntm_matrix_integration.vhd
touch code/math/calculus/matrix/ntm_matrix_softmax.vhd
touch code/math/calculus/tensor/ntm_tensor_differentiation.vhd
touch code/math/calculus/tensor/ntm_tensor_integration.vhd
touch code/math/calculus/tensor/ntm_tensor_softmax.vhd
touch code/math/calculus/vector/ntm_vector_differentiation.vhd
touch code/math/calculus/vector/ntm_vector_integration.vhd
touch code/math/calculus/vector/ntm_vector_softmax.vhd
touch code/math/function/matrix/ntm_matrix_logistic_function.vhd
touch code/math/function/matrix/ntm_matrix_oneplus_function.vhd
touch code/math/function/scalar/ntm_scalar_logistic_function.vhd
touch code/math/function/scalar/ntm_scalar_oneplus_function.vhd
touch code/math/function/vector/ntm_vector_logistic_function.vhd
touch code/math/function/vector/ntm_vector_oneplus_function.vhd
touch code/math/series/matrix/ntm_matrix_cosh_function.vhd
touch code/math/series/matrix/ntm_matrix_exponentiator_function.vhd
touch code/math/series/matrix/ntm_matrix_logarithm_function.vhd
touch code/math/series/matrix/ntm_matrix_power_function.vhd
touch code/math/series/matrix/ntm_matrix_sinh_function.vhd
touch code/math/series/matrix/ntm_matrix_sqrt_function.vhd
touch code/math/series/matrix/ntm_matrix_tanh_function.vhd
touch code/math/series/scalar/ntm_scalar_cosh_function.vhd
touch code/math/series/scalar/ntm_scalar_exponentiator_function.vhd
touch code/math/series/scalar/ntm_scalar_logarithm_function.vhd
touch code/math/series/scalar/ntm_scalar_power_function.vhd
touch code/math/series/scalar/ntm_scalar_sinh_function.vhd
touch code/math/series/scalar/ntm_scalar_sqrt_function.vhd
touch code/math/series/scalar/ntm_scalar_tanh_function.vhd
touch code/math/series/vector/ntm_vector_cosh_function.vhd
touch code/math/series/vector/ntm_vector_exponentiator_function.vhd
touch code/math/series/vector/ntm_vector_logarithm_function.vhd
touch code/math/series/vector/ntm_vector_power_function.vhd
touch code/math/series/vector/ntm_vector_sinh_function.vhd
touch code/math/series/vector/ntm_vector_sqrt_function.vhd
touch code/math/series/vector/ntm_vector_tanh_function.vhd
touch code/ntm/memory/ntm_addressing.vhd
touch code/ntm/memory/ntm_content_based_addressing.vhd
touch code/ntm/read_heads/ntm_reading.vhd
touch code/ntm/top/ntm_interface_matrix.vhd
touch code/ntm/top/ntm_interface_vector.vhd
touch code/ntm/top/ntm_output_vector.vhd
touch code/ntm/top/ntm_top.vhd
touch code/ntm/write_heads/ntm_erasing.vhd
touch code/ntm/write_heads/ntm_writing.vhd
touch code/pkg/dnc_core_pkg.vhd
touch code/pkg/ntm_arithmetic_pkg.vhd
touch code/pkg/ntm_core_pkg.vhd
touch code/pkg/ntm_fnn_controller_pkg.vhd
touch code/pkg/ntm_intro_pkg.vhd
touch code/pkg/ntm_lstm_controller_pkg.vhd
touch code/pkg/ntm_math_pkg.vhd
touch code/pkg/ntm_state_pkg.vhd
touch code/state/feedback/ntm_state_matrix_feedforward.vhd
touch code/state/feedback/ntm_state_matrix_input.vhd
touch code/state/feedback/ntm_state_matrix_output.vhd
touch code/state/feedback/ntm_state_matrix_state.vhd
touch code/state/outputs/ntm_state_vector_output.vhd
touch code/state/outputs/ntm_state_vector_state.vhd
touch code/state/top/ntm_state_top.vhd
touch code/trainer/differentiation/model_matrix_controller_differentiation.vhd
touch code/trainer/differentiation/model_vector_controller_differentiation.vhd
touch code/trainer/FNN/ntm_trainer.vhd
touch code/trainer/LSTM/ntm_activation_trainer.vhd
touch code/trainer/LSTM/ntm_forget_trainer.vhd
touch code/trainer/LSTM/ntm_input_trainer.vhd
touch code/trainer/LSTM/ntm_output_trainer.vhd
