touch code/architecture/mpsoc/model_mpsoc.vhd
touch code/architecture/pu/model_pu.vhd
touch code/architecture/soc/model_soc.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_adder.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_divider.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_multiplier.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_adder.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_divider.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_multiplier.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_adder.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_divider.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_multiplier.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_adder.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_divider.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_multiplier.vhd
touch code/arithmetic/float/matrix/model_matrix_float_adder.vhd
touch code/arithmetic/float/matrix/model_matrix_float_divider.vhd
touch code/arithmetic/float/matrix/model_matrix_float_multiplier.vhd
touch code/arithmetic/float/scalar/model_scalar_float_adder.vhd
touch code/arithmetic/float/scalar/model_scalar_float_divider.vhd
touch code/arithmetic/float/scalar/model_scalar_float_multiplier.vhd
touch code/arithmetic/float/tensor/model_tensor_float_adder.vhd
touch code/arithmetic/float/tensor/model_tensor_float_divider.vhd
touch code/arithmetic/float/tensor/model_tensor_float_multiplier.vhd
touch code/arithmetic/float/vector/model_vector_float_adder.vhd
touch code/arithmetic/float/vector/model_vector_float_divider.vhd
touch code/arithmetic/float/vector/model_vector_float_multiplier.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_adder.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_divider.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_multiplier.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_adder.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_divider.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_multiplier.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_adder.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_divider.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_multiplier.vhd
touch code/arithmetic/integer/vector/model_vector_integer_adder.vhd
touch code/arithmetic/integer/vector/model_vector_integer_divider.vhd
touch code/arithmetic/integer/vector/model_vector_integer_multiplier.vhd
touch code/controller/FNN/convolutional/model_controller.vhd
touch code/controller/FNN/standard/model_controller.vhd
touch code/controller/LSTM/convolutional/model_activation_gate_vector.vhd
touch code/controller/LSTM/convolutional/model_controller.vhd
touch code/controller/LSTM/convolutional/model_forget_gate_vector.vhd
touch code/controller/LSTM/convolutional/model_hidden_gate_vector.vhd
touch code/controller/LSTM/convolutional/model_input_gate_vector.vhd
touch code/controller/LSTM/convolutional/model_output_gate_vector.vhd
touch code/controller/LSTM/convolutional/model_state_gate_vector.vhd
touch code/controller/LSTM/standard/model_activation_gate_vector.vhd
touch code/controller/LSTM/standard/model_controller.vhd
touch code/controller/LSTM/standard/model_forget_gate_vector.vhd
touch code/controller/LSTM/standard/model_hidden_gate_vector.vhd
touch code/controller/LSTM/standard/model_input_gate_vector.vhd
touch code/controller/LSTM/standard/model_output_gate_vector.vhd
touch code/controller/LSTM/standard/model_state_gate_vector.vhd
touch code/math/algebra/matrix/model_matrix_convolution.vhd
touch code/math/algebra/matrix/model_matrix_inverse.vhd
touch code/math/algebra/matrix/model_matrix_multiplication.vhd
touch code/math/algebra/matrix/model_matrix_product.vhd
touch code/math/algebra/matrix/model_matrix_summation.vhd
touch code/math/algebra/matrix/model_matrix_transpose.vhd
touch code/math/algebra/matrix/model_matrix_vector_convolution.vhd
touch code/math/algebra/matrix/model_matrix_vector_product.vhd
touch code/math/algebra/matrix/model_transpose_vector_product.vhd
touch code/math/algebra/tensor/model_tensor_convolution.vhd
touch code/math/algebra/tensor/model_tensor_inverse.vhd
touch code/math/algebra/tensor/model_tensor_matrix_convolution.vhd
touch code/math/algebra/tensor/model_tensor_matrix_product.vhd
touch code/math/algebra/tensor/model_tensor_product.vhd
touch code/math/algebra/tensor/model_tensor_transpose.vhd
touch code/math/algebra/vector/model_dot_product.vhd
touch code/math/algebra/vector/model_vector_convolution.vhd
touch code/math/algebra/vector/model_vector_cosine_similarity.vhd
touch code/math/algebra/vector/model_vector_module.vhd
touch code/math/algebra/vector/model_vector_multiplication.vhd
touch code/math/algebra/vector/model_vector_summation.vhd
touch code/math/calculus/matrix/model_matrix_differentiation.vhd
touch code/math/calculus/matrix/model_matrix_integration.vhd
touch code/math/calculus/matrix/model_matrix_softmax.vhd
touch code/math/calculus/tensor/model_tensor_differentiation.vhd
touch code/math/calculus/tensor/model_tensor_integration.vhd
touch code/math/calculus/tensor/model_tensor_softmax.vhd
touch code/math/calculus/vector/model_vector_differentiation.vhd
touch code/math/calculus/vector/model_vector_integration.vhd
touch code/math/calculus/vector/model_vector_softmax.vhd
touch code/math/function/matrix/model_matrix_logistic_function.vhd
touch code/math/function/matrix/model_matrix_oneplus_function.vhd
touch code/math/function/scalar/model_scalar_logistic_function.vhd
touch code/math/function/scalar/model_scalar_oneplus_function.vhd
touch code/math/function/vector/model_vector_logistic_function.vhd
touch code/math/function/vector/model_vector_oneplus_function.vhd
touch code/math/series/matrix/model_matrix_cosh_function.vhd
touch code/math/series/matrix/model_matrix_exponentiator_function.vhd
touch code/math/series/matrix/model_matrix_logarithm_function.vhd
touch code/math/series/matrix/model_matrix_sinh_function.vhd
touch code/math/series/matrix/model_matrix_tanh_function.vhd
touch code/math/series/scalar/model_scalar_cosh_function.vhd
touch code/math/series/scalar/model_scalar_exponentiator_function.vhd
touch code/math/series/scalar/model_scalar_logarithm_function.vhd
touch code/math/series/scalar/model_scalar_sinh_function.vhd
touch code/math/series/scalar/model_scalar_tanh_function.vhd
touch code/math/series/vector/model_vector_cosh_function.vhd
touch code/math/series/vector/model_vector_exponentiator_function.vhd
touch code/math/series/vector/model_vector_logarithm_function.vhd
touch code/math/series/vector/model_vector_sinh_function.vhd
touch code/math/series/vector/model_vector_tanh_function.vhd
touch code/ntm/memory/model_addressing.vhd
touch code/ntm/memory/model_content_based_addressing.vhd
touch code/ntm/read_heads/model_reading.vhd
touch code/ntm/top/model_interface_matrix.vhd
touch code/ntm/top/model_interface_vector.vhd
touch code/ntm/top/model_output_vector.vhd
touch code/ntm/top/model_top.vhd
touch code/ntm/write_heads/model_erasing.vhd
touch code/ntm/write_heads/model_writing.vhd
touch code/pkg/model_arithmetic_vhdl_pkg.vhd
touch code/pkg/model_fnn_controller_vhdl_pkg.vhd
touch code/pkg/model_linear_controller_vhdl_pkg.vhd
touch code/pkg/model_lstm_controller_vhdl_pkg.vhd
touch code/pkg/model_math_vhdl_pkg.vhd
touch code/pkg/model_ntm_core_vhdl_pkg.vhd
touch code/pkg/model_state_vhdl_pkg.vhd
touch code/pkg/model_transformer_controller_vhdl_pkg.vhd
touch code/state/feedback/model_state_matrix_feedforward.vhd
touch code/state/feedback/model_state_matrix_input.vhd
touch code/state/feedback/model_state_matrix_output.vhd
touch code/state/feedback/model_state_matrix_state.vhd
touch code/state/linear/convolutional/model_controller.vhd
touch code/state/linear/standard/model_controller.vhd
touch code/state/outputs/model_state_vector_output.vhd
touch code/state/outputs/model_state_vector_state.vhd
touch code/state/top/model_state_top.vhd
touch code/trainer/differentiation/model_trainer_matrix_differentiation.vhd
touch code/trainer/differentiation/model_trainer_vector_differentiation.vhd
touch code/trainer/FNN/model_trainer.vhd
touch code/trainer/linear/model_trainer.vhd
touch code/trainer/LSTM/model_activation_trainer.vhd
touch code/trainer/LSTM/model_forget_trainer.vhd
touch code/trainer/LSTM/model_input_trainer.vhd
touch code/trainer/LSTM/model_output_trainer.vhd
touch code/transformer/components/model_masked_multi_head_attention.vhd
touch code/transformer/components/model_masked_scaled_dot_product_attention.vhd
touch code/transformer/components/model_multi_head_attention.vhd
touch code/transformer/components/model_scaled_dot_product_attention.vhd
touch code/transformer/controller/fnn/convolutional/model_fnn.vhd
touch code/transformer/controller/fnn/standard/model_fnn.vhd
touch code/transformer/controller/lstm/convolutional/model_lstm.vhd
touch code/transformer/controller/lstm/standard/model_lstm.vhd
touch code/transformer/functions/model_layer_norm.vhd
touch code/transformer/functions/model_positional_encoding.vhd
touch code/transformer/inputs/model_inputs_vector.vhd
touch code/transformer/inputs/model_keys_vector.vhd
touch code/transformer/inputs/model_queries_vector.vhd
touch code/transformer/inputs/model_values_vector.vhd
touch code/transformer/top/model_controller.vhd
touch code/transformer/top/model_decoder.vhd
touch code/transformer/top/model_encoder.vhd
