touch code/algebra/matrix/model_matrix_convolution.vhd
touch code/algebra/matrix/model_matrix_differentiation.vhd
touch code/algebra/matrix/model_matrix_integration.vhd
touch code/algebra/matrix/model_matrix_inverse.vhd
touch code/algebra/matrix/model_matrix_multiplication.vhd
touch code/algebra/matrix/model_matrix_product.vhd
touch code/algebra/matrix/model_matrix_softmax.vhd
touch code/algebra/matrix/model_matrix_summation.vhd
touch code/algebra/matrix/model_matrix_transpose.vhd
touch code/algebra/matrix/model_matrix_vector_convolution.vhd
touch code/algebra/matrix/model_matrix_vector_product.vhd
touch code/algebra/matrix/model_transpose_vector_product.vhd
touch code/algebra/tensor/model_tensor_convolution.vhd
touch code/algebra/tensor/model_tensor_differentiation.vhd
touch code/algebra/tensor/model_tensor_integration.vhd
touch code/algebra/tensor/model_tensor_inverse.vhd
touch code/algebra/tensor/model_tensor_matrix_convolution.vhd
touch code/algebra/tensor/model_tensor_matrix_product.vhd
touch code/algebra/tensor/model_tensor_product.vhd
touch code/algebra/tensor/model_tensor_softmax.vhd
touch code/algebra/tensor/model_tensor_transpose.vhd
touch code/algebra/vector/model_dot_product.vhd
touch code/algebra/vector/model_vector_convolution.vhd
touch code/algebra/vector/model_vector_cosine_similarity.vhd
touch code/algebra/vector/model_vector_differentiation.vhd
touch code/algebra/vector/model_vector_integration.vhd
touch code/algebra/vector/model_vector_module.vhd
touch code/algebra/vector/model_vector_multiplication.vhd
touch code/algebra/vector/model_vector_softmax.vhd
touch code/algebra/vector/model_vector_summation.vhd
touch code/architecture/mpsoc/ahb4/accelerator_mpsoc_ahb4.vhd
touch code/architecture/mpsoc/apb4/accelerator_mpsoc_apb4.vhd
touch code/architecture/mpsoc/axi4/accelerator_mpsoc_axi4.vhd
touch code/architecture/mpsoc/bb/accelerator_mpsoc_bb.vhd
touch code/architecture/mpsoc/biu/accelerator_mpsoc_biu.vhd
touch code/architecture/mpsoc/wb/accelerator_mpsoc_wb.vhd
touch code/architecture/pu/ahb4/accelerator_pu_ahb4.vhd
touch code/architecture/pu/apb4/accelerator_pu_apb4.vhd
touch code/architecture/pu/axi4/accelerator_pu_axi4.vhd
touch code/architecture/pu/bb/accelerator_pu_bb.vhd
touch code/architecture/pu/biu/accelerator_pu_biu.vhd
touch code/architecture/pu/wb/accelerator_pu_wb.vhd
touch code/architecture/soc/ahb4/accelerator_soc_ahb4.vhd
touch code/architecture/soc/apb4/accelerator_soc_apb4.vhd
touch code/architecture/soc/axi4/accelerator_soc_axi4.vhd
touch code/architecture/soc/bb/accelerator_soc_bb.vhd
touch code/architecture/soc/biu/accelerator_soc_biu.vhd
touch code/architecture/soc/wb/accelerator_soc_wb.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_adder.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_divider.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_multiplier.vhd
touch code/arithmetic/fixed/matrix/model_matrix_fixed_subtractor.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_adder.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_divider.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_multiplier.vhd
touch code/arithmetic/fixed/scalar/model_scalar_fixed_subtractor.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_adder.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_divider.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_multiplier.vhd
touch code/arithmetic/fixed/tensor/model_tensor_fixed_subtractor.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_adder.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_divider.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_multiplier.vhd
touch code/arithmetic/fixed/vector/model_vector_fixed_subtractor.vhd
touch code/arithmetic/float/matrix/model_matrix_float_adder.vhd
touch code/arithmetic/float/matrix/model_matrix_float_divider.vhd
touch code/arithmetic/float/matrix/model_matrix_float_multiplier.vhd
touch code/arithmetic/float/matrix/model_matrix_float_subtractor.vhd
touch code/arithmetic/float/scalar/model_scalar_float_adder.vhd
touch code/arithmetic/float/scalar/model_scalar_float_divider.vhd
touch code/arithmetic/float/scalar/model_scalar_float_multiplier.vhd
touch code/arithmetic/float/scalar/model_scalar_float_subtractor.vhd
touch code/arithmetic/float/tensor/model_tensor_float_adder.vhd
touch code/arithmetic/float/tensor/model_tensor_float_divider.vhd
touch code/arithmetic/float/tensor/model_tensor_float_multiplier.vhd
touch code/arithmetic/float/tensor/model_tensor_float_subtractor.vhd
touch code/arithmetic/float/vector/model_vector_float_adder.vhd
touch code/arithmetic/float/vector/model_vector_float_divider.vhd
touch code/arithmetic/float/vector/model_vector_float_multiplier.vhd
touch code/arithmetic/float/vector/model_vector_float_subtractor.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_adder.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_divider.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_multiplier.vhd
touch code/arithmetic/integer/matrix/model_matrix_integer_subtractor.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_adder.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_divider.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_multiplier.vhd
touch code/arithmetic/integer/scalar/model_scalar_integer_subtractor.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_adder.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_divider.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_multiplier.vhd
touch code/arithmetic/integer/tensor/model_tensor_integer_subtractor.vhd
touch code/arithmetic/integer/vector/model_vector_integer_adder.vhd
touch code/arithmetic/integer/vector/model_vector_integer_divider.vhd
touch code/arithmetic/integer/vector/model_vector_integer_multiplier.vhd
touch code/arithmetic/integer/vector/model_vector_integer_subtractor.vhd
touch code/math/matrix/model_matrix_cosh_function.vhd
touch code/math/matrix/model_matrix_exponentiator_function.vhd
touch code/math/matrix/model_matrix_logarithm_function.vhd
touch code/math/matrix/model_matrix_logistic_function.vhd
touch code/math/matrix/model_matrix_oneplus_function.vhd
touch code/math/matrix/model_matrix_sinh_function.vhd
touch code/math/matrix/model_matrix_tanh_function.vhd
touch code/math/scalar/model_scalar_cosh_function.vhd
touch code/math/scalar/model_scalar_exponentiator_function.vhd
touch code/math/scalar/model_scalar_logarithm_function.vhd
touch code/math/scalar/model_scalar_logistic_function.vhd
touch code/math/scalar/model_scalar_oneplus_function.vhd
touch code/math/scalar/model_scalar_sinh_function.vhd
touch code/math/scalar/model_scalar_tanh_function.vhd
touch code/math/vector/model_vector_cosh_function.vhd
touch code/math/vector/model_vector_exponentiator_function.vhd
touch code/math/vector/model_vector_logarithm_function.vhd
touch code/math/vector/model_vector_logistic_function.vhd
touch code/math/vector/model_vector_oneplus_function.vhd
touch code/math/vector/model_vector_sinh_function.vhd
touch code/math/vector/model_vector_tanh_function.vhd
touch code/nn/fnn/convolutional/model_controller.vhd
touch code/nn/fnn/standard/model_controller.vhd
touch code/nn/lstm/convolutional/model_activation_gate_vector.vhd
touch code/nn/lstm/convolutional/model_controller.vhd
touch code/nn/lstm/convolutional/model_forget_gate_vector.vhd
touch code/nn/lstm/convolutional/model_hidden_gate_vector.vhd
touch code/nn/lstm/convolutional/model_input_gate_vector.vhd
touch code/nn/lstm/convolutional/model_output_gate_vector.vhd
touch code/nn/lstm/convolutional/model_state_gate_vector.vhd
touch code/nn/lstm/standard/model_activation_gate_vector.vhd
touch code/nn/lstm/standard/model_controller.vhd
touch code/nn/lstm/standard/model_forget_gate_vector.vhd
touch code/nn/lstm/standard/model_hidden_gate_vector.vhd
touch code/nn/lstm/standard/model_input_gate_vector.vhd
touch code/nn/lstm/standard/model_output_gate_vector.vhd
touch code/nn/lstm/standard/model_state_gate_vector.vhd
touch code/nn/ntm/memory/model_addressing.vhd
touch code/nn/ntm/memory/model_content_based_addressing.vhd
touch code/nn/ntm/read_heads/model_reading.vhd
touch code/nn/ntm/top/model_interface_matrix.vhd
touch code/nn/ntm/top/model_interface_vector.vhd
touch code/nn/ntm/top/model_output_vector.vhd
touch code/nn/ntm/top/model_top.vhd
touch code/nn/ntm/write_heads/model_erasing.vhd
touch code/nn/ntm/write_heads/model_writing.vhd
touch code/pkg/model_ann_controller_vhdl_pkg.vhd
touch code/pkg/model_arithmetic_vhdl_pkg.vhd
touch code/pkg/model_fnn_controller_vhdl_pkg.vhd
touch code/pkg/model_lstm_controller_vhdl_pkg.vhd
touch code/pkg/model_math_vhdl_pkg.vhd
touch code/pkg/model_ntm_core_vhdl_pkg.vhd
touch code/pkg/model_pnn_controller_vhdl_pkg.vhd
touch code/pkg/model_state_vhdl_pkg.vhd
touch code/trainer/differentiation/model_trainer_matrix_differentiation.vhd
touch code/trainer/differentiation/model_trainer_vector_differentiation.vhd
touch code/trainer/fnn/model_trainer.vhd
touch code/trainer/lstm/model_activation_trainer.vhd
touch code/trainer/lstm/model_forget_trainer.vhd
touch code/trainer/lstm/model_input_trainer.vhd
touch code/trainer/lstm/model_output_trainer.vhd
touch code/trainer/pnn/model_trainer.vhd
