touch library/arithmetic/matrix/ntm_matrix_adder.psl
touch library/arithmetic/matrix/ntm_matrix_divider.psl
touch library/arithmetic/matrix/ntm_matrix_multiplier.psl
touch library/arithmetic/matrix/ntm_matrix_subtract.psl
touch library/arithmetic/scalar/ntm_scalar_adder.psl
touch library/arithmetic/scalar/ntm_scalar_divider.psl
touch library/arithmetic/scalar/ntm_scalar_multiplier.psl
touch library/arithmetic/scalar/ntm_scalar_subtract.psl
touch library/arithmetic/tensor/ntm_tensor_adder.psl
touch library/arithmetic/tensor/ntm_tensor_divider.psl
touch library/arithmetic/tensor/ntm_tensor_multiplier.psl
touch library/arithmetic/tensor/ntm_tensor_subtract.psl
touch library/arithmetic/vector/ntm_vector_adder.psl
touch library/arithmetic/vector/ntm_vector_divider.psl
touch library/arithmetic/vector/ntm_vector_multiplier.psl
touch library/arithmetic/vector/ntm_vector_subtract.psl
touch library/controller/FNN/convolutional/ntm_controller.psl
touch library/controller/FNN/standard/ntm_controller.psl
touch library/controller/LSTM/convolutional/ntm_activation_gate_vector.psl
touch library/controller/LSTM/convolutional/ntm_controller.psl
touch library/controller/LSTM/convolutional/ntm_forget_gate_vector.psl
touch library/controller/LSTM/convolutional/ntm_hidden_gate_vector.psl
touch library/controller/LSTM/convolutional/ntm_input_gate_vector.psl
touch library/controller/LSTM/convolutional/ntm_output_gate_vector.psl
touch library/controller/LSTM/convolutional/ntm_state_gate_vector.psl
touch library/controller/LSTM/standard/ntm_activation_gate_vector.psl
touch library/controller/LSTM/standard/ntm_controller.psl
touch library/controller/LSTM/standard/ntm_forget_gate_vector.psl
touch library/controller/LSTM/standard/ntm_hidden_gate_vector.psl
touch library/controller/LSTM/standard/ntm_input_gate_vector.psl
touch library/controller/LSTM/standard/ntm_output_gate_vector.psl
touch library/controller/LSTM/standard/ntm_state_gate_vector.psl
touch library/math/algebra/matrix/ntm_matrix_convolution.psl
touch library/math/algebra/matrix/ntm_matrix_inverse.psl
touch library/math/algebra/matrix/ntm_matrix_multiplication.psl
touch library/math/algebra/matrix/ntm_matrix_product.psl
touch library/math/algebra/matrix/ntm_matrix_summation.psl
touch library/math/algebra/matrix/ntm_matrix_transpose.psl
touch library/math/algebra/matrix/ntm_matrix_vector_convolution.psl
touch library/math/algebra/matrix/ntm_matrix_vector_product.psl
touch library/math/algebra/matrix/ntm_transpose_vector_product.psl
touch library/math/algebra/scalar/ntm_scalar_multiplication.psl
touch library/math/algebra/scalar/ntm_scalar_summation.psl
touch library/math/algebra/tensor/ntm_tensor_convolution.psl
touch library/math/algebra/tensor/ntm_tensor_inverse.psl
touch library/math/algebra/tensor/ntm_tensor_matrix_convolution.psl
touch library/math/algebra/tensor/ntm_tensor_matrix_product.psl
touch library/math/algebra/tensor/ntm_tensor_multiplication.psl
touch library/math/algebra/tensor/ntm_tensor_product.psl
touch library/math/algebra/tensor/ntm_tensor_summation.psl
touch library/math/algebra/tensor/ntm_tensor_transpose.psl
touch library/math/algebra/vector/ntm_dot_product.psl
touch library/math/algebra/vector/ntm_vector_convolution.psl
touch library/math/algebra/vector/ntm_vector_cosine_similarity.psl
touch library/math/algebra/vector/ntm_vector_module.psl
touch library/math/algebra/vector/ntm_vector_multiplication.psl
touch library/math/algebra/vector/ntm_vector_summation.psl
touch library/math/calculus/matrix/ntm_matrix_differentiation.psl
touch library/math/calculus/matrix/ntm_matrix_integration.psl
touch library/math/calculus/matrix/ntm_matrix_softmax.psl
touch library/math/calculus/tensor/ntm_tensor_differentiation.psl
touch library/math/calculus/tensor/ntm_tensor_integration.psl
touch library/math/calculus/tensor/ntm_tensor_softmax.psl
touch library/math/calculus/vector/ntm_vector_differentiation.psl
touch library/math/calculus/vector/ntm_vector_integration.psl
touch library/math/calculus/vector/ntm_vector_softmax.psl
touch library/math/function/matrix/ntm_matrix_logistic_function.psl
touch library/math/function/matrix/ntm_matrix_oneplus_function.psl
touch library/math/function/scalar/ntm_scalar_logistic_function.psl
touch library/math/function/scalar/ntm_scalar_oneplus_function.psl
touch library/math/function/vector/ntm_vector_logistic_function.psl
touch library/math/function/vector/ntm_vector_oneplus_function.psl
touch library/math/statitics/matrix/ntm_matrix_deviation.psl
touch library/math/statitics/matrix/ntm_matrix_mean.psl
touch library/math/statitics/scalar/ntm_scalar_deviation.psl
touch library/math/statitics/scalar/ntm_scalar_mean.psl
touch library/math/statitics/vector/ntm_vector_deviation.psl
touch library/math/statitics/vector/ntm_vector_mean.psl
touch library/ntm/memory/ntm_addressing.psl
touch library/ntm/memory/ntm_matrix_content_based_addressing.psl
touch library/ntm/memory/ntm_vector_content_based_addressing.psl
touch library/ntm/read_heads/ntm_reading.psl
touch library/ntm/top/ntm_interface_matrix.psl
touch library/ntm/top/ntm_interface_top.psl
touch library/ntm/top/ntm_interface_vector.psl
touch library/ntm/top/ntm_output_vector.psl
touch library/ntm/top/ntm_top.psl
touch library/ntm/trained/ntm_trained_top.psl
touch library/ntm/write_heads/ntm_erasing.psl
touch library/ntm/write_heads/ntm_writing.psl
touch library/state/feedback/ntm_state_matrix_feedforward.psl
touch library/state/feedback/ntm_state_matrix_input.psl
touch library/state/feedback/ntm_state_matrix_output.psl
touch library/state/feedback/ntm_state_matrix_state.psl
touch library/state/outputs/ntm_state_vector_output.psl
touch library/state/outputs/ntm_state_vector_state.psl
touch library/state/top/ntm_state_top.psl
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.psl
touch library/trainer/differentiation/ntm_vector_controller_differentiation.psl
touch library/trainer/FNN/ntm_fnn_b_trainer.psl
touch library/trainer/FNN/ntm_fnn_d_trainer.psl
touch library/trainer/FNN/ntm_fnn_k_trainer.psl
touch library/trainer/FNN/ntm_fnn_trainer.psl
touch library/trainer/FNN/ntm_fnn_u_trainer.psl
touch library/trainer/FNN/ntm_fnn_v_trainer.psl
touch library/trainer/FNN/ntm_fnn_w_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.psl
touch library/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.psl
touch library/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_b_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_d_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_k_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_u_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_v_trainer.psl
touch library/trainer/LSTM/input/ntm_lstm_input_w_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_b_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_d_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_k_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_u_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_v_trainer.psl
touch library/trainer/LSTM/output/ntm_lstm_output_w_trainer.psl
touch library/transformer/components/ntm_masked_multi_head_attention.psl
touch library/transformer/components/ntm_masked_scaled_dot_product_attention.psl
touch library/transformer/components/ntm_multi_head_attention.psl
touch library/transformer/components/ntm_scaled_dot_product_attention.psl
touch library/transformer/controller/fnn/ntm_fnn.psl
touch library/transformer/controller/lstm/ntm_lstm.psl
touch library/transformer/functions/ntm_layer_norm.psl
touch library/transformer/functions/ntm_positional_encoding.psl
touch library/transformer/inputs/ntm_inputs_vector.psl
touch library/transformer/inputs/ntm_keys_vector.psl
touch library/transformer/inputs/ntm_queries_vector.psl
touch library/transformer/inputs/ntm_values_vector.psl
touch library/transformer/top/ntm_controller.psl
touch library/transformer/top/ntm_decoder.psl
touch library/transformer/top/ntm_encoder.psl
