touch library/arithmetic/matrix/ntm_matrix_arithmetic.scala
touch library/arithmetic/scalar
touch library/arithmetic/scalar/ntm_scalar_arithmetic.scala
touch library/arithmetic/tensor/ntm_tensor_arithmetic.scala
touch library/arithmetic/test_scalar_arithmetic.scala
touch library/arithmetic/vector/ntm_vector_arithmetic.scala
touch library/math/algebra/matrix/ntm_matrix_algebra.scala
touch library/math/algebra/scalar
touch library/math/algebra/scalar/ntm_scalar_algebra.scala
touch library/math/algebra/tensor/ntm_tensor_algebra.scala
touch library/math/algebra/vector/ntm_vector_algebra.scala
touch library/math/calculus/matrix/ntm_matrix_calculus.scala
touch library/math/calculus/tensor/ntm_tensor_calculus.scala
touch library/math/calculus/vector/ntm_vector_calculus.scala
touch library/math/function/matrix/ntm_matrix_function.scala
touch library/math/function/scalar
touch library/math/function/scalar/ntm_scalar_function.scala
touch library/math/function/vector/ntm_vector_function.scala
touch library/math/statitics/matrix/ntm_matrix_statitics.scala
touch library/math/statitics/scalar
touch library/math/statitics/scalar/ntm_scalar_statitics.scala
touch library/math/statitics/vector/ntm_vector_statitics.scala
touch library/nn/ANN/components/ntm_masked_multi_head_attention.scala
touch library/nn/ANN/components/ntm_masked_scaled_dot_product_attention.scala
touch library/nn/ANN/components/ntm_multi_head_attention.scala
touch library/nn/ANN/components/ntm_scaled_dot_product_attention.scala
touch library/nn/ANN/controller/fnn/ntm_fnn.scala
touch library/nn/ANN/controller/lstm/ntm_lstm.scala
touch library/nn/ANN/functions/ntm_layer_norm.scala
touch library/nn/ANN/functions/ntm_positional_encoding.scala
touch library/nn/ANN/inputs/ntm_inputs_vector.scala
touch library/nn/ANN/inputs/ntm_keys_vector.scala
touch library/nn/ANN/inputs/ntm_queries_vector.scala
touch library/nn/ANN/inputs/ntm_values_vector.scala
touch library/nn/ANN/top/ntm_controller.scala
touch library/nn/ANN/top/ntm_decoder.scala
touch library/nn/ANN/top/ntm_encoder.scala
touch library/nn/FNN/convolutional/ntm_controller.scala
touch library/nn/FNN/standard/ntm_controller.scala
touch library/nn/LSTM/convolutional/ntm_activation_gate_vector.scala
touch library/nn/LSTM/convolutional/ntm_controller.scala
touch library/nn/LSTM/convolutional/ntm_forget_gate_vector.scala
touch library/nn/LSTM/convolutional/ntm_hidden_gate_vector.scala
touch library/nn/LSTM/convolutional/ntm_input_gate_vector.scala
touch library/nn/LSTM/convolutional/ntm_output_gate_vector.scala
touch library/nn/LSTM/convolutional/ntm_state_gate_vector.scala
touch library/nn/LSTM/standard/ntm_activation_gate_vector.scala
touch library/nn/LSTM/standard/ntm_controller.scala
touch library/nn/LSTM/standard/ntm_forget_gate_vector.scala
touch library/nn/LSTM/standard/ntm_hidden_gate_vector.scala
touch library/nn/LSTM/standard/ntm_input_gate_vector.scala
touch library/nn/LSTM/standard/ntm_output_gate_vector.scala
touch library/nn/LSTM/standard/ntm_state_gate_vector.scala
touch library/nn/NTM/memory/ntm_addressing.scala
touch library/nn/NTM/memory/ntm_matrix_content_based_addressing.scala
touch library/nn/NTM/memory/ntm_vector_content_based_addressing.scala
touch library/nn/NTM/read_heads/ntm_reading.scala
touch library/nn/NTM/top/ntm_interface_matrix.scala
touch library/nn/NTM/top/ntm_interface_top.scala
touch library/nn/NTM/top/ntm_interface_vector.scala
touch library/nn/NTM/top/ntm_output_vector.scala
touch library/nn/NTM/top/ntm_top.scala
touch library/nn/NTM/trained/ntm_trained_top.scala
touch library/nn/NTM/write_heads/ntm_erasing.scala
touch library/nn/NTM/write_heads/ntm_writing.scala
touch library/state/feedback/ntm_state_feedback.scala
touch library/state/outputs/ntm_state_outputs.scala
touch library/state/top/ntm_state_top.scala
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.scala
touch library/trainer/differentiation/ntm_vector_controller_differentiation.scala
touch library/trainer/FNN/ntm_fnn_b_trainer.scala
touch library/trainer/FNN/ntm_fnn_d_trainer.scala
touch library/trainer/FNN/ntm_fnn_k_trainer.scala
touch library/trainer/FNN/ntm_fnn_trainer.scala
touch library/trainer/FNN/ntm_fnn_u_trainer.scala
touch library/trainer/FNN/ntm_fnn_v_trainer.scala
touch library/trainer/FNN/ntm_fnn_w_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.scala
touch library/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.scala
touch library/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_b_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_d_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_k_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_u_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_v_trainer.scala
touch library/trainer/LSTM/input/ntm_lstm_input_w_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_b_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_d_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_k_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_u_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_v_trainer.scala
touch library/trainer/LSTM/output/ntm_lstm_output_w_trainer.scala
