touch library/algebra/matrix/accelerator_matrix_convolution.m
touch library/algebra/matrix/accelerator_matrix_differentiation.m
touch library/algebra/matrix/accelerator_matrix_integration.m
touch library/algebra/matrix/accelerator_matrix_inverse.m
touch library/algebra/matrix/accelerator_matrix_multiplication.m
touch library/algebra/matrix/accelerator_matrix_product.m
touch library/algebra/matrix/accelerator_matrix_softmax.m
touch library/algebra/matrix/accelerator_matrix_summation.m
touch library/algebra/matrix/accelerator_matrix_transpose.m
touch library/algebra/matrix/accelerator_matrix_vector_convolution.m
touch library/algebra/matrix/accelerator_matrix_vector_product.m
touch library/algebra/matrix/accelerator_transpose_vector_product.m
touch library/algebra/scalar/accelerator_scalar_multiplication.m
touch library/algebra/scalar/accelerator_scalar_summation.m
touch library/algebra/tensor/accelerator_tensor_convolution.m
touch library/algebra/tensor/accelerator_tensor_differentiation.m
touch library/algebra/tensor/accelerator_tensor_integration.m
touch library/algebra/tensor/accelerator_tensor_inverse.m
touch library/algebra/tensor/accelerator_tensor_matrix_convolution.m
touch library/algebra/tensor/accelerator_tensor_matrix_product.m
touch library/algebra/tensor/accelerator_tensor_multiplication.m
touch library/algebra/tensor/accelerator_tensor_product.m
touch library/algebra/tensor/accelerator_tensor_softmax.m
touch library/algebra/tensor/accelerator_tensor_summation.m
touch library/algebra/tensor/accelerator_tensor_transpose.m
touch library/algebra/vector/accelerator_dot_product.m
touch library/algebra/vector/accelerator_vector_convolution.m
touch library/algebra/vector/accelerator_vector_cosine_similarity.m
touch library/algebra/vector/accelerator_vector_differentiation.m
touch library/algebra/vector/accelerator_vector_integration.m
touch library/algebra/vector/accelerator_vector_module.m
touch library/algebra/vector/accelerator_vector_multiplication.m
touch library/algebra/vector/accelerator_vector_softmax.m
touch library/algebra/vector/accelerator_vector_summation.m
touch library/arithmetic/matrix/accelerator_matrix_adder.m
touch library/arithmetic/matrix/accelerator_matrix_divider.m
touch library/arithmetic/matrix/accelerator_matrix_multiplier.m
touch library/arithmetic/matrix/accelerator_matrix_subtractor.m
touch library/arithmetic/MatrixArithmetic.m
touch library/arithmetic/scalar/accelerator_scalar_adder.m
touch library/arithmetic/scalar/accelerator_scalar_divider.m
touch library/arithmetic/scalar/accelerator_scalar_multiplier.m
touch library/arithmetic/scalar/accelerator_scalar_subtractor.m
touch library/arithmetic/ScalarArithmetic.m
touch library/arithmetic/tensor/accelerator_tensor_adder.m
touch library/arithmetic/tensor/accelerator_tensor_divider.m
touch library/arithmetic/tensor/accelerator_tensor_multiplier.m
touch library/arithmetic/tensor/accelerator_tensor_subtractor.m
touch library/arithmetic/TensorArithmetic.m
touch library/arithmetic/vector/accelerator_vector_adder.m
touch library/arithmetic/vector/accelerator_vector_divider.m
touch library/arithmetic/vector/accelerator_vector_multiplier.m
touch library/arithmetic/vector/accelerator_vector_subtractor.m
touch library/arithmetic/VectorArithmetic.m
touch library/math/matrix/accelerator_matrix_deviation_function.m
touch library/math/matrix/accelerator_matrix_logistic_function.m
touch library/math/matrix/accelerator_matrix_mean_function.m
touch library/math/matrix/accelerator_matrix_oneplus_function.m
touch library/math/scalar/accelerator_scalar_deviation_function.m
touch library/math/scalar/accelerator_scalar_logistic_function.m
touch library/math/scalar/accelerator_scalar_mean_function.m
touch library/math/scalar/accelerator_scalar_oneplus_function.m
touch library/math/vector/accelerator_vector_deviation_function.m
touch library/math/vector/accelerator_vector_logistic_function.m
touch library/math/vector/accelerator_vector_mean_function.m
touch library/math/vector/accelerator_vector_oneplus_function.m
touch library/nn/ann/components/accelerator_masked_multi_head_attention.m
touch library/nn/ann/components/accelerator_masked_scaled_dot_product_attention.m
touch library/nn/ann/components/accelerator_multi_head_attention.m
touch library/nn/ann/components/accelerator_scaled_dot_product_attention.m
touch library/nn/ann/controller/fnn/accelerator_fnn.m
touch library/nn/ann/controller/lstm/accelerator_lstm.m
touch library/nn/ann/functions/accelerator_layer_norm.m
touch library/nn/ann/functions/accelerator_positional_encoding.m
touch library/nn/ann/inputs/accelerator_inputs_vector.m
touch library/nn/ann/inputs/accelerator_keys_vector.m
touch library/nn/ann/inputs/accelerator_queries_vector.m
touch library/nn/ann/inputs/accelerator_values_vector.m
touch library/nn/ann/top/accelerator_controller.m
touch library/nn/ann/top/accelerator_decoder.m
touch library/nn/ann/top/accelerator_encoder.m
touch library/nn/dnc/memory/accelerator_addressing.m
touch library/nn/dnc/memory/accelerator_allocation_weighting.m
touch library/nn/dnc/memory/accelerator_backward_weighting.m
touch library/nn/dnc/memory/accelerator_forward_weighting.m
touch library/nn/dnc/memory/accelerator_matrix_content_based_addressing.m
touch library/nn/dnc/memory/accelerator_memory_matrix.m
touch library/nn/dnc/memory/accelerator_memory_retention_vector.m
touch library/nn/dnc/memory/accelerator_precedence_weighting.m
touch library/nn/dnc/memory/accelerator_sort_vector.m
touch library/nn/dnc/memory/accelerator_temporal_link_matrix.m
touch library/nn/dnc/memory/accelerator_usage_vector.m
touch library/nn/dnc/memory/accelerator_vector_content_based_addressing.m
touch library/nn/dnc/read_heads/accelerator_read_content_weighting.m
touch library/nn/dnc/read_heads/accelerator_read_vectors.m
touch library/nn/dnc/read_heads/accelerator_read_weighting.m
touch library/nn/dnc/top/accelerator_interface_matrix.m
touch library/nn/dnc/top/accelerator_interface_top.m
touch library/nn/dnc/top/accelerator_interface_vector.m
touch library/nn/dnc/top/accelerator_output_vector.m
touch library/nn/dnc/top/accelerator_top.m
touch library/nn/dnc/trained/accelerator_trained_top.m
touch library/nn/dnc/write_heads/accelerator_write_content_weighting.m
touch library/nn/dnc/write_heads/accelerator_write_weighting.m
touch library/nn/fnn/convolutional/accelerator_controller.m
touch library/nn/fnn/standard/accelerator_controller.m
touch library/nn/lstm/convolutional/accelerator_activation_gate_vector.m
touch library/nn/lstm/convolutional/accelerator_controller.m
touch library/nn/lstm/convolutional/accelerator_forget_gate_vector.m
touch library/nn/lstm/convolutional/accelerator_hidden_gate_vector.m
touch library/nn/lstm/convolutional/accelerator_input_gate_vector.m
touch library/nn/lstm/convolutional/accelerator_output_gate_vector.m
touch library/nn/lstm/convolutional/accelerator_state_gate_vector.m
touch library/nn/lstm/standard/accelerator_activation_gate_vector.m
touch library/nn/lstm/standard/accelerator_controller.m
touch library/nn/lstm/standard/accelerator_forget_gate_vector.m
touch library/nn/lstm/standard/accelerator_hidden_gate_vector.m
touch library/nn/lstm/standard/accelerator_input_gate_vector.m
touch library/nn/lstm/standard/accelerator_output_gate_vector.m
touch library/nn/lstm/standard/accelerator_state_gate_vector.m
touch library/nn/ntm/memory/accelerator_addressing.m
touch library/nn/ntm/memory/accelerator_matrix_content_based_addressing.m
touch library/nn/ntm/memory/accelerator_vector_content_based_addressing.m
touch library/nn/ntm/read_heads/accelerator_reading.m
touch library/nn/ntm/top/accelerator_interface_matrix.m
touch library/nn/ntm/top/accelerator_interface_top.m
touch library/nn/ntm/top/accelerator_interface_vector.m
touch library/nn/ntm/top/accelerator_output_vector.m
touch library/nn/ntm/top/accelerator_top.m
touch library/nn/ntm/trained/accelerator_trained_top.m
touch library/nn/ntm/write_heads/accelerator_erasing.m
touch library/nn/ntm/write_heads/accelerator_writing.m
touch library/trainer/differentiation/accelerator_matrix_controller_differentiation.m
touch library/trainer/differentiation/accelerator_vector_controller_differentiation.m
touch library/trainer/fnn/accelerator_fnn_b_trainer.m
touch library/trainer/fnn/accelerator_fnn_d_trainer.m
touch library/trainer/fnn/accelerator_fnn_k_trainer.m
touch library/trainer/fnn/accelerator_fnn_trainer.m
touch library/trainer/fnn/accelerator_fnn_u_trainer.m
touch library/trainer/fnn/accelerator_fnn_v_trainer.m
touch library/trainer/fnn/accelerator_fnn_w_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_b_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_d_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_k_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_u_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_v_trainer.m
touch library/trainer/lstm/activation/accelerator_lstm_activation_w_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_b_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_d_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_k_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_u_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_v_trainer.m
touch library/trainer/lstm/forget/accelerator_lstm_forget_w_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_b_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_d_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_k_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_u_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_v_trainer.m
touch library/trainer/lstm/input/accelerator_lstm_input_w_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_b_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_d_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_k_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_u_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_v_trainer.m
touch library/trainer/lstm/output/accelerator_lstm_output_w_trainer.m
