touch library/arithmetic
touch library/arithmetic/matrix
touch library/arithmetic/matrix/MatrixArithmetic.m
touch library/arithmetic/matrix/ntm_matrix_adder.m
touch library/arithmetic/matrix/ntm_matrix_divider.m
touch library/arithmetic/matrix/ntm_matrix_multiplier.m
touch library/arithmetic/matrix/ntm_matrix_subtractor.m
touch library/arithmetic/scalar
touch library/arithmetic/scalar/ntm_scalar_adder.m
touch library/arithmetic/scalar/ntm_scalar_divider.m
touch library/arithmetic/scalar/ntm_scalar_multiplier.m
touch library/arithmetic/scalar/ntm_scalar_subtractor.m
touch library/arithmetic/scalar/ScalarArithmetic.m
touch library/arithmetic/tensor
touch library/arithmetic/tensor/ntm_tensor_adder.m
touch library/arithmetic/tensor/ntm_tensor_divider.m
touch library/arithmetic/tensor/ntm_tensor_multiplier.m
touch library/arithmetic/tensor/ntm_tensor_subtractor.m
touch library/arithmetic/tensor/TensorArithmetic.m
touch library/arithmetic/vector
touch library/arithmetic/vector/ntm_vector_adder.m
touch library/arithmetic/vector/ntm_vector_divider.m
touch library/arithmetic/vector/ntm_vector_multiplier.m
touch library/arithmetic/vector/ntm_vector_subtractor.m
touch library/arithmetic/vector/VectorArithmetic.m
touch library/math
touch library/math/algebra
touch library/math/algebra/matrix
touch library/math/algebra/matrix/ntm_matrix_convolution.m
touch library/math/algebra/matrix/ntm_matrix_inverse.m
touch library/math/algebra/matrix/ntm_matrix_multiplication.m
touch library/math/algebra/matrix/ntm_matrix_product.m
touch library/math/algebra/matrix/ntm_matrix_summation.m
touch library/math/algebra/matrix/ntm_matrix_transpose.m
touch library/math/algebra/matrix/ntm_matrix_vector_convolution.m
touch library/math/algebra/matrix/ntm_matrix_vector_product.m
touch library/math/algebra/matrix/ntm_transpose_vector_product.m
touch library/math/algebra/scalar
touch library/math/algebra/scalar/ntm_scalar_multiplication.m
touch library/math/algebra/scalar/ntm_scalar_summation.m
touch library/math/algebra/tensor
touch library/math/algebra/tensor/ntm_tensor_convolution.m
touch library/math/algebra/tensor/ntm_tensor_inverse.m
touch library/math/algebra/tensor/ntm_tensor_matrix_convolution.m
touch library/math/algebra/tensor/ntm_tensor_matrix_product.m
touch library/math/algebra/tensor/ntm_tensor_multiplication.m
touch library/math/algebra/tensor/ntm_tensor_product.m
touch library/math/algebra/tensor/ntm_tensor_summation.m
touch library/math/algebra/tensor/ntm_tensor_transpose.m
touch library/math/algebra/vector
touch library/math/algebra/vector/ntm_dot_product.m
touch library/math/algebra/vector/ntm_vector_convolution.m
touch library/math/algebra/vector/ntm_vector_cosine_similarity.m
touch library/math/algebra/vector/ntm_vector_module.m
touch library/math/algebra/vector/ntm_vector_multiplication.m
touch library/math/algebra/vector/ntm_vector_summation.m
touch library/math/calculus
touch library/math/calculus/matrix
touch library/math/calculus/matrix/ntm_matrix_differentiation.m
touch library/math/calculus/matrix/ntm_matrix_integration.m
touch library/math/calculus/matrix/ntm_matrix_softmax.m
touch library/math/calculus/tensor
touch library/math/calculus/tensor/ntm_tensor_differentiation.m
touch library/math/calculus/tensor/ntm_tensor_integration.m
touch library/math/calculus/tensor/ntm_tensor_softmax.m
touch library/math/calculus/vector
touch library/math/calculus/vector/ntm_vector_differentiation.m
touch library/math/calculus/vector/ntm_vector_integration.m
touch library/math/calculus/vector/ntm_vector_softmax.m
touch library/math/function
touch library/math/function/matrix
touch library/math/function/matrix/ntm_matrix_logistic_function.m
touch library/math/function/matrix/ntm_matrix_oneplus_function.m
touch library/math/function/scalar
touch library/math/function/scalar/ntm_scalar_logistic_function.m
touch library/math/function/scalar/ntm_scalar_oneplus_function.m
touch library/math/function/vector
touch library/math/function/vector/ntm_vector_logistic_function.m
touch library/math/function/vector/ntm_vector_oneplus_function.m
touch library/math/statitics
touch library/math/statitics/matrix
touch library/math/statitics/matrix/ntm_matrix_deviation.m
touch library/math/statitics/matrix/ntm_matrix_mean.m
touch library/math/statitics/scalar
touch library/math/statitics/scalar/ntm_scalar_deviation.m
touch library/math/statitics/scalar/ntm_scalar_mean.m
touch library/math/statitics/vector
touch library/math/statitics/vector/ntm_vector_deviation.m
touch library/math/statitics/vector/ntm_vector_mean.m
touch library/nn/ANN/components
touch library/nn/ANN/components/ntm_masked_multi_head_attention.m
touch library/nn/ANN/components/ntm_masked_scaled_dot_product_attention.m
touch library/nn/ANN/components/ntm_multi_head_attention.m
touch library/nn/ANN/components/ntm_scaled_dot_product_attention.m
touch library/nn/ANN/controller/fnn/ntm_fnn.m
touch library/nn/ANN/controller/lstm
touch library/nn/ANN/controller/lstm/ntm_lstm.m
touch library/nn/ANN/functions/ntm_layer_norm.m
touch library/nn/ANN/functions/ntm_positional_encoding.m
touch library/nn/ANN/inputs/ntm_inputs_vector.m
touch library/nn/ANN/inputs/ntm_keys_vector.m
touch library/nn/ANN/inputs/ntm_queries_vector.m
touch library/nn/ANN/inputs/ntm_values_vector.m
touch library/nn/ANN/top/ntm_controller.m
touch library/nn/ANN/top/ntm_decoder.m
touch library/nn/ANN/top/ntm_encoder.m
touch library/nn/FNN/convolutional/ntm_controller.m
touch library/nn/FNN/standard/ntm_controller.m
touch library/nn/LSTM/convolutional/ntm_activation_gate_vector.m
touch library/nn/LSTM/convolutional/ntm_controller.m
touch library/nn/LSTM/convolutional/ntm_forget_gate_vector.m
touch library/nn/LSTM/convolutional/ntm_hidden_gate_vector.m
touch library/nn/LSTM/convolutional/ntm_input_gate_vector.m
touch library/nn/LSTM/convolutional/ntm_output_gate_vector.m
touch library/nn/LSTM/convolutional/ntm_state_gate_vector.m
touch library/nn/LSTM/standard/ntm_activation_gate_vector.m
touch library/nn/LSTM/standard/ntm_controller.m
touch library/nn/LSTM/standard/ntm_forget_gate_vector.m
touch library/nn/LSTM/standard/ntm_hidden_gate_vector.m
touch library/nn/LSTM/standard/ntm_input_gate_vector.m
touch library/nn/LSTM/standard/ntm_output_gate_vector.m
touch library/nn/LSTM/standard/ntm_state_gate_vector.m
touch library/nn/NTM/memory
touch library/nn/NTM/memory/ntm_addressing.m
touch library/nn/NTM/memory/ntm_matrix_content_based_addressing.m
touch library/nn/NTM/memory/ntm_vector_content_based_addressing.m
touch library/nn/NTM/read_heads/ntm_reading.m
touch library/nn/NTM/top/ntm_interface_matrix.m
touch library/nn/NTM/top/ntm_interface_top.m
touch library/nn/NTM/top/ntm_interface_vector.m
touch library/nn/NTM/top/ntm_output_vector.m
touch library/nn/NTM/top/ntm_top.m
touch library/nn/NTM/trained/ntm_trained_top.m
touch library/nn/NTM/write_heads/ntm_erasing.m
touch library/nn/NTM/write_heads/ntm_writing.m
touch library/state/feedback/ntm_state_matrix_feedforward.m
touch library/state/feedback/ntm_state_matrix_input.m
touch library/state/feedback/ntm_state_matrix_output.m
touch library/state/feedback/ntm_state_matrix_state.m
touch library/state/outputs/ntm_state_vector_output.m
touch library/state/outputs/ntm_state_vector_state.m
touch library/state/top/ntm_state_top.m
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.m
touch library/trainer/differentiation/ntm_vector_controller_differentiation.m
touch library/trainer/FNN/ntm_fnn_b_trainer.m
touch library/trainer/FNN/ntm_fnn_d_trainer.m
touch library/trainer/FNN/ntm_fnn_k_trainer.m
touch library/trainer/FNN/ntm_fnn_trainer.m
touch library/trainer/FNN/ntm_fnn_u_trainer.m
touch library/trainer/FNN/ntm_fnn_v_trainer.m
touch library/trainer/FNN/ntm_fnn_w_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.m
touch library/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.m
touch library/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_b_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_d_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_k_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_u_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_v_trainer.m
touch library/trainer/LSTM/input/ntm_lstm_input_w_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_b_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_d_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_k_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_u_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_v_trainer.m
touch library/trainer/LSTM/output/ntm_lstm_output_w_trainer.m
